### PR TITLE
Have use-before-def error message point to where symbol was defined

### LINKED ISSUE #10034: Use before def errors should also note where the used variable is defined
### Summary of Problem
As seen in #9985, if an outer scoped variable shares a name with a more local scoped variable defined after the use, it can be confusing to tell which symbol is meant in the error message.  If the more local scoped variable is defined much later in the scope than its use-before-def, it would be hard to track it down to rename it or otherwise avoid the error.  It would be nice for this error message to also include the location where the matched variable is defined.

### Steps to Reproduce

**Source Code:**

```chapel
proc main() {
  var a = 12;
  {
    var b = a; // This actually refers to the variable on the following line, but the user thinks they are referring to the one above
    var a = 1;
  }
}
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[`test/visibility/scoping-shadows-error-message.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/visibility/scoping-shadows-error-message.chpl) #1234

### Configuration Information

- Output of `chpl --version`: 1.18.0 (pre-release

### PR DESCRIPTION
**Pull request by bradcray**
In issue #10034 (and #9985 before that), it was noted that the error message for cases that misunderstand Chapel's use-before-def rules in the case of shadowing an outer variable like

```chapel
var a;
{
  var b = a;
  var a = 1;
}
```

were confusing.  This change tries to improve this by having the error message point to the point of definition to clarify that it's the local shadow variable, not the outer variable.

Note that there are other use-before-def errors generated by the compiler, particularly when initializing fields out-of-order that this commit does not improve.  I took a quick look at those cases, but wasn't seeing the way to get to the definition point easily before I timed out.

Resolves #10034.

### CODE REVIEW

File: compiler/passes/normalize.cpp [hunk 1]
```diff
@@ -647,8 +647,8 @@ void checkUseBeforeDefs(FnSymbol* fn) {
                 // Only complain one time
                 if (undefined.find(sym) == undefined.end()) {
                   USR_FATAL_CONT(se,
-                                 "'%s' used before defined (first used here)",
-                                 sym->name);
+                                 "'%s' used before defined (defined here: %s:%d)",
+                                 sym->name, sym->defPoint->fname(), sym->defPoint->linenum());
```
Comment (vasslitvinov) [inline compiler/passes/normalize.cpp]: how about simply sym->defPoint->stringLoc() ?
