### PR TITLE
Fix no dead code elimination bug

### LINKED ISSUE #22560: Compiler error using ```--no-dead-code-elimination```
### Summary of Problem
When compiling any(?) Chapel program with the ```--no-dead-code-elimination``` it produces the following error:

``` 
error: Could not find C variable none_chpl - perhaps it is a complex macro?
```

### Steps to Reproduce

**Source Code:**

```chapel
config const numMessages = 100;
forall msg in 1..numMessages do
  writeln("Hello, world! (from iteration ", msg, " of ", numMessages, ")");
```

**Compile command:**
``` chpl foo.chpl --no-dead-code-elimination```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.30.0
  built with LLVM version 14.0.6
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: bundled *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
Resolves #22560.

Fix compilation with `--no-dead-code-elimination` by pruning statement-level uses of `none`.

Such uses can appear when an `inline` function is inlined and its return statements are pruned away. The `none` value is left behind as a statement-level expression. Normally, it would be code-eliminated, but here it persists until codegen and confuses the generator (no type for `nothing`).

TESTING

- [x] `linux64`, `standard`

Reviewed by @vasslitvinov. Thanks!

### CODE REVIEW

File: compiler/AST/FnSymbol.cpp [hunk 1]
```diff
@@ -1025,6 +1025,10 @@ bool FnSymbol::isAnonymous() const {
   return hasFlag(FLAG_ANONYMOUS_FN) || hasFlag(FLAG_LEGACY_LAMBDA);
 }
 
+bool FnSymbol::isInline() const {
+  return hasFlag(FLAG_INLINE);
+}
```
Comment (vasslitvinov) [inline compiler/AST/FnSymbol.cpp:1030]: I do not think we need `isInline()`. Remove it from the PR (also in .h)?

**Review by vasslitvinov — APPROVED** [review]

File: compiler/AST/FnSymbol.cpp (hunk 1 above)
Comment (vasslitvinov) [reply compiler/AST/FnSymbol.cpp:1030]: That's why I wrote `bool hasFlag(BaseAST* ast, int flag)` et al. :)

Comment (dlongnecke-cray) [reply compiler/AST/FnSymbol.cpp:1030]: Oh, perfect! 🎉  Yet another thing I don't know or forgot about! 😁 You re-learn things every day!
