### PR TITLE
Fix bug with records obtained from another scope without an import or use

### LINKED ISSUE #10397: fields not usable after Module.getRecord()
The following programs do not compile but one might expect them to.

In both cases, an explicit module decorates a function call to a module that is not used (e.g. `C.make_struct()` ). This function returns a record. Following code cannot access the record's field.

 test/classes/ferguson/module-call-returns-type.chpl

``` chapel
module C {
  record my_struct {
    var my_field:c_int;
  }

  proc make_struct():my_struct {
    var ret:my_struct;
    ret.my_field = 0;
    return ret;
  }
}

proc test() {
  var tmp = C.make_struct();
  var f = tmp.my_field;
  writeln(f);
}

test();
```

 test/extern/ferguson/externblock/extern-record-field-scope-issue.chpl

``` chapel
module C {
  extern {
    typedef struct my_struct {
      int my_field;
    } my_struct;

    static my_struct make_struct(void) {
      my_struct ret;
      ret.my_field = 0;
      return ret;
    }
  }
}

proc test() {
  var tmp = C.make_struct();
  var f = tmp.my_field;
  writeln(f);
}

test();
```

### LINKED ISSUE #11868: Inconsistent behavior when using module's class/record without `use` statement
Related #7857

Echoing [this statement](https://github.com/chapel-lang/chapel/issues/7857#issuecomment-363211386),
> It doesn't appear intuitive to allow constructing an object with the module prefix, but then prevent use of methods inside that object.

```chapel
module A {
  class C {
    var x: int;
    proc foo() { return x; }
  }
  record R {
    var x: int;
    proc foo() { return x; }
  }
}

// use A only;

var c1: A.C; // Ok
var c2 = new owned A.C(); // Ok

var r1: A.R; // error: unresolved call 'R.init()'
var r2 = new A.R(); // Ok
```

This behavior is inconsistent.
- `r1` is the only one that fails, and I didn't bring `module A` into scope with a `use` statement.

And non-intuitive.
- If I can define these variables, I should be allowed to use them. If I try to use the members of `C` and `R`, it predictably fails without a `use` statement.

```chapel
// c1 is nil; don't use it.

// These lines do not compile without `use A`.
writeln(c2.x);
writeln(c2.foo());

// r1 did not compile, so ignore it.

// These lines do not compile without `use A`.
writeln(r2.x);
writeln(r2.foo());
```
Of course, if I `use A only`, everything works.

Questions.
1. Why am I allowed to define a variable or construct an object, but not use its members when I do not have `use module [only]` active in the current scope?
2. What is the difference between `r1` and `r2` that allows `r2` to work when `r1`'s definition did not?

### PR DESCRIPTION
**Pull request by lydia-duncan**
There are some situations where it is reasonable to expect to use the
fields and methods of a record type from another scope and other
situations where it is not.  Prior to this change, one was unable to use
the fields and methods of a record obtained via explicitly naming the
scope where the record was defined, either if it was defined in a 
submodule of the current scope or if its enclosing scope was
visible due to a use or import of its parent module.  For instance, the
following code was expected to compile and run, but would fail to
resolve the record initializer (even though it knew how to find the
record type):

```chapel
module A {
  record R {
    var x: int;
    proc foo() { return x; }
  }
}

var r1: A.R;              // error: unresolved call 'R.init()'
var r2 = new A.R(); // This line was fine, but subsequent methods calls weren't
```

This change fixes that issue.  Hopefully it handles the last of the cases
where we obtain a record and expect to be able to operate on it, but cannot.

Resolves #11868 
Resolves #10397

<details>
This change adds a new primitive to track named references to symbols within
modules.  This primitive is then stored on the nearest enclosing BlockStmt, similar
to the storage of the useList.  When we reach visibleFunction determination for
methods, we then traverse this list after following all use and import statements in
the current scope.

There were several alternatives to this strategy considered.  Here are their problems:
- Storing the referenced module in the useList might allow code in the same scope
after the explicit statement to utilize symbols incorrectly, e.g. by allowing
unqualified access if a UseStmt is inserted or by shadowing outer-scoped variables
with the same name as the module if the module is explicitly named through a longer
path (if `A.B.foo` causes an import of A.B, references to an outer-scoped symbol B
might accidentally think it should use the module).
- Traversing the module's used modules list allows inner scopes with such references
to impact the symbols available throughout the entire module.
</details>

Testing changes
-----------------
Checks various scenarios where an instance of a record is created using a long
explicit path to the record rather than an import or use of the scope where the
record is defined.  Some of these were motivated by examining the code being
written.

- direct submodule
- subsubmodule
- in a sibling module when the parent module is imported
- in a sibling module when the parent module is used
- ensuring that the nested module doesn't hide a symbol with the same name
- explicitly naming a type for a record's field
- explicitly naming a type that has explicitly named a type in another module
for a field
- explicitly naming a type for an argument
- explicitly naming a type for an argument in a nested function
- explicitly naming a type while in a forall loop
- explicitly naming a type while in a forall stmt

Also removes the .bad and .future file for the test tracked in #10397,
test/classes/ferguson/module-call-returns-type.chpl

TODO:
- [x] sanity paratest after latest cleanup

### CODE REVIEW

File: compiler/passes/scopeResolve.cpp [hunk 1]
```diff
@@ -1168,6 +1168,19 @@ static void setupShadowVars() {
...
+// Track modules that we name explicitly in the scope where we do so
+static void storeReferencedMod(ModuleSymbol* mod, BaseAST* cur) {
+  if (cur == NULL) {
+    return;
+  }
+  BaseAST* scope = getScope(cur);
+  if (BlockStmt* block = toBlockStmt(scope)) {
+    block->modRefsAdd(mod);
+  } else {
+    storeReferencedMod(mod, scope);
```
Comment (mppf) [inline compiler/passes/scopeResolve.cpp:1180]: Not a big deal, but I personally think it better to write this simple traversal as a loop

Comment (lydia-duncan) [reply compiler/passes/scopeResolve.cpp:1180]: You know, I'm not entirely certain why I chose to make it a recursive function instead XD
