### PR TITLE
Fix (basic) llvm library mode with C

### LINKED ISSUE #9687: LLVM compilation with --library uses wrong compiler flags
When using the `--library` flag, by comparing the `--savec` output between the C back end and the LLVM back end, it can be seen that the LLVM back end passes only `.o` files to the compile step.  Because it is the compile step, many non-link-time flags are passed, but because there are only `.o` files, clang runs as the linker and complains that there are unused command line arguments.

Fixing this is necessary to make Chapel libraries work, which is necessary to make the LLVM back end work with Cython.

The LLVM back end should probably skip the compile step in the `--library` case.  That might be sufficient to fix the problem and make libraries work with LLVM.

### PR DESCRIPTION
**Pull request by lydia-duncan**
Prior to this change, compiling with `--llvm --library` would create an
executable instead of a library file.  This change adds a branch for
library compilation to the LLVM code generation.  While there, it also
splits some of the old functionality into separate functions.

It does not fix Python library compilation, and also does not fix the
handling when launchers are involved or `CHPL_LIB_PIC` is set.

Adds a partial copy of the interop/C test directory for LLVM testing.
Some of these tests do not work today (specifically those involving
`--library-makefile`, returning `chpl_external_array`, or operating on
`chpl_opaque_array`).  I have action items to work on them and the
issues in the previous paragraph.

Resolves #9687, #12459

Passed a full test run with CHPL_LLVM=llvm on linux and the new
directory with CHPL_LLVM=llvm on my Mac

### CODE REVIEW

File: compiler/llvm/clangUtil.cpp [hunk 1]
```diff
@@ -3018,84 +3084,141 @@ void makeBinaryLLVM(void) {
...
+  bool startsWithLib = strncmp(executableFilename, "lib", libLength) == 0;
+  if (!startsWithLib) {
+    libraryPrefix = "lib";
+  }
+  const char* fullLibraryName = astr(libDir, "/", libraryPrefix,
+                                     executableFilename, exeExt);
+
+  std::error_code err;
+
+  // rm -f hello
```
Comment (mppf) [inline compiler/llvm/clangUtil.cpp]: Could we have a new function in this file like `moveResultFromTmp` that does the removing / moving / copying across filesystems?

File: compiler/llvm/clangUtil.cpp [hunk 2]
```diff
@@ -2974,6 +2984,62 @@ void makeBinaryLLVM(void) {
...
+      fflush(stdout); fflush(stderr);
+    }
+
+    mysystem(makecmd, "Make Binary - Building Launcher and Copying");
+  }
+}
+
+static void makeLLVMLibrary(std::string moduleFilename, const char* tmpbinname,
+                            std::vector<std::string> dotOFiles) {
+  std::string commandBase = "ar -c -r -s"; // Stolen from Makefile.static
```
Comment (mppf) [inline compiler/llvm/clangUtil.cpp]: Usually it's possible to override the AR command in a Makefile setting. It might be worth offering a way to do to that (but that can be future work).

File: compiler/llvm/clangUtil.cpp [hunk 3]
```diff
@@ -2559,6 +2559,16 @@ void checkAdjustedDataLayout() {
...
 }
 
+static void makeLLVMLibrary(std::string moduleFilename, const char* tmpbinname,
+                            std::vector<std::string> dotOFiles);
+static void runLLVMLinking(std::string useLinkCXX, std::string options,
+                           std::string moduleFilename, std::string maino,
+                           const char* tmpbinname,
+                           std::vector<std::string> dotOFiles,
+                           std::vector<std::string> clangLDArgs,
+                           bool saw_sysroot);
```
Comment (mppf) [inline compiler/llvm/clangUtil.cpp]: let's call it sawSysroot

File: test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl [hunk 4]
```diff
@@ -0,0 +1,4 @@
+export proc foo(x: [?D] int) {
```
Comment (mppf) [inline test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl]: There's quite a lot of tests here. I'm hoping that in the future, we'll remove the `test/interop/C/llvm` directory and `test/interop/C` will cover the LLVM or C case depending on if the test run is already using `--llvm`. Otherwise it seems like we are making it harder for ourselves with all the duplication. 

Generally speaking I'd be happier with `test/interop/C` having skipifs for the tests that don't work yet with `--llvm` but the solution in this PR OK for the moment.

File: compiler/llvm/clangUtil.cpp [hunk 5]
```diff
@@ -3018,84 +3084,141 @@ void makeBinaryLLVM(void) {
...
+
+    std::string mv("mv ");
+    mv += tmpbinname;
+    mv += " ";
+    mv += fullLibraryName;
+
+    mysystem(mv.c_str(), mv.c_str());
+
+    /* For future LLVM,
+       err = llvm::sys::fs::copy_file(tmpbinname, fullLibraryName);
```
[the remark this answers is not in the document]
Comment (lydia-duncan) [reply compiler/llvm/clangUtil.cpp]: I don't have a strong opinion, I was mostly preserving the comment because it seemed like it might be useful in the future.  I would prefer to enable it in a separate PR, though.

**Comment by lydia-duncan** [comment]
Yup, they're all futures right now

File: compiler/llvm/clangUtil.cpp (hunk 2 above)
Comment (lydia-duncan) [reply compiler/llvm/clangUtil.cpp]: Yeah - I saw that $(AR) was a Makefile variable but wasn't sure how to replicate that outside of a Makefile so hard-coded it for the moment.

File: test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl (hunk 4 above)
Comment (lydia-duncan) [reply test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl]: This goes back to the issue I mentioned in our LLVM deep dive - having the library compilation in precomp files instead of .compopts files on the .chpl file itself means that passing `--llvm` to start_test doesn't impact how the library files are built.  And having the C compilation and execution be part of a prediff on the .chpl file instead seemed like it would tie us to testing one particular C compiler (instead of allowing us to check linking to the library using icc/cce/etc.).  I agree it's not ideal and I think there's some retooling we'll want to do on start_test but that seemed bigger than the scope of the PR

**Comment by lydia-duncan** [comment]
My test directory passed on my Mac after the .bad files got removed.  I'll run full LLVM testing on linux again once the machine is rebooted

File: compiler/llvm/clangUtil.cpp (hunk 2 above)
Comment (lydia-duncan) [reply compiler/llvm/clangUtil.cpp]: I opened #12505 to track that

File: compiler/llvm/clangUtil.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (lydia-duncan) [reply compiler/llvm/clangUtil.cpp]: I opened #12504 to track that

File: test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl (hunk 4 above)
Comment (lydia-duncan) [reply test/interop/C/llvm/exportArray/arrayArg_queriedDomain.chpl]: I opened #12507
