### PR TITLE
Better error for initializing param field with non-param

### LINKED ISSUE #8423: classes with user-written initializers allow param fields with default values that are not params.
### Summary of Problem

```chapel
config var x = 7;

class C {
  param p = x;
  proc init() { }
}

var c = new C();
writeln(c);
delete c;
```

Without the ``writeln(c)``, this compiles.  With it,

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl --force-initializers wrparmem.chpl
In file included from /tmp/chpl-fortytwo-24984.deleteme/_main.c:28:0:
/tmp/chpl-fortytwo-24984.deleteme/ChapelIO.c: In function ‘writeThisFieldsDefaultImpl2’:
/tmp/chpl-fortytwo-24984.deleteme/ChapelIO.c:236:26: error: ‘tmp_chpl’ undeclared (first use in this function)
 writeIt_chpl(_ref_tmp_6, tmp_chpl);
                          ^
/tmp/chpl-fortytwo-24984.deleteme/ChapelIO.c:236:26: note: each undeclared identifier is reported only once for each function it appears in
/home/fortytwo/src/chapel/runtime/etc/Makefile.exe:27: recipe for target '/tmp/chpl-fortytwo-24984.deleteme/wrparmem.tmp' failed
make: *** [/tmp/chpl-fortytwo-24984.deleteme/wrparmem.tmp] Error 1
error: compiling generated source
```

Curiously, with the ``proc init() { }`` removed but with ``--force-initializers``, it reports

```
wrparmem.chpl:6: error: default value for param is not a param
```

which is what I expected to happen as written above.

**Associated Future Test(s):**

[`test/classes/initializers/generics/param-field-default-value-non-param-config-var.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/param-field-default-value-non-param-config-var.chpl)

[edit 2/12 cassella to add path to future]

### Configuration Information

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl --version
chpl version 1.17.0 pre-release (44fa845)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chpl/tfn$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chpl/tfn$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

### LINKED ISSUE #8443: internal error for class with param field whose default value is another, non-param, field.
### Summary of Problem

This is a variation of #8423: a different non-param source of the param field's default value leads to different incorrect behavior.

### Steps to Reproduce

**Source Code:**

```chapel
class C {
  var notaparam = 42;
  param p = notaparam;
  proc init() { }
}

var c = new C();
writeln(c);
delete c;
```

I expected ``default value for param is not a param``.  Instead,

```
$ chpl param-field-default-value-non-param-field.chpl 
internal error: seg fault [misc.cpp:564]
```

As in the other issue, it compiles without the writeln().

**Associated Future Test(s):**
[`test/classes/initializers/generics/param-field-default-value-non-param-field.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/param-field-default-value-non-param-field.chpl
          ) #8453 

[ edit 2/17 cassella to add pointer to future. ]

### Configuration Information

```
fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ chpl --version
chpl version 1.17.0 pre-release (2d81356)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

### PR DESCRIPTION
**Pull request by benharsh**
When initializing a param field, the compiler would insert a param temporary to store the default value for the param field. If the default value could not be evaluated at compile-time, the compiler would silently continue and later fail during code generation. This PR checks that the param temporary actually has an immediate, and if not issues an error.

Resolves #8423
Resolves #8443

Testing:
- [x] local + futures
- [x] gasnet + futures

### CODE REVIEW

**Comment by benharsh** [comment]
@lydia-duncan : willing to review?

File: compiler/resolution/functionResolution.cpp [hunk 1]
```diff
@@ -4926,15 +4926,21 @@ static void resolveInitField(CallExpr* call) {
...
     if (isLegalParamType(srcType) == false) {
       USR_FATAL_CONT(fs, "'%s' is not of a supported param type", fs->name);
     }
-    if (srcExpr->symbol()->isParameter() == false) {
+
+    // Check against the symbol's Immediate is required because the symbol is
+    // likely a temporary, which generally will suppress an error if
+    // initialized from a non-param.
+    else if (srcSym->isParameter() == false ||
+            (isVarSymbol(srcSym) && getImmediate(srcSym) == NULL)) {
```
Comment (lydia-duncan) [inline compiler/resolution/functionResolution.cpp]: This makes me nervous.  It basically means `hasFlag(FLAG_PARAM)` is not a valid check at this point in time, because srcSym->isParameter should dispatch to VarSymbol's isParameter, which checks for either the flag or the presence of an immediate.

I would prefer tracking down where the temporary fails to get checked.  I suspect it is being created with `FLAG_MAYBE_PARAM` instead of `FLAG_PARAM`, when we should know at the time it is being used to create a param variable.

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp]: > I suspect it is being created with FLAG_MAYBE_PARAM instead of FLAG_PARAM, when we should know at the time it is being used to create a param variable.

Sorry, ignore that.  I still think we should track down where the temporary suppresses the error

Comment (benharsh) [reply compiler/resolution/functionResolution.cpp]: I'm not as sure because a lot of parts of the compiler ignore or postpone checking of temporaries because of our early lowering. I think it would be easy to detect when initializing the temporary with a non-param, but generating a useful error message would be more difficult.

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp]: Ah, because it would have lost the name of the original variable at that point?

Comment (benharsh) [reply compiler/resolution/functionResolution.cpp]: Yeah, and then we'd have to examine the surrounding AST to figure out the context.

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp]: Ugh.  Maybe just add a comment that this is kinda gross?

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp]: Thanks!  (also, I think you know this, but in case it wasn't clear, I'm annoyed at the implementation causing these choices, not you for having to make it)
