### PR TITLE
Special case `isCopyableType` to avoid warning

### LINKED ISSUE #20984: isCopyableType with a sync type argument is triggering a sync deprecation warning for unclear reasons
### Summary of Problem
The following code triggers the warning:
```
$CHPL_HOME/modules/standard/Types.chpl:267: warning: Initializing a type-inferred variable from a 'sync' is deprecated; apply a 'read??()' method to the right-hand side
```
This seems wrong to me - we should have replaced uses of this deprecated functionality internally and it seems like the error should only matter for instances of the type rather than for interactions with the type itself.  As a caller, I would not expect `isCopyableType` to need to make an instance and so run into this error.

In looking briefly at the compiler handling, it kinda looks like the `init=` is getting inserted into the code calling `isCopyableType` but I'm not sure why and it seems to happen at a point in resolution after preFolding the primitive away.  My guess was something to do with the argument, but passing `sync string` as a type argument to an ordinary function didn't seem to trigger it.

`isCopyableType` itself is "no doc"ed, but is used in our array implementation and the implementation of our collection types.  I discovered this when making a record with an array of arrays of syncs and not explicitly doing anything with the field in the initializer.  It seems rarer that a user will run into it themselves but if they do, I'm not entirely certain what they would do to squash the warning.

### Steps to Reproduce

**Source Code:**
Direct way to trigger the warning:
```chapel
var x: sync string;
writeln(isCopyableType(x.type));
```

Way I encountered the warning in the wild (generalized):
```chapel
record Foo {
  var x: [0..3][0..3] sync string;
  var otherField: int;

  proc init(val: int) {
    otherField = val;
  }
}

proc main() {
  var f = new Foo(3);
  writeln(f.otherField);
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A

**Associated Future Test(s):**
[`test/library/standard/Types/copyable-sync-string.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/library/standard/Types/copyable-sync-string.chpl) #20986 
[`test/types/sync/lydia/arrayOfArrayOfSyncsInField.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/types/sync/lydia/arrayOfArrayOfSyncsInField.chpl) #20986

### Configuration Information

- Output of `chpl --version`: 1.29.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

### PR DESCRIPTION
**Pull request by jabraham17**
With the `sync`/`single` implicit reads/writes deprecation, the `init=` for the implementing records were marked as deprecated. This causes `isCopyableType` to throw a deprecation warning when it trys to resolve the `init=` while checking if a type is copyable (bug reported in #20984). This behavior should go away when the deprecation is removed, but until then users may get unintended deprecation warnings. This is resolved in the short term by special casing the check to not try to resolve `init=` for `sync`/`single`. In the long term, this special case can be removed when the deprecated `init=` is removed.

## Summary of changes
- add a check for a `sync` or `single` before trying to resolve `init=` in `setRecordCopyableFlags`
- explicitly set `FLAG_TYPE_INIT_EQUAL_FROM_CONST` for `sync`/`single` to maintain deprecated behavior, for now
- removed `FLAG_TYPE_INIT_EQUAL_MISSING` and `FLAG_TYPE_ASSIGN_MISSING`
  - both were only used locally in their respective functions and are not needed for correctness

## Tests
- convert the two futures in #20984 into normal tests

## testing
- paratest
- paratest + gasnet

[Reviewed by @lydia-duncan]
closes #20984

### CODE REVIEW

File: compiler/resolution/preFold.cpp [hunk 1]
```diff
@@ -267,9 +267,15 @@ static void setRecordCopyableFlags(AggregateType* at) {
       }
 
     } else {
-      // Try resolving a test init= to set the flags
-      const char* err = NULL;
-      FnSymbol* initEq = findCopyInitFn(at, err);
+      // TODO Jade:
```
Comment (lydia-duncan) [inline compiler/resolution/preFold.cpp:270]: Let's throw a date on this as well, for extra wincing if we don't get to it right away :)

File: compiler/resolution/preFold.cpp [hunk 2]
```diff
@@ -267,9 +267,15 @@ static void setRecordCopyableFlags(AggregateType* at) {
...
+      // special case since while implicit reads of sync/single are not yet removed
+      // with their removal, the init= that throws a warning will be gone
+      FnSymbol* initEq = NULL;
+      if(!ts->hasFlag(FLAG_SYNC) && !ts->hasFlag(FLAG_SINGLE)) {
+        // Try resolving a test init= to set the flags
+        const char* err = NULL;
+        initEq = findCopyInitFn(at, err);
+      }
       if (initEq == NULL) {
         ts->addFlag(FLAG_TYPE_INIT_EQUAL_MISSING);
```
Comment (lydia-duncan) [inline compiler/resolution/preFold.cpp:280]: We might want to rename this flag (or probably better yet, set a new flag) to better describe what is going on, since we're explicitly ignoring if there's an `init=` for those types

File: test/library/standard/Types/copyable-sync-single-string.chpl [hunk 3]
```diff
@@ -0,0 +1,7 @@
+var x: sync string;
+param p = isCopyableType(x.type);
+compilerWarning("isCopyableType(sync string) = " + p:string);
+var y: sync string;
+param p2 = isCopyableType(y.type);
+compilerWarning("isCopyableType(single string) = " + p2:string);
```
Comment (lydia-duncan) [inline test/library/standard/Types/copyable-sync-single-string.chpl:6]: I don't think these need to be `compilerWarning`s, they could just be writelns now

**Review by lydia-duncan — COMMENTED** [review]
Thanks for taking this on!  I've made a suggestion that will probably make the change more extensive than you were hoping for, but I think will leave the compiler in a better state if we don't get back to it right away.

There's a couple more suggestions, too, but they're pretty minor

File: compiler/resolution/preFold.cpp (hunk 2 above)
Comment (jabraham17) [reply compiler/resolution/preFold.cpp:280]: This flag is unused outside of `setRecordCopyableFlags` so the change is actually pretty minimal. In changing this, I would probably also change `FLAG_TYPE_ASSIGN_MISSING` which is similarly defined and used (and is only used in the analogous `setRecordAssignableFlags`).

I would propose `FLAG_TYPE_HAS_NO_INIT_EQUAL` and `FLAG_TYPE_HAS_NO_ASSIGN`

Comment (jabraham17) [reply compiler/resolution/preFold.cpp:280]: Or alternatively, I think both of these flags can be removed entirely since the functions should work without them and they aren't used elsewhere.

Comment (lydia-duncan) [reply compiler/resolution/preFold.cpp:280]: What about `FLAG_TYPE_SHOULDNT_INIT_EQUAL` or `FLAG_TYPE_DONT_USE_INIT_EQUAL`?

Comment (lydia-duncan) [reply compiler/resolution/preFold.cpp:280]: I'd be okay with removing them entirely

Comment (jabraham17) [reply compiler/resolution/preFold.cpp]: I have removed them and am running paratest now.

Comment (lydia-duncan) [reply compiler/resolution/preFold.cpp]: Be sure to note that in your PR message before merging!

Comment (jabraham17) [reply compiler/resolution/preFold.cpp]: paratest passed with everything removed, so I think this PR should be good to go

**Review by lydia-duncan — APPROVED** [review]
Looks good, thanks!
