### PR TITLE
Fix a bug with re-exporting multiple functions with the same name

### LINKED ISSUE #15605: Problem with re-exporting functions that share a name from two mods
### Summary of Problem
We could re-export multiple functions, and multiple functions with the same name
from the same module, but we currently experience an issue resolving functions when
two re-exported modules both provide overloads of the same function name.

The error given is:
```
multipleDef2Proc.chpl:18: In function 'main':
multipleDef2Proc.chpl:19: error: Symbol 'foo' undeclared in module 'C'
```

### Steps to Reproduce

**Source Code:**

```chapel
module A {
  proc foo(x: int, y: int) {
    writeln("A.foo", x, y);
  }
}
module B {
  proc foo(x: int) {
    writeln("B.foo ", x);
  }
}
module C {
  public import A.foo;
  public import B.foo;
}
module D {
  import C;

  proc main() {
    C.foo(10);
  }
}
```

**Compile command:**
`chpl multiDef2Proc.chpl`

**Associated Future Test(s):**
[`test/visibility/import/edgeCases/multipleDef2Proc.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/edgeCases/multipleDef2Proc.chpl) #15316 

### Configuration Information

- Output of `chpl --version`: 1.23.0 (pre-release)

### PR DESCRIPTION
**Pull request by lydia-duncan**
Prior to this effort, we could re-export multiple functions, and multiple functions
with the same name from the same module, but we experienced an issue
resolving functions when two re-exported modules both provided overloads of
the same function name.

This was because scope resolution was detecting there were multiple options and
decided this meant there was no matching symbol, rather than returning an
arbitrary choice and letting function resolution determine which of the options
was correct.

Resolves #15605 

Details
-------
Stop returning the module where the last symbol was found for re-exported
matches during scope resolution.  Instead, only use the module specified by
the user, so that function resolution has an appropriate starting point to look
for the symbol.  As a result, two of the overloads for ResolveScope's
lookupPublicUnqualAccessSyms method were no longer necessary, so remove
them.  In the remaining function, count the number of matches that were
functions and if all of the matches were functions, return the first one
arbitrarily.

Update visibleFunctions to create a map of names to re-exported functions
with those names (and a bool to indicate if we've already searched for
re-exported functions), but only populate it when we go looking in a particular
scope.  Each map is stored on the relevant VisibleFunctionBlock and cleaned
up when it is cleaned up.

To aid in the function resolution change and to prevent having to add another
instance of the Vec type, added an append overload to the Vec type which
takes in a std::vector instead of another Vec.

Testing changes
-----------------
- Removed the .future and .bad for the motivating test, and fix a typo in its
expected output
- Updated test/visibility/import/edgeCases/noArgFunctionError.chpl's expected
output due to now using the module prefix specified by the user instead of the
module prefix of the scope where the re-exported symbol was defined.
- Added a few tests to lock in re-exported function behavior, including:
  - a basic test of a re-exported function
  - a test over re-exporting two functions with the same name from the same
     scope
  - re-exporting the same name from two modules when one module is further
     down a re-export chain
  - re-exporting the same name from two modules when both modules provide
     multiple overloads
  - re-exporting the same name from two modules when one of the modules
     was only a candidate because the re-export renamed the function.

Passed a full standard paratest with futures, and a valgrind run over
test/visibility

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@e-kayrakli - would you be up for reviewing this?

File: compiler/passes/ResolveScope.cpp [hunk 1]
```diff
@@ -1071,13 +1049,19 @@ Symbol* ResolveScope::lookupPublicUnqualAccessSyms(const char* name,
...
     // potentially start the error process here
     checkConflictingSymbols(symbols, name, context,
                             traversedRenames, renameLocs);
+    if (numFuncs == symbols.size()) {
+      // All options found were functions, but we found them from different
+      // public imports.  That's okay, though, function resolution will handle
+      // determining which one is the best choice.  Arbitrarily return the
+      // first function
+      return symbols[0];
+    }
```
Comment (e-kayrakli) [inline compiler/passes/ResolveScope.cpp:1064]: Minor:  this check should happen before `checkConflictingSymbols`. i.e. if all the symbols are functions `checkConflictingSymbols` doesn't do anything but just iterate over the list of symbols. I don't think it'd have real impact on performance or anything. It would just feel more natural to me.
