### PR TITLE
Fix memory leaks in test-radix-bucketizer.chpl

### LINKED ISSUE #13569: memory leak with coforall reducing an array
The following program leaks memory:

``` chapel
config const n = 100;
  
proc main() {
  var counts:[0..#n] int;
  var nTasks = 10;
  coforall tid in 0..#nTasks with (+ reduce counts) {
    counts[tid] += 1;
  }
}
```

This caused an increase in memory leaks in nightly:

https://chapel-lang.org/perf/chapcs/?startdate=2019/07/14&enddate=2019/07/28&graphs=memoryleaksforalltests

from the test test/library/packages/Sort/correctness/test-radix-bucketizer.chpl which calls SequentialInPlacePartitioning.bucketize which uses this pattern. (These were added in PR #13347).

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #13569, plugging the memory leak in
```
test/library/packages/Sort/correctness/test-radix-bucketizer.chpl
```

When setting up the AST for a task reduce intent, I was using
PRIM_ASSIGN instead of calling the `=` function (which is a really bad
idea when used on an array btw) to store the result of globalOp.generate()
into the outer variable.  Also, the task-private shadow variables were not
getting autoDestroy-ed. This fixes these bugs.

While there, add multi-arg versions of `Expr::insertAfter(Expr*)`, for convenience.
A single varargs version instead would be even nicer.

Testing:
* [x] memleaks -- removes leaks in the bucketizer test, does not affect other tests
* [x] valgrind
* [x] linux64 -futures
  - modulo distributions/ferguson/dist-assoc-bulkadd.bad mismatch, to be handled post-merge

### CODE REVIEW

File: compiler/passes/createTaskFunctions.cpp [hunk 1]
```diff
@@ -370,16 +370,21 @@ static void addReduceIntentSupport(FnSymbol* fn, CallExpr* call,
   Expr* tailAnchor = findTailInsertionPoint(call, isCoforall);
   // Doing insertAfter() calls in reverse order.
   // Can't insertBefore() on tailAnchor->next - that can be NULL.
-  tailAnchor->insertAfter("chpl__delete(%S)",
-                         globalOp);
-  tailAnchor->insertAfter("'='(%S, generate(%S,%S))",
```
Comment (mppf) [inline compiler/passes/createTaskFunctions.cpp]: FYI, I think this is a case where the call-expr-string stuff actually made the bug harder to see. I definitely prefer the `new CallExpr` style, even though it can be more verbose.

Arguably the multi-arg version of insertAfter would be better to simply insert many things in order than to do this format string thing (My next comment has an example). I think the format string thing should have a different method name.

File: compiler/passes/createTaskFunctions.cpp [hunk 2]
```diff
@@ -370,16 +370,21 @@ static void addReduceIntentSupport(FnSymbol* fn, CallExpr* call,
...
-                         origSym, gMethodToken, globalOp);
+  // origSym = <- globalOp.generate() (via genTemp); delete globalOp;
+  VarSymbol* genTemp = newTemp("genTemp");
+  genTemp->addFlag(FLAG_INSERT_AUTO_DESTROY);
+  tailAnchor->insertAfter(new CallExpr("chpl__delete", globalOp));
+  tailAnchor->insertAfter(new CallExpr("=", origSym, genTemp));
+  tailAnchor->insertAfter("'move'(%S,generate(%S,%S))",
+                          genTemp, gMethodToken, globalOp);
+  tailAnchor->insertAfter(new DefExpr(genTemp));
```
Comment (mppf) [inline compiler/passes/createTaskFunctions.cpp]: Inserting things in reverse order is in my opinion unnecessarily confusing.
Here is how I would write this:
``` c++
  CallExpr* del = new CallExpr("chpl__delete", globalOp);
  tailAnchor->insertAfter(del);
  del->insertBefore(new DefExpr(genTemp));
  del->insertBefore(new CallExpr(PRIM_MOVE, genTemp, new CallExpr("generate", gMethodToken, globalOp));
  del->insertBefore(new CallExpr("=", origSym, genTemp));
```

but using a block or a PRIM_NOOP would also be reasonable alternatives.

If you took my multi-arg insertAfter suggestion, it would look like this
``` c++
  tailAnchor->insertAfter( 
    new DefExpr(genTemp),
    new CallExpr(PRIM_MOVE, genTemp, new CallExpr("generate", gMethodToken, globalOp)),
    new CallExpr("=", origSym, genTemp)),
    new CallExpr("chpl__delete", globalOp));
```

**Comment by bradcray** [comment]
@vasslitvinov / @mppf: Could one of you add the simpler version of the code that demonstrated the issue in #13569 as a test (assuming it hasn't been elsewhere and I missed it) so that we have a smaller code to look at if something goes wrong here in the future?  (Maybe printing out counts at the end so that it's less of a no-op?)

**Comment by vasslitvinov** [comment]
Done, `test/parallel/taskPar/taskIntents/ri-array.chpl`

**Comment by bradcray** [comment]
Thanks!
