### PR TITLE
Fix environment variable passing for remaining Perl-implemented launchers

### LINKED ISSUE #11536: Fix environment variable passing for Perl-implemented launchers
#11355 was a user issue with the slurm-gasnetrun_ibv launcher, fixed by #11532 .  In fixing the user issue, it was noticed that other launchers have similar problems.

Examine all the gasnetrun_ibv, gasnetrun_mpi, and gasnetrun_ofi launchers and apply the following fixes as necessary.

1.  Some launchers do not pass the full environment to the compute nodes.
2.  These launchers are written in Perl, with a preamble that mangles the character-set-locale (via LC_ALL et al.).  When these environment variables are passed to the compute nodes, the mangled version is passed.  The workaround from #11532 should be applied.

### PR DESCRIPTION
**Pull request by dmk42**
GASNet launchers written in Perl reset the character-set environment to prevent Perl from performing UTF-8-related modifications on binary byte strings.  Consequently, these launchers need special handling to preserve the character-set environment variables.

#11532 brought the Slurm gasnetrun_ibv launcher up to date with these requirements.  This change does the same for the remaining Perl-based launchers.

Closes #11536

### CODE REVIEW

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h [hunk 1]
```diff
@@ -36,11 +36,12 @@ static char _nlbuf[16];
 static char** chpl_launch_create_argv(const char *launch_cmd,
                                       int argc, char* argv[],
                                       int32_t numLocales) {
-  const int largc = 7;
-  char *largv[largc];
+  const int maxlargc = 7 + 4;
```
Comment (ronawho) [inline runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: Little weird to not just have 11. Or maybe make these names variables and use them to update largc?

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h [hunk 2]
```diff
@@ -49,6 +50,46 @@ static char** chpl_launch_create_argv(const char *launch_cmd,
...
+    strcat(lc_all_buf, lc_all);
+    largv[9] = lc_all_buf;
+    if (lc_collate == NULL)
+      lc_collate = "";
+    char *lc_collate_buf = chpl_mem_allocMany(
+                        sizeof("LC_COLLATE=") + strlen(lc_collate),
+                        sizeof(char), CHPL_RT_MD_COMMAND_BUFFER, -1, 0);
+    strcpy(lc_collate_buf, "LC_COLLATE=");
+    strcat(lc_collate_buf, lc_collate);
+    largv[10] = lc_collate_buf;
```
Comment (ronawho) [inline runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: This is an awful lot of code just to copy a few env var values. Can we fold this into chpl_get_enviro_keys()? If not, can we make some common routine to simplify this and prevent code duplication across launchers

File: runtime/src/launch/mpirun/launch-mpirun.c [hunk 3]
```diff
@@ -52,10 +52,53 @@ static char** chpl_launch_create_argv(const char *launch_cmd,
...
   largv[1] = (char *) "-np";
   sprintf(_nlbuf, "%d", numranks);
   largv[2] = _nlbuf;
+  largv[3] = (char*) "-E";
+  largv[4] = chpl_get_enviro_keys(',');
+
+  // If any of the relevant character set environment variables
+  // are set, replicate the state of all of them.  This needs to
+  // be done separately from the -E mechanism because the
+  // launcher is written in Perl, which mangles the character
```
Comment (ronawho) [inline runtime/src/launch/mpirun/launch-mpirun.c]: This calls `mpirun`, not a gasnet wrapper. How sure are you that mpirun may be written in perl?

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h (hunk 1 above)
Comment (dmk42) [reply runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: 11 is fine.  I'll do that.

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h (hunk 2 above)
Comment (dmk42) [reply runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: OK, it looks like chpl_get_enviro_keys is only used by the Perl-based launchers.  I had been assuming it was used more widely.  Since it's specific to those launchers, I will fold the code into that routine.

File: runtime/src/launch/mpirun/launch-mpirun.c (hunk 3 above)
Comment (dmk42) [reply runtime/src/launch/mpirun/launch-mpirun.c]: `third-party/gasnet/gasnet-src/other/mpirun_common.in` seems to imply that mpirun is a wrapper for the Perl-based gasnet_mpi.

**Comment by ronawho** [comment]
> It's pretty easy to test gasnetrun_{ibv, mpi, ofi} (and #11537 exists to add nightly testing), but how do we test this patch?

Oh, I missed in your email that were asking how to test these configs. 

---
We do not have any way to test pbs-gasnetrun_ibv

There is nightly testing for mpirun launcher (util/cron/test-mpicc.bash), so you can take a look at that for how to repro. Should be something like: 

```sh
util/cron/common-mpicc.bash
export CHPL_LAUNCHER=mpirun
# run your test
```

We do not have nightly testing for gasnetrun_{ibv, mpi, ofi} yet, but manually is pretty easy: 

On chapcs:
```sh
# ibv
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=ibv
export GASNET_PHYSMEM_MAX=16G
export GASNET_PHYSMEM_NOPROBE=1

#mpi 
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=mpi

#ofi  
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=ofi
```

```sh
salloc --nodes=2 --share
# run your test (do this for each config)
```

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h (hunk 2 above)
Comment (dmk42) [reply runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: It turns out it isn't going to be possible to put it in chpl_get_enviro_keys, because multiple arguments need to be returned.  There do need to be two versions of the code, one for the one-arg-per-array-element type of launching, and one for generating a command-line string.

File: runtime/src/launch/mpirun/launch-mpirun.c (hunk 3 above)
Comment (ronawho) [reply runtime/src/launch/mpirun/launch-mpirun.c]: I'm not following. We're _not_ calling a gasnet wrapper. We're literally calling the system `mpirun`

gasnetrun_* launchers that use mpi-spawning may end up calling gasnetrun_mpi, but that's not related to this. Under the covers gasnetrun_mpi will call the system `mpirun`, but again not related to this.

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h (hunk 2 above)
Comment (ronawho) [reply runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: I'm fine if there's 2 functions, so long as we can avoid the code dupe between launchers

File: runtime/src/launch/mpirun/launch-mpirun.c (hunk 3 above)
Comment (dmk42) [reply runtime/src/launch/mpirun/launch-mpirun.c]: OK, in that case, I can remove that file from my changes.

File: runtime/src/launch/gasnetrun_common/gasnetrun_common.h (hunk 1 above)
Comment (dmk42) [reply runtime/src/launch/gasnetrun_common/gasnetrun_common.h]: I ended up going with the named quantity instead, to make it easier to move the code into a central place.

**Comment by dmk42** [comment]
Thanks for the testing info.  Now that I have added a new test, checking `test/types/string/dmk/utf8_env.chpl` will tell us what we want to know.

**Comment by gbtitus** [comment]
I looked this over and didn't spot anything not already mentioned.
