### PR TITLE
Fix error with certain `include module` patterns

### LINKED ISSUE #25569: [Bug]: strange error with include module
### Summary of Problem

**Description:**
I'm seeing errors when using submodules in a different file. The error goes away if I paste the submodule declaration in the place of the `include module`.

**Is this issue currently blocking your progress?**
No

### Steps to Reproduce

**Source Code:**

```chapel
// M.chpl
module M {
  config param EXTRA_CHECKS = false;

  include public module SubModule;

  use this.SubModule;
  foo();
}
```

```chapel
// M/SubModule.chpl
module SubModule {
  import super.EXTRA_CHECKS;

  proc foo() { }
}
```

**Compile command:**
```
chpl M.chpl  -o test
```

```
M/SubModule.chpl:1: In module 'SubModule':
M/SubModule.chpl:2: error: invalid use of 'super' in 'import'; 'SubModule' is a top-level module
M/SubModule.chpl:1: note: module 'SubModule' was declared at the top level here
```

**Associated Future Test(s):**
TODO

### PR DESCRIPTION
**Pull request by mppf**
Resolves #25569

This PR fixes a problem with using `import super.something` from within a submodule that was stored in a different file using `include module`.

Reviewed by @DanilaFe - thanks!

- [x] full comm=none testing

### CODE REVIEW

File: frontend/lib/parsing/parsing-queries.cpp [hunk 1]
```diff
@@ -1425,11 +1429,26 @@ const ID& idToParentId(Context* context, ID id) {
...
+    parseFileContainingIdToBuilderResult(context, id, &parentSymbolPath);
+
   if (r != nullptr) {
     result = r->idToParentId(id);
+    // For a submodule in a separate file, the BuilderResult's idToParentId
+    // will return an empty ID for the submodule.
+    // Detect that and return the parent module in that case.
+    if (result.isEmpty() && !parentSymbolPath.isEmpty()) {
+      ID parentSymbolId = id.parentSymbolId(context);
+      if (!parentSymbolId.isEmpty()) {
```
Comment (DanilaFe) [inline frontend/lib/parsing/parsing-queries.cpp:1447]: Shouldn't `parentSymbold` always be non-empty here, since we know that the current module is nested within another (`!parentSymbolPath.isEmpty()` ?) Is there a situation in which `parentSymbolPath` is non-empty but `parentSymbolId` returns an empty ID?

**Review by DanilaFe — APPROVED** [review]

File: frontend/lib/parsing/parsing-queries.cpp (hunk 1 above)
Comment (mppf) [reply frontend/lib/parsing/parsing-queries.cpp:1447]: It should not. I can change this into a `CHPL_ASSERT`.

Comment (DanilaFe) [reply frontend/lib/parsing/parsing-queries.cpp:1447]: I think that would be more robust.
