### PR TITLE
Alignment improvements in LLVM codegen

### LINKED ISSUE #24602: CUDA 12: Misaligned address issues with types which aren't 64 bits
### Summary of Problem

When using CUDA 12 in the following pattern we get the error:
```
internal error: gpu-nvidia.c:292: Error calling CUDA function: misaligned address (Code: 716)
```

Workaround:
Change `proc foo(..)` to be `inline proc foo(...)`

### Steps to Reproduce

**Source Code:**

```chapel
on here.gpus[0] {
  var a: [1..10] uint(32);
  @assertOnGpu
  foreach chunk in 0..1 {
    foo(a);
  }
}

 proc foo(ref arr : [] uint(32)) {
  var sum : uint(32);
  var temp : uint(32) = arr[1];
  arr[1] = sum;
  sum += temp;
}
```

Output from compiling and running:
```
me@pinoa:~/chapel> chpl test/gpu/native/studies/sort/repro.chpl && ./repro
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
internal error: gpu-nvidia.c:292: Error calling CUDA function: misaligned address (Code: 716)
```

**Associated Future Test(s):**
`test/gpu/native/studies/sort/cuda12_misaligned.chpl`

### Configuration Information
<details> <summary> Show </summary>
- Output of `chpl --version`:

```
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
chpl version 2.0.0 pre-release (719155d0d3)
  built with LLVM version 17.0.6
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: nvidia *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

```
gcc (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- (For Cray systems only) Output of `module list`:

```
Currently Loaded Modules:
  1) craype-x86-rome                         8) cray-dsmml/0.3.0
  2) libfabric/1.15.2.0                      9) cray-mpich/8.1.29
  3) craype-network-ofi                     10) cray-libsci/24.03.0
  4) perftools-base/24.03.0                 11) PrgEnv-gnu/8.5.0
  5) xpmem/2.6.2-2.5_2.27__gd067c3f.shasta  12) cray-pmi/6.1.14
  6) gcc-native/13.2                        13) cudatoolkit/23.3_12.0
  7) craype/2.7.31                          14) cray-python/3.11.7
```

</details>

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #24602. Fixes LLVM codegen's handling of Chapel records with a mix of `extern`- and non-extern-typed fields, such as the wide-pointer type that is a record combining the extern `chpl_localeID_t` and a narrow pointer. Removes the no-longer-occurring error "unhandled misaligned record member".

Removes the workarounds added in #24585 and #24600. The tests `gpu/native/studies/shoc/shoc-sort` and `gpu/native/studies/sort/scanTest` would fail without this PR if these workarounds were removed.

Calculates and stores the alignment for AggregateTypes for classes. It is now an error if the desired alignment for the struct implementing a Chapel class is >16 because our heap allocators may not be able to provide alignment>16 when allocating class instances.

Clarifies / tidies up LLVM codegen's handling of LLVM types and alignments for Chapel types. Sets up for supporting user-specified alignment on Chapel types, fields, and variables.

I plan to hide `checkStructFields()` behind `if (fVerify)` for the release, after a few nights of testing that we do across various platforms. This is to reduce the chance of a false alarm for users out in the field.

### Test updates

De-futurizes the reproducer for the original misalignment error in #24602:
`test/gpu/native/studies/sort/cuda12_misaligned.chpl`

Removes the test for the "unhandled misaligned" error in favor of a beefed-up sister test:
`test/llvm/alignment/check-align-padding-error.chpl`
`test/llvm/alignment/check-align-padding.chpl`

Adds the execution output to .good by extending .prediff:
`test/llvm/alignment/check-align16.chpl`
`test/llvm/alignment/check-align16-field1.chpl`

Locks the error message for alignment>16 for Chapel classes:
`test/llvm/alignment/check-align-class-32.chpl`

Adds a .future tests for a compiler crash and another one for a better error message, see #25191:
`test/extern/records/OpaqueStructUseError.chpl`
`test/extern/vass/missing-extern-type-1.chpl`

### Implementation notes

Each `TypeSymbol` now stores its corresponding `LLVM::Type` as well as the required alignment. Read on for details.

`TypeSymbol::getLLVMType()` and `getLLVMStructureType()` now invoke `TypeSymbol::codegenDef()` if its LLVM type has not been computed yet. `TypeSymbol::hasLLVMType()` checks the latter. `type->codegen().type` should now be replaced with`type->symbol->getLLVMType()` to avoid unnecessary overhead.

`TypeSymbol::getLLVMAlignment()` and `getLLVMStructureAlignment()` do not perform the check `hasLLVMType` to avoid executing a branch. It is developer responsibility to ensure that `hasLLVMType` is true when querying the alignment.

`TypeSymbol::getLLVMAlignment()` and `getLLVMStructureAlignment()` return `ALIGNMENT_DEFER`, meaning "defer the alignment to LLVM," in those cases where computing the alignment can be delegated to LLVM. One example is (narrow) pointer types. Another example is a struct for which the alignment calculated by our codegen is the same or weaker than the alignment calculated by LLVM, see `llvmAlignmentOrDefer()`. The alignment is not DEFER, for example, when the alignment is, or depends on something that is, determined by an annotation in the program rather than by the ABI or hardware rules. To "undo" the DEFER, use `TypeSymbol::getABIAlignment()`.

The alignments considered above are "ABI" alignments, not "preferred" alignments, in LLVM terminology. The "preferred" alignment is the same or stricter/bigger than the "ABI" alignment and could potentially improve performance.

I follow the lead of Clang, see below, by inserting explicit padding into LLVM's struct corresponding to a Chapel record or class -- when otherwise LLVM would not align the fields as desired. This is done in `buildStructFields()`.

I set the alignment of `alloca` instructions and `GlobalVariable` declarations in `setValueAlignment()`. One of the overloads takes AST's `Type` and `Symbol` formals. Currently it uses only the Type formal to look up its required alignment. The `Symbol` formal is there to support user-requested field and variable alignments in the future, which I envision being stored in a field in `Symbol` or `VarSymbol`.

Minor: classes without user-declared fields no longer have a dummy int32 field added because they already have the `chpl__cid` field.

Detailed dev history: 57c5b877a2..52c0f7b977 and e18ec32d85..028a571b9e

### Design considerations

I considered having each `Type` / `TypeSymbol` calculate its LLVM type proactively -- to obviate the calls to `ensureCodegenned()` and `hasLLVMType()`. However, there are mutliple locations in the code where this would be necessary, which would make this approach fragile w.r.t. code evolution. The final blow came from `getOrMakeWideTypeDuringCodegen()` where implementing this approach is particularly tricky / ugly because it can be invoked when `gGenInfo` is not set up yet.

I chose to store the alignment as an `int` because (a) it was comfortable for me and (b) it allowed me to have the value `ALIGNMENT_UNINIT` that I use for assertions "this alignment has/has not been computed already."

Here are my trade-offs w.r.t. other alternatives:

* `uint` or `uint64_t` : I disliked the slightly increased verbosity compared to plain `int` -- more so than appreciated the benefit of ensuring positive alignment and supporting bigger alignments.

* `llvm::Align` : on the upside, it fits in a byte, supports alignments up to 2**64, and ensures that the alignment is a power of 2. Downsides: interacting with integer alignments is more involved and I was not used to it. Also, it would not support ALIGNMENT_UNINIT.

* `llvm::MaybeAlign` : this may be a good alternative, however it makes interacting with integer alignments even more involved.

I am not sure whether ALIGNMENT_DEFER is a good idea. We can always switch away from it. At least it allows us to avoid querying LLVM explicitly for pointers and primitive types. Such queries involve more lookups than I expected, for example they need the "address space" for pointers.

There is no way to associate our own alignment with an `LLVM::Type`. Therefore we need to store and propagate it ourselves for AST Types.

Storing the LLVM type for each AST type seems faster than looking it up every time in the LayeredValueTable, which was done before for primitive and extern types. Storing the alignment (or ALIGNMENT_DEFER) universally for each AST type seems faster than figuring it out or recomputing it for struct types, which was done before upon each query.

### What I learned about LLVM, clang, alignment, and LLVM struct layout.

LLVM's alloca, load, and store instructions always store the desired alignment. When the alignment is not provided when such an instruction is constructed, LLVM fills it in based on its knowledge about the type of the data.

If the alignment associated with an `alloca` is stricter/bigger than the alignment specified when loading from or storing into this location, it is OK correctness-wise. Such loads/stores might be slower in some cases than ones using a matching alignment.

If, conversely, the specified alignment of a load or store is stricter/bigger than that of the memory location, the generated binary can crash during execution. We have witnessed this on NVIDIA for stack-allocated variables. I have seen this also on an Intel CPU upon a `movaps` instruction.

LLVM does not correlate the alignments of `alloca` vs. loads and stores. Our codegen needs to do that.

The "ABI" alignment is a requirement of the underlying platform / architecture. The "preferred" alignment, in LLVM terminology, may be stricter/bigger, potentially leading to better performance due to faster load / store instructions.

Clang implements the `aligned` attribute for users to specify the alignment of fields in a struct. See, for example, `test/llvm/alignment/check-align16.chpl`. Since LLVM does not provide a way to represent such an alignment in a type, Clang inserts explicit padding -- only when LLVM would not lay out / align the fields as desired. If so, Clang may insert padding after the last field as well, which ensures desired alignment of adjacent array elements for example.

For example, given these C structs:

```C
struct s1 {
  char c;
  uint64_t u;
}
struct s2 {
  uint64_t x;
  uint64_t a __attribute__((aligned (16)));
};
```

Clang produces these LLVM types:

```
%struct.s1 = type { i8, i64 }                        ; hasPadding() = true
%struct.s2 = type { i64, [8 x i8], i64, [8 x i8] }   ; hasPadding() = false
```

LLVM computes the layout and alignment of a struct type on demand, e.g., upon a call to `getStructLayout()`. The computation is in `StructLayout::StructLayout()` in llvm-src/lib/IR/DataLayout.cpp. It is straightforward and queries DataLayout::getABITypeAlign(the type of each field) and DataLayout::getTypeAllocSize(the type of each field).

LLVM does not insert explicit padding into its struct types. This is understandable, because otherwise it would break GEP (GetElementPtr) calculations. Instead, LLVM provides `StructLayout::hasPadding()`, which indicates whether such padding is needed / will be inserted in the generated binary.

### Future work

User-facing: enable users to request alignment of Chapel types, fields, variables. See `setValueAlignment` above.

Pack the fields of Chapel classes and records so that, for example, `(bool, int, bool)` takes 16 bytes instead of 24.

Replace the remaining occurrences of `type->codegen().type` with `type->symbol->getLLVMType()`. Drop `->symbol` in `->symbol->getLLVMType()`.

Find occurrences where using the "preferred" alignment can improve performance.

Convince ourselves that the alignments coming out from Clang or LLVM will always fit in an `int`. Otherwise fix the type of TypeSymbol::llvmAlignment and remove the casts to `(int)` of the results of `.value()` calls on LLVM:Align things. Alternatively, switch from storing the alignment as an int to storing it as an llvm::MaybeAlign, where "absent" means "uninitialized" and the alignment of 1 means "deferred," as it does in this PR.

Tweak: co-locate `TypeSymbol::getLLVMType` and `TypeSymbol::getLLVMAlignment` with `Type::GEPMap` since they all support LLVM codegen. I.e., put either all under TypeSymbol or all under Type.

### CODE REVIEW

**Comment by vasslitvinov** [comment]
As of this writing / 4774bd48ed, there are cases where our codegen emits an `alloca` without setting its alignment according to some AST Type/Symbol. This is because AST Types/Symbols are nowhere in sight in those cases. I am looking for help here, to ensure that the outcomes of such an `alloca` cannot be assumed to have stricter/bigger alignment elsewhere in the code. This could happen, for example, if such an `alloca` is passed to code assumes it to allocate a particular AST Type, unless it is a primitive or pointer type.

* `createStoreLoadCast()` in compiler/llvm/llvmGlobalToWide.cpp where it calls `makeAlloca()` with 3 args.

* Other calls to `makeAlloca()` with 3 args in llvmGlobalToWide.cpp. 

* The call to `createAllocaInFunctionEntry()` in `convertValueToType()` and, transitively, `extendToPointerSize()` with 2 args.

* The call to `makeAlloca()` with 8 args in llvmAggregateGlobalOps.cpp. Here the alignment comes from `Ranges` where, in turn, it comes from some existing instruction's `getAlign()`. I am unclear whether this existing instruction's alignment is indeed appropriate for the newly-created alloca.

File: compiler/codegen/cg-type.cpp [hunk 1]
```diff
@@ -187,6 +205,217 @@ void EnumType::codegenDef() {
...
+
+    llvm::Type *largestType = NULL;
+    uint64_t largestSize = 0;
+
+    for_fields(field, ag) {
+      llvm::Type* fieldType = field->type->symbol->getLLVMType();
+      INT_ASSERT(fieldType);
+      uint64_t fieldSize = DL.getTypeStoreSize(fieldType);
+
+      if(fieldSize > largestSize) {
```
Comment (jabraham17) [inline compiler/codegen/cg-type.cpp:286]: nit, spacing between `if` and `(`

File: compiler/codegen/cg-type.cpp [hunk 2]
```diff
@@ -187,6 +205,217 @@ void EnumType::codegenDef() {
...
+      GEPMap.insert(std::pair<std::string, int>(field->cname, paramID));
+      GEPMap.insert(std::pair<std::string, int>(
+            std::string("_u.") + field->cname, paramID));
+
+      // TODO account for field's alignment in case it is >8
+    }
+
+    llvm::StructType * st;
+    // handle an empty union.
+    if( largestType ) {
```
Comment (jabraham17) [inline compiler/codegen/cg-type.cpp:300]: nit, spacing on condition

File: compiler/codegen/cg-type.cpp [hunk 3]
```diff
@@ -187,6 +205,217 @@ void EnumType::codegenDef() {
...
+  // to reduce codegen time and to reduce the chance of a false alarm
+  // on an architecture that we have not tested.
+  if (structSize == 0) {
+    INT_ASSERT(aligns.size() == 0);                   // we did not populate it
+    INT_ASSERT(isDeferredAlignment(structAlignment)); // delegated to LLVM
+  } else {
+    INT_ASSERT(params.size() == aligns.size());  // we populated them together
+    const llvm::StructLayout* layout = DL.getStructLayout(stype);
+    // These are other ways to query the struct size - any of them useful?
+    //  DL.getTypeAllocSize(stype) and layout->getSizeInBytes()
```
Comment (jabraham17) [inline compiler/codegen/cg-type.cpp:408]: should this go behind `fVerify`? And maybe instead of asserts everywhere, user facing error messages?

File: compiler/codegen/cg-type.cpp [hunk 4]
```diff
@@ -187,6 +205,217 @@ void EnumType::codegenDef() {
...
+      // add dummyFieldToAvoidWarning which also
+      // stops us from doing 0-byte memory allocation
+      // (comes up with ioNewline and --no-local RA)
+      // TODO - don't ever allocate 0-byte structures
+      // example: DefaultComparator
+      if (explicitPadding)
+        addFieldWhenEP("_dummyFieldToAvoidWarning", padTy, 1, 1);
+      else
+        addFieldWhenNotEP("_dummyFieldToAvoidWarning",
+          llvm::Type::getInt8Ty(gContext->llvmContext())); // here padTy==0
```
Comment (jabraham17) [inline compiler/codegen/cg-type.cpp:376]: The old code used a dummy value of i32, this is i8. Why the change?

File: compiler/codegen/cg-symbol.cpp [hunk 5]
```diff
@@ -1860,13 +1946,11 @@ GenRet TypeSymbol::codegen() {
     }
   } else {
 #ifdef HAVE_LLVM
-    if( ! getLLVMType() ) {
       // If we don't have an LLVM type yet, the type hasn't been
       // code generated, so code generate it now. This can get called
       // when adding types partway through code generation.
-      codegenDef();
+    ensureCodegenned(this);
```
Comment (jabraham17) [inline compiler/codegen/cg-symbol.cpp:1952]: nit,  formatting

File: compiler/codegen/cg-expr.cpp [hunk 6]
```diff
@@ -6116,7 +6139,13 @@ DEFINE_PRIM(DYNAMIC_CAST) {
...
     AggregateType* at = toAggregateType(call->get(1)->typeInfo());
     const char* struct_name = at->classStructName(true);
-    GenRet tmp = createTempVar(struct_name);
+    GenRet tmp = createTempVar(struct_name,
+#ifdef HAVE_LLVM
+      gGenInfo->cfile ? 0 : at->symbol->getLLVMStructureAlignment()
+#else
+      0  // ignored for C codegen
+#endif
+    );
```
Comment (jabraham17) [inline compiler/codegen/cg-expr.cpp:6148]: Can you make this code more readable? Maybe a temporary instead of doing it in-place like this?

File: compiler/codegen/cg-expr.cpp [hunk 7]
```diff
@@ -2471,7 +2505,8 @@ GenRet codegenTernary(GenRet cond, GenRet ifTrue, GenRet ifFalse)
     char name[32];
     snprintf(name, sizeof(name), "chpl_macro_tmp_tv_%d", codegen_tmp++);
 
-    llvm::Value* tmp = createVarLLVM(values.a->getType(), name);
+    llvm::Value* tmp = createVarLLVM(values.a->getType(), ret.chplType,
+                                     (Symbol*)nullptr, name);
```
Comment (jabraham17) [inline compiler/codegen/cg-expr.cpp:2509]: is the cast really needed?

File: compiler/codegen/cg-expr.cpp [hunk 8]
```diff
@@ -1547,15 +1587,9 @@ GenRet createTempVar(Type* t)
...
-    INT_ASSERT(llTy);
-
-    llvm::AllocaInst* alloca = createVarLLVM(llTy);
-    llvm::MaybeAlign alignment = getAlignment(t);
-    if (alignment) {
-      alloca->setAlignment(*alignment);
-    }
+    // getLLVMType() code-generates the type, if needed.
+    llvm::Type* llTy = t->symbol->getLLVMType();
+    llvm::AllocaInst* alloca = createVarLLVM(llTy, t, (Symbol*)nullptr);
```
Comment (jabraham17) [inline compiler/codegen/cg-expr.cpp:1592]: Same here, why is the cast needed?

File: compiler/codegen/cg-expr.cpp [hunk 9]
```diff
@@ -267,22 +267,35 @@ GenRet DefExpr::codegen() {
...
-  return createVarLLVM(type, name);
+  return createVarLLVM(type, astType, astSymbol, name);
+}
+
+// 'alignment' is expected to follow 'AlignmentStatus'
+llvm::AllocaInst* createVarLLVM(llvm::Type* type, const char* name,
+                                int alignment)
+{
+  llvm::AllocaInst* result = createVarLLVM(type, (Type*)nullptr,
+                                           (Symbol*)nullptr, name);
```
Comment (jabraham17) [inline compiler/codegen/cg-expr.cpp:296]: Why the casting?

**Review by jabraham17 — COMMENTED** [review]
This looks good to me for post-release, assuming the CI failures are resolved

File: compiler/codegen/cg-type.cpp (hunk 2 above)
Comment (vasslitvinov) [reply compiler/codegen/cg-type.cpp:300]: Both the above conditionals are part of code that was moved from elsewhere in this file. I propose to retain the original spacing, although it is a weak preference.

Comment (jabraham17) [reply compiler/codegen/cg-type.cpp:300]: I think if you are touching the code anyways, you might as well leave it in a better state

File: compiler/codegen/cg-type.cpp (hunk 3 above)
Comment (vasslitvinov) [reply compiler/codegen/cg-type.cpp:408]: These are really asserts, meaning that a violation would mean a bug on my end, not user's.

I am not excited about hiding them behind fVerify because it means the checks will be skipped in the majority of testing. I am open to removing these checks altogether after a couple of weeks of testing, if this addresses your concerns.

File: compiler/codegen/cg-type.cpp (hunk 4 above)
Comment (vasslitvinov) [reply compiler/codegen/cg-type.cpp:376]: No real good reason other than saving space, at least "on paper". If you feel strongly I can revert to i32.

File: compiler/codegen/cg-expr.cpp (hunk 8 above)
Comment (vasslitvinov) [reply compiler/codegen/cg-expr.cpp:1592]: In the two cases above, I added the casts to nudge the reader towards understanding that the null goes to the "symbol" vs. the "type" formal argument. If this is problematic, I can remove the casts, as they are not needed for correct operation of the code.

File: compiler/codegen/cg-expr.cpp (hunk 9 above)
Comment (vasslitvinov) [reply compiler/codegen/cg-expr.cpp:296]: Same as above.

File: compiler/codegen/cg-type.cpp (hunk 3 above)
Comment (jabraham17) [reply compiler/codegen/cg-type.cpp:408]: No I think keep them, whether or not they need to go behind `fVerify` probably depends on if they cause a major perf regression

File: compiler/codegen/cg-type.cpp (hunk 4 above)
Comment (jabraham17) [reply compiler/codegen/cg-type.cpp:376]: I would revert to i32 to avoid possible unintended side effects

**Comment by vasslitvinov** [comment]
TODO: the following fails the assert in TypeSymbol::getLLVMStructureAlignment()  under `CHPL_LLVM=system` and `CHPL_TARGET_COMPILER=gnu`. Note: this method should not be invoked at all in this configuration.
```chpl
use CTypes;

record R {
  var arr: c_array(c_int, 10);
}

extern proc foo1(const in a: c_array(c_int));
extern proc foo2(const ref a: c_array(c_int));

proc main() {
  var arr: c_array(c_int, 99);
  foo1(arr);
  foo2(arr);
}
```

**Comment by e-kayrakli** [comment]
Not something to distract from progress here, but I wonder if `test/gpu/native/distArray/blockUseInFunction.future` (https://github.com/chapel-lang/chapel/issues/24429) is resolved after this PR.

**Comment by e-kayrakli** [comment]
I am also inclined to think that this will resolve https://github.com/chapel-lang/chapel/pull/24787. I don't think we need to test it (I don't remember how to test it with Arkouda, Shreyas might, but does not worth the effort of remembering). So, I suggest you just add a "Resolves" statement in the OP to make sure that it is closed once this goes in.

File: compiler/codegen/cg-symbol.cpp [hunk 10]
```diff
@@ -1474,6 +1467,26 @@ void TypeSymbol::codegenDef() {
   if (!hasFlag(FLAG_EXTERN)) {
     type->codegenDef();
   }
+  else if( info->cfile ) {
```
Comment (vasslitvinov) [inline compiler/codegen/cg-symbol.cpp:1470]: Another space nit.

**Review by jabraham17 — APPROVED** [review]
Looks great!

**Comment by e-kayrakli** [comment]
Phew! Thanks @vasslitvinov!
