### PR TITLE
Type methods to accept any memory management / nilability

### LINKED ISSUE #12095: Problem calling static method on type of field when not borrowed
### Summary of Problem
When I get the type of a field and try to call a static method on that type, I encounter issues depending on the lifetime of the field.  The call will resolve if the field is borrowed, but will not if the field is unmanaged, owned, or shared.

### Steps to Reproduce

**Source Code:**

```chapel
class Parent {
  proc type foo() param {
    return 3;
  }
}

class Child: Parent {
}

record Wrapper {
  var x;
}

var p = new shared Parent(); // works if borrowed or unspecified, otherwise fails to resolve the call
var c = new shared Child(); // works if borrowed or unspecified, otherwise fails to resolve the call
var w1 = new Wrapper(p);
var w2 = new Wrapper(c);

writeln(w1.x.type: string);
writeln(w2.x.type: string);
writeln(w1.x.type.foo());
writeln(w2.x.type.foo());
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
test/classes/lydia/staticMethodInheritance-whenField-*.chpl #12096

### Configuration Information

- Output of `chpl --version`: 1.19.0 (pre-release)

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #12095.
Next steps: #13109, #13152, #13153, #13155.

A type method declared in one of the following ways:

```chpl
class MyClass {
  proc type myTypeMethod1 ....
}
proc type MyClass.myTypeMethod2 ....
proc type (MyClass).myTypeMethod3 ....
```

can now be invoked on a MyClass type that is owned, shared, borrowed,
or unmanaged and either nilable or non-nilable. It can also be invoked
on any flavor of a subclass of MyClass.

Such a type method is now generic even when MyClass itself is not generic.

If the type method is declared as a secondary method with a specific
receiver type, then only that flavor of the class type is accepted.
For example:

```chpl
// invocable only on the specific flavor returned by getMyClassType()
proc type (getMyClassType()).myTypeMethod4 .....

// invocable only on non-nilable borrowed MyClass
proc type (borrowed MyClass).myTypeMethod5 .....
```

#### Implementation

During scopeResolve, for each type method that needs to be generic
as described above, the compiler:

* changes the type of the `this` formal from `MyClass` to `dtAny`,

* adds the where-clause: `isSubtype(_to_borrowed(_to_nonnil(this)), MyClass)`.

Note:

* The `this` formal of a type method has the `type` intent.

* If the where-clause already exists, switch it to an `&&` of (a) the above
  isSubtype() and (b) the existing where-clause.

This PR also disables checking for the `override` keyword on type methods.
This avoids spurious "missing override keyword" warning when a type method
is inherited by a child class. #13154 asks whether this check should be done.

We consider this to be a temporary step, ex. due to #13153 and #13155.
Later on, we'll need to remove the where clause and instead use an argument
like `anymanagement C`. If we choose to make MyClass generic on the management
type in general (as being discussed in #12917) then we would probably either
apply the change here much more broadly (in which we keep this code and build
on it) - or change the meaning of a class AggregateType within the compiler
(in which case we could remove the where clause code here).

#### Tests

The .good file for `test/functions/typeMethods/anymanaged.chpl` reflects
the current incorrect behavior for `(owned D).mo()` and `(shared D).ms()`,
which should print `true`. See #13109.

I did not add a test to "lock in" the behavior when a type method
inherited from a parent class is invoked on a child class. Specifically,
what type is `this` within the type method in this case - the child class,
the parent class, something else? I am posing this question in #13154.

#### Testing

* [x] Linux64 -futures

### CODE REVIEW

File: compiler/passes/scopeResolve.cpp [hunk 1]
```diff
@@ -1512,12 +1519,54 @@ static void resolveEnumeratedTypes() {
...
+// Convert each "proc type C.myProc() ..." to, roughtly:
+// "proc type any.myProc() where isSubtype(this.type, C) ..."
+//
+static void adjustTypeMethodsOnClasses() {
+  forv_Vec(FnSymbol, fn, gFnSymbols) {
+    if (fn->thisTag != INTENT_TYPE) continue; // handle only type methods
+
+    ArgSymbol* thisArg = toArgSymbol(fn->_this);
+    Type*      thisType = thisArg->type;
+    if (! isClass(thisType)) continue; // handle only classes
```
Comment (mppf) [inline compiler/passes/scopeResolve.cpp]: Can the comment say "handle only undecorated classes"?

File: compiler/passes/scopeResolve.cpp [hunk 2]
```diff
@@ -1512,12 +1519,54 @@ static void resolveEnumeratedTypes() {
...
+    // Update the type of 'this'.
+    thisArg->type = dtAny;
+
+    // The desired where-expression. Clean up this.type for isSubtype().
+    SET_LINENO(thisArg);
+    Expr* isSubtype = new_Expr(
+     "'is_subtype'(%S,'to borrowed class'('to non nilable class'(%S)))",
+     thisType->symbol, thisArg);
+
+    if (BlockStmt* where = fn->where) {
```
Comment (mppf) [inline compiler/passes/scopeResolve.cpp]: Can you call addToWhereClause (defined in normalize.cpp)? I think the main differences from this code are:
 * addToWhereClause adds FLAG_NOT_FULLY_GENERIC on the tested formal
 * addToWhereClause uses `&` to combine rather than `&&`

I don't know why the `&` vs `&&` difference exists. AFAIK FLAG_NOT_FULLY_GENERIC is generally appropriate in such cases but will not matter specifically for type arguments.

Additionally it looks like your approach here (to avoid `&&` if we just added the where clause) is probably better than what happens in addToWhereClause. Perhaps you could improve addToWhereClause and call it?

Comment (vasslitvinov) [reply compiler/passes/scopeResolve.cpp]: I did not put this in the PR because I wanted to take a closer look at & vs &&. My understanding is that the code that inserts `&` happens after `&&` are lowered. So if we insert `&&` where it inserts `&`, then the `&&` will result in an "unresolved call" error at resolution.

Ideally, we'd switch `addToWhereClause` to insert an if-then-else that behaves like an `&&`. At which point it will make sense to redirect the above scopeResolve code to it as well. For now I am leaving it as future work.
