### PR TITLE
Prevent auto local access from optimizing loops with semantic errors

### LINKED ISSUE #23653: Internal error when var is undefined and passed to zip
### Summary of Problem
While putting together the index gather story for the tutorial, I got an internal compiler error.  Below is a reproducer.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;
//use CopyAggregator;

config const numUpdates = 10;
var Src = [1, 2, 3, 4, 5];
var Dest: [0..<numUpdates] int;

{
  const D = blockDist.create({0..numUpdates-1});
  var Inds: [D] int;

  forall (d, i) in zip(Dst, Inds) with (var agg = new SrcAggregator(int)) do
    agg.copy(d, Src[i]);
}
```

**Compile command and error:**
```
chpl replicate.chpl 
replicate.chpl:12: internal error: OPT-FOR-ONS-1181 chpl version 1.32.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### Configuration Information

Homebrew on an Intel Mac.

### PR DESCRIPTION
**Pull request by jabraham17**
Adds new check `loopHasValidOptInfo` to prevent the compiler trying to optimize loops with semantic errors.

This resolves #23653, where the compiler would try to optimize the loop, but because the variable did not exist the optimization would fail. Sadly, this couldn't be handled by the existing use-before-def check because it occurs after the optimization.

Testing: paratest and paratest with gasnet

[Reviewed by @e-kayrakli]

### CODE REVIEW

File: compiler/optimizations/forallOptimizations.cpp [hunk 1]
```diff
@@ -931,7 +931,18 @@ static void gatherForallInfo(ForallStmt *forall) {
...
+
+  auto multiDIndicesSize = forall->optInfo.multiDIndices.size();
+  auto iterSymSize = forall->optInfo.iterSym.size();
+  auto dotDomIterSymSize = forall->optInfo.dotDomIterSym.size();
+  auto iterCallTmpSize = forall->optInfo.iterCallTmp.size();
+
+  return multiDIndicesSize > 0 &&
+         multiDIndicesSize == iterSymSize &&
+         multiDIndicesSize == dotDomIterSymSize &&
+         iterCallTmpSize == multiDIndicesSize;
```
Comment (e-kayrakli) [inline compiler/optimizations/forallOptimizations.cpp:945]: Nit: swap order.

Non-nit: I am not really understanding how this is helping. Do. you remember which of these comparison help in this particular case?

Comment (e-kayrakli) [reply compiler/optimizations/forallOptimizations.cpp:945]: (By looking at the code, I expect all of these to have the same size always)

File: test/optimizations/autoLocalAccess/use-before-def-bug.chpl [hunk 2]
```diff
@@ -0,0 +1,6 @@
+// from issue #23653
```
Comment (e-kayrakli) [inline test/optimizations/autoLocalAccess/use-before-def-bug.chpl:1]: Could you make this more self-contained by adding a sentence summarizing the issue here?

File: test/optimizations/autoLocalAccess/use-before-def-bug.good [hunk 3]
```diff
@@ -0,0 +1,4 @@
+
+Start analyzing forall (use-before-def-bug.chpl:6)
+| Can't optimize this forall: invalid induction variables (use-before-def-bug.chpl:6)
```
Comment (e-kayrakli) [inline test/optimizations/autoLocalAccess/use-before-def-bug.good:3]: This isn't right. `d` and `i` are valid induction variables.

**Review by e-kayrakli — COMMENTED** [review]
I left some inline comments. My main concern is that the log output is misleading. Ideally the check that catches this case (I don't understand which/how, see inline comments) should be in its own helper function, and probably called right after `loopHasValidInductionVariables` around here: https://github.com/chapel-lang/chapel/blob/main/compiler/optimizations/forallOptimizations.cpp#L1419-L1422

That way we can generate a log output specific for this case saying something similar about the iterands but not induction variables.

File: compiler/optimizations/forallOptimizations.cpp (hunk 1 above)
Comment (jabraham17) [reply compiler/optimizations/forallOptimizations.cpp:945]: This helps because of the loop in `gatherForallInfo`, which goes through all iterated expressions. It always appends to `iterSym`, `dotDomIterSym`, and `iterCallTmp`, but it only appends to `multiDIndicesSize` when it finds a non-null iter expr. In this case of a use-before-def, the mismatch is because it cannot find a symbol to put in `iterSym`.

So the check could be simplified to just `multiDIndicesSize > 0 && multiDIndicesSize == iterSymSize`. Although I think I will factor it out to a separate check as you suggested

Comment (e-kayrakli) [reply compiler/optimizations/forallOptimizations.cpp:945]: Hmm, that's strange (an issue with the iterand throwing the induction variable analysis off), but no need to investigate further. Thanks!

Yeah, I agree, any check you deem appropriate can go in a separate function whose failure results in a better log message.

File: compiler/optimizations/forallOptimizations.cpp [hunk 4]
```diff
@@ -1421,6 +1432,11 @@ static void autoLocalAccess(ForallStmt *forall) {
     return;
   }
 
+  if (!loopHasValidOptInfo(forall)) {
+    LOG_ALA(1, "Can't optimize this forall: invalid opt info", forall);
```
Comment (e-kayrakli) [inline compiler/optimizations/forallOptimizations.cpp:1436]: "invalid loop" (or anything else that's more user-facing than "opt info")

**Review by e-kayrakli — APPROVED** [review]
