### PR TITLE
Split initialization for multi-variable declarations in functions

### LINKED ISSUE #16371: Split initialization not working right for multi-variable declarations?
On a branch that I'm working on, I'm disabling the ability to directly read and write sync variables, requiring .readFE() and .writeEF() to be explicitly invoked instead.  The one place that direct writes are supported are in initialization, such that:

```chapel
var x: sync int = 42;
```

is supported.  And due to split initialization, this also means that:

```chapel
var x: sync int;
x = 42;
```

is supported, which makes sense.  However, I'm finding something odd.  While I can do:

```chapel
var x: sync int, y: sync int;
x = 42;
y = 33;
```

and:

```chapel
var x: sync int;
var y: sync int;

x = 45;
y = 33;
```

I can't do:

```chapel
var x, y: sync int;

x = 45;
y = 33;
```

This makes me think that something is broken w.r.t. split initialization and variables sharing a common type expression.

(running into this makes me think we've seen this in some other context, but with a quick search, I couldn't find a related issue.  For some reason, I think @dlongnecke-cray was involved?)

### PR DESCRIPTION
**Pull request by slnguyen**
Resolves #16371

Before this PR, the following
```chpl
record Point {
  var x: real;
  var y: real;

  // This is a default initializer
  proc init() {
    writeln("Point default-init");
    this.x = 0.0;
    this.y = 0.0;
  }

  // This is a useful initializer for this type
  proc init(x: real, y: real) {
    writeln("initializing");
    this.x = x;
    this.y = y;
  }


  // This is a copy initializer
  proc init=(from: Point) {
    writeln("Point copy-init");
    this.x = from.x;
    this.y = from.y;
  }

}


proc = (ref lhs: Point, rhs: Point) {
  writeln("Point assignment");
  lhs.x = rhs.x;
  lhs.y = rhs.y;
}

{

  var a, b: Point;

  a = new Point(1.0, 2.0);
  b = new Point(4.0, 5.0);

  a; b;

}
```
resulted in the following output:
```
Point default-init
initializing
Point assignment
initializing
```
The output shows that split initialization was not applied. In more detail, in the above example, in the line ` var a, b: Point;`  the variable `b` is initialized with `'typeof' a`. The mention of `a` between the lines `var a, b: Point;` and `a = new Point(1.0, 2.0);` prevents split initialization. If split initialization was applied the output would be:
```
initializing
initializing
```
This PR makes the following changes:

- for multivariable declarations in functions, the back propagation of initialization type is moved from the parse pass (in `build.cpp`) to the cleanup pass (in `cleanup.cpp`). Doing so allows us to create a temporary type representing the initialization type and assigning the temporary type to each variable in the multivariable declaration. This way in the example above, for the line ` var a, b: Point;`, both `a` and `b` will be initialized with the temporary type, `b` will not be initialized with `'typeof' a`, allowing split initialization to be applied.
-  moves call of the `backPropagateInitsTypes` function in `build.cpp` from `buildVarDecls` to `buildClassDefExpr` so that it only applies to class fields.  Class fields are treated differently because an AggregateType has an AList of fields and it wouldn't make sense to add a temporary to these.
- to avoid errors for multi-variable declarations before their types/inits are established, adding `gSplitInit` and the check for variables not initialized and with no type is moved from the `checkParsed` pass to `cleanup`.
- modifies several tests of assignment to avoid split-init now that split-init applies to them.

There are two tests added to this PR, the first `backPropagateInitVar.chpl` tests if the above example results in the expected output:
```
initializing
initializing
```
The second test `backPropagateInFunction.chpl` tests if variables are initialized correctly.

This PR:

- [x] Addd test cases
- [x] Passes full local testing

### CODE REVIEW

File: compiler/passes/cleanup.cpp [hunk 1]
```diff
@@ -67,19 +67,155 @@ void cleanup() {
...
+  if(tmpBlock) {
+    block->insertAtHead(tmpBlock);
+    tmpBlock->flattenAndRemove();
+  }	   
+}
+
+static void backPropagate(BaseAST* ast) {
+  if (BlockStmt* block = toBlockStmt(ast)) {
+    if (block->blockTag == BLOCK_SCOPELESS){
+      for_alist(stmt, block->body){
```
Comment (mppf) [inline compiler/passes/cleanup.cpp:164]: It'd be nice to add a comment here indicating that we're looking for scopeless blocks containing only DefExprs (and end of statement markers) since these are how the multi-variable-declarations are represented after parsing

**Review by mppf — APPROVED** [review]
It would be good if the PR message could link to the original issue (#16371). You can even use `Resolves #16371` to close that issue when the PR merges. Since that issue has details about the problem, you could have put less in the PR message, but what is there is OK.

It would also be nice if the PR mentioned:
 * that several tests of assignment needed update to avoid split-init now that split-init applies to them
 * that backPropagateInitsTypes in build.cpp is moved from buildVarDecls to buildClassDefExpr so that it only applies to class fields. The class fields are treated differently because an AggregateType has an AList of fields and it wouldn't make sense to add a temporary to these.  Anyway, this change leaves var multi-decls in functions to be adjusted in cleanup in the new code this PR adds.
 * that the check for variables not initialized and with no type and adding `gSplitInit` is moved from checkParsed to cleanup in order to avoid errors for multi-variable declarations before their types/inits are established

**Comment by mppf** [comment]
Travis is failing with 

> Found tabs :-(
> compiler/passes/cleanup.cpp:158: }

This check happens in `./util/buildRelease/smokeTest`
