### PR TITLE
Make first-class functions retain return intents

### LINKED ISSUE #18905: first-class functions don’t maintain the `ref` return intent
### Summary of Problem
If a first class function has a `ref` intent, it does not seem to be maintained, resulting in a compiler error. Brad has looked at this briefly and suggested filing the issue.

### Steps to Reproduce

**Source Code:**

```chapel
var A: [1..3] int;

proc foo(x: int) ref {
  return A[x];
}

proc bar(fn) {
  ref x    = fn(2);
  x = 42;
}

bar(foo);
writeln(A);
```

**Compile command:**
`chpl issue.chpl`

**Compiler error:**
`issue.chpl:7: In function 'bar':
issue.chpl:8: error: Cannot set a non-const reference to a const variable.
  issue.chpl:12: called as bar(fn: shared chpl__fcf_type_int64_t__ref_int64_t)
note: generic instantiations are underlined in the above callstack`

### Configuration Information

- Output of `chpl --version`:chpl version 1.26.0 pre-release (dbe3743)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv *
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: gasnetrun_ibv *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled *
CHPL_HWLOC: bundled *
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none

### PR DESCRIPTION
**Pull request by bradcray**
Prior to this commit, the compiler's implementation of first-class
functions as class methods failed to preserve the function's return
intent on the method—using the default RET_VALUE return intent
instead.  As pointed out by @thomasrolinger on issue #18905,
this made 'ref' and 'const ref' return intents fail to work as expected/
intended.

Here, I'm propagating the return intent of the function being
captured into the classes and methods used to implement the
first-class function which makes the `const ref` and `ref` cases
work as expected.  I added a pair of tests to lock this behavior
in as well.

I tried adding tests to see whether a `param` return intent would
work correctly, but had challenges unrelated to the return intent
itself (e.g., FCFs don't seem to do very well with param arguments
or computations), so left that as future work, under the general
"FCFs haven't really received much attention yet" mantle and the
sense that I was not making things worse in this regard.

I've added a future here indicating that we don't properly complain
about functions that return 'const ref' being stored in 'ref'
variables, which is orthogonal to this issue but something I
stumbled across in testing and filed #18909 to capture.

Resolves #18905

### CODE REVIEW

File: compiler/resolution/preFold.cpp [hunk 1]
```diff
@@ -3055,6 +3057,7 @@ static Type* createOrFindFunTypeFromAnnotation(AList& argList,
                                                   parent,
                                                   argList,
                                                   false,
+                                                  RET_VALUE,
```
Comment (vasslitvinov) [inline compiler/resolution/preFold.cpp:3060]: I do not understand this code well enough to see the ramifications of this default. I am willing to accept it for now.

**Review by vasslitvinov — APPROVED** [review]
Looks good.

File: compiler/resolution/preFold.cpp (hunk 1 above)
Comment (bradcray) [reply compiler/resolution/preFold.cpp:3060]: I made the new `retTag` argument required so that if/when future calls to the function are added in the future, people would think about what the return tag should be rather than having bugs like this lurk beneath the surface.  My understanding is that RET_VALUE is the default retTag for a function (see https://github.com/chapel-lang/chapel/blob/main/compiler/AST/FnSymbol.cpp#L55), so is what these calls had been getting before this change.  So here, I'm simply making that choice of default more explicit.  I looked briefly at this function to see whether there's something smarter we could/should be doing, but nothing jumped out at me, and so I concluded that I wasn't leaving things in any worse shape than they had been in for this call.
