### PR TITLE
Disable an assertion to turn an assertion error for incorrect user programs into a user-facing error

### LINKED ISSUE #16860: defining arrays as borrowed gives poor user feedback from chpl.
When defining an array in a record, setting the ownership of the array to `borrowed`, and not explicitly setting the array domain one ends up with an error **AST-LOO-XPR-0201**

### Summary of Problem

I have created my own [key comparator for sorting](https://chapel-lang.org/docs/1.23/modules/packages/Sort.html#the-key-method). My can sort one array based on values in a diffrent array `fScore`.

I want to be explicit that fScore is an array. The array is owned outside the record. The array will outlive the record. The domain of the array is defined in a different scope, and is not available.

As new to the language it feels natural to define this as an `var <variablename> : borrowed [..] real;`.

One expects the program to compile, but this causes error listed below. This user feedback is rather poor on what causes the problem.

```bash
internal error: AST-LOO-XPR-0201 chpl version 1.23.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

I are two solutions to this problem.

#### Removed borrowed

On line 2. By changing the record type from `  var fScore : borrowed [..] real;` to `  var fScore : [..] real;` the program compiles without an error.

#### Skip the array type

On line 2. By changing the record type from `  var fScore : borrowed [..] real;` to `  var fScore;` the program compiles without an error.

### Steps to Reproduce

**Source Code:**

In chapel file FScoreComparator.chpl
```chapel
record FScoreComparator {
  var fScore :  borrowed [..] real;
  proc init(fScore : borrowed [..] real) {
    this.fScore = fScore;
  }
}

proc FScoreComparator.key(i) {
  var D = this.fScore.domain;
  if D.contains(i) then
    return this.fScore[i];
  else
    return max(real);
}
```

**Compile command:**
`chpl FScoreComparator.chpl`

### PR DESCRIPTION
**Pull request by bradcray**
This addresses user issue #16860 in which an early assertion
in the compiler generated an internal error for unsupported
patterns in user code when the lack of the assertion results
in a user-facing error message later in compilation.  Specifically,
I removed the assertion and let the error case through.

Tested linux64 for everything and the new test with `--verify`,
ASAN, and valgrind.

Resolves #16860.

### CODE REVIEW

File: compiler/AST/LoopExpr.cpp [hunk 1]
```diff
@@ -198,7 +198,11 @@ bool LowerLoopExprVisitor::enterLoopExpr(LoopExpr* node) {
   if (node->getStmtExpr() == NULL) {
     // Don't touch LoopExprs in DefExprs, they should be copied later into
     // BlockStmts.
-    INT_ASSERT(isDefExpr(node->parentExpr));
+
+    // While this works for correct codes, it results in assertion errors
+    // for incorrect codes that don't generate errors until resolution:
+    //
+    //    INT_ASSERT(isDefExpr(node->parentExpr));
```
Comment (mppf) [inline compiler/AST/LoopExpr.cpp:205]: Could you check that the failing case runs OK when the compiler is run under valgrind and verify?

**Review by mppf — APPROVED** [review]

File: compiler/AST/LoopExpr.cpp (hunk 1 above)
Comment (bradcray) [reply compiler/AST/LoopExpr.cpp:205]: For the new test?  Good thought!

- [x] `--compopts --verify` works
- [x] `--valgrind` works
- [x] `export CHPL_SANITIZE=address` works
