### PR TITLE
Fix support for requires of .chpl files within implicitly used modules

### LINKED ISSUE #18883: Using require on a Chapel file only works if in the module with the main function
### Summary of Problem
Trying to `require` a module in a Chapel file besides the file with the `main()` function does not bring in the `require`d file. It seems that putting a `require` for a Chapel module in any included module should work as if it were in the `main` module in the project hierarchy, as it does with non-Chapel module `require` statements.

### Steps to Reproduce

`A.chpl` with main function
```
module A {
   proc main() {
      use B;
      test();
   }
}
```
`B.chpl` with require (in same directory as A)
```
module B {
  require '../C.chpl';
  public use C;
}
```
`C.chpl` with function to call (up one directory from modules A and B):
```
module C {
  proc test() {
    writeln("In module C");
  }
}
```
And this is the error that you see compiling with `chpl A.chpl`: `error: Cannot find module or enum 'C'`

Moving the `require '../C.chpl'` to module A and the code compiles and runs as expected.

### PR DESCRIPTION
**Pull request by bradcray**
BenMcD pointed out in issue #18883 that we were not doing a good job of
parsing files in `require` statements that were in implicitly used modules.
This was due to the lack of a loop in the logic that starts parsing dependent
files that weren't explicitly named on the command-file.  The fix was
fairly simple: add a loop that continues parsing things while it still
finds new things that need to be parsed.  This PR does so and also adds
an extended version of Ben's motivating test that takes the chain one
step further to make sure that it can spin for multiple rounds (I got
it wrong the first time around, so only got one level deep).

In the test, I added a few copies of the modules in subdirectories because
of some vagueness (which I think there may be open issues for) about
whether paths should be relative to the file they live in or the invocation of
the compiler.  I didn't make any attempts to mess with the current behavior
here, or even think about it much, but put in some extra copies of the files
in case the behavior changes down the road.

Resolves #18883.

### CODE REVIEW

File: compiler/parser/parser.cpp [hunk 1]
```diff
@@ -350,6 +350,38 @@ static void printModuleSearchPath();
...
+  const size_t reductionMaxLength = 16;
+  /*
+    Ensure that all the files parsed don't exceed
+    (NAME_MAX - reductionMaxLength) e.g. 239 bytes on
+    unix and linux system.
+  */
+  const size_t maxFileName = NAME_MAX - reductionMaxLength;
+  const char* baseName = stripdirectories(inputFileName);
+  if (strlen(baseName) > maxFileName)
+    {
```
Comment (mppf) [inline compiler/parser/parser.cpp:371]: weird indenting

**Review by mppf — APPROVED** [review]

File: compiler/parser/parser.cpp (hunk 1 above)
Comment (bradcray) [reply compiler/parser/parser.cpp:371]: I'm not normally a "curly bracket on its own line" kind of guy, but that's how the code was formatted before I refactored it and this is how emacs indents that style by default.  Would you like me to change this?  Do you care what I change it to?  (e.g., I'd probably change it to the curly bracket being on the previous line).

Comment (bradcray) [reply compiler/parser/parser.cpp:371]: (I assume the rationale is "we indent the single statement that follows a single-statement conditional and then we indent statements within a compound statement" and checking Wikipedia, it seems like this is the case and that it is "GNU style", which is the default for emacs.  I'm not advocating for preserving it per se, just explaining how it ended up like this and still wondering whether you want it changed).

Comment (mppf) [reply compiler/parser/parser.cpp:371]: It's not a big deal but I'd change it. Throughout the compiler source code, things tend to be either

```
if (bla) {
  stmts;
}
```

or 

```
if (bla)
{
  stmts;
}
```

I consider both of the above typical for our code and totally acceptable.

I don't know of anybody on our team who wants to advocate for the `{` to be indented (which is what we have here). I'm sure there are people in the broader world who like that. 

But obviously it does not make much difference.
