### PR TITLE
Zero-initialize variables of extern type

### LINKED ISSUE #7992: extern types don't have default values
I was ambushed by this while working on #7908. In `IO.chpl`, my function `file.check(out error: syserr)` was causing `hello.chpl` to segfault. The generated code was not default initializing the `syserr` formal, leading to garbage memory in the `out error` and cascading failures after that.

While I've managed to create a workaround for this issue, we should still consider giving default values to extern types such as `syserr`. Here's an example:

``` chapel
proc test() {
  var x:syserr;
  writeln(x:int);
}

test();
```

output:
```
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by mppf**
Updates the compiler to:
 * allow `proc init()` to specify the default initializer for an extern record
 * if that does not apply, zero-initialize variables of extern type.
 
Before this PR, such variables of extern type were not initialized at all and stored garbage memory.

Resolves #7992

- [x] full local futures testing
- [x] full local futures testing with CHPL_LLVM=none

Reviewed by @e-kayrakli - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
@chapel-lang/perf-team - @bradcray and I have been discussing whether or not we can bring this PR into the point release. I have a minor concern that it could have performance impact -- but, I am really doubtful this would have any noticeable performance impact. Any concerns here with the concept? (the PR will still need a review in any case).

**Comment by ronawho** [comment]
I would not expect any performance fallout from this, but we could run it through perf playground first if we wanted to be extra careful.

**Comment by bradcray** [comment]
> we could run it through perf playground first if we wanted to be extra careful.

I'd also personally be OK with merging soon, and backing out if we had any surprises that we weren't happy with (because I'm similarly not worried about it, and that seems like the shortest path).

**Comment by ronawho** [comment]
That would be fine with me

File: compiler/codegen/cg-expr.cpp [hunk 1]
```diff
@@ -5279,6 +5279,38 @@ DEFINE_PRIM(STACK_ALLOCATE_CLASS) {
...
+  INT_ASSERT(dest.isLVPtr == GEN_VAL);
+  // And also above call should generate a value
+  INT_ASSERT(size.isLVPtr == GEN_VAL);
+
+  if (info->cfile) {
+    GenRet zero = codegenZero32();
+    codegenCall("memset", dest, zero, size);
+  } else {
+#ifdef HAVE_LLVM
+    llvm::ConstantInt* zero = info->irBuilder->getIntN(8, 0);
```
Comment (e-kayrakli) [inline compiler/codegen/cg-expr.cpp:5298]: The zeroes that we have seem to have different widths (8-bit here vs 32-bit for C). I don't think this should be an issue, but wanted to bring up in case it was inadvertent, or you think it may be an issue.

File: test/extern/ferguson/extern-record-proc-other-init.good [hunk 2]
```diff
@@ -0,0 +1,5 @@
+extern-record-proc-other-init.chpl:24: In function 'testMystruct':
+extern-record-proc-other-init.chpl:26: error: unresolved call 'R.init()'
+extern-record-proc-other-init.chpl:3: note: this candidate did not match: R.init(arg: int(64))
+extern-record-proc-other-init.chpl:26: note: because call does not supply enough arguments
+extern-record-proc-other-init.chpl:3: note: it is missing a value for formal 'arg: int(64)'
```
Comment (e-kayrakli) [inline test/extern/ferguson/extern-record-proc-other-init.good:5]: Shouldn't this be a "cannot default initialize variable" or some sort of split-init error?

The error message is not ideal. But if it is not easy to tackle I don't have a problem with this for now -- not the worst error message I saw.

**Review by e-kayrakli — APPROVED** [review]

File: test/extern/ferguson/extern-record-proc-other-init.good (hunk 2 above)
Comment (mppf) [reply test/extern/ferguson/extern-record-proc-other-init.good:5]: Yeah, I think improving this error message is nice future work but it's outside of the scope of this PR.

File: compiler/codegen/cg-expr.cpp (hunk 1 above)
Comment (mppf) [reply compiler/codegen/cg-expr.cpp:5298]: I think it's correct. C's `memset` is odd in that it accepts a byte to fill with as an `int`. The LLVM intrinsic accepts a byte (`i8`).
