### PR TITLE
Fix some bugs with promotion and operator methods

### LINKED ISSUE #17218: Operator methods and promotion do not play nicely
### Summary of Problem
Operator methods cause an internal compiler error when used in a promoted setting.

### Steps to Reproduce

**Source Code:**

```chapel
record Foo {
  var x: int;
}
operator Foo.==(lhs: Foo, rhs: Foo) {
  return lhs.x == rhs.x;
}
proc main() {
  var arr1: [0..3] Foo;
  var arr2: [0..3] Foo;
  writeln(arr1 == arr2);
}
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[`test/functions/operatorOverloads/operatorMethods/promotedCall.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/functions/operatorOverloads/operatorMethods/promotedCall.chpl) #TBD

### Configuration Information

- Output of `chpl --version`: chapel 1.24.0 (pre-release)

### PR DESCRIPTION
**Pull request by lydia-duncan**
When the call to an operator needs to be adjusted due to either missing
arguments that are present in the function (because we're calling an
operator method) or due to additional actuals that are not present in
the function (because we're calling a standalone operator, but are in
a method on a type that has its own definition of that operator as a
method), we typically perform that after promotion wrappers have
been created.  However, we had failed to update the creation of a
promotion wrapper when promotion of an operator was needed.

This change adds a field to the PromotionInfo type that tracks the
index difference between the actuals in the call and the formals
stored in the promotedType field.  When a call has less actuals
than the function has formals, this value will be -2 (because the
method token and corresponding "this" actual are missing in the
call) and we will ignore those formals when determining how to
create the wrapper.  When the call has more actuals than the
function has formals, this value will be 2 (because the method
token and corresponding "this" formal are missing in the function)
and we will ignore those actuals when looking for the first actual
to promote.

Additionally, add the operator flag to the promotion wrapper so
that the call to it may also be adjusted appropriately.

Resolves #17218
Resolves Cray/chapel-private#1782

Adds a test of both cases mentioned above, which both failed
before but now work.

TODO:
- [x] full paratest with latest change

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@mppf - would you be up for reviewing this?  It's a code freeze task, not feature freeze so it's okay to wait until your feature freeze stuff is done

File: compiler/resolution/wrappers.cpp [hunk 1]
```diff
@@ -2113,12 +2123,28 @@ PromotionInfo::PromotionInfo(FnSymbol* fn,
 {
   int numActuals = actualFormals.size();
 
+  // Operators may mismatch the number of formals and the number of actuals.
+  // Store any difference for later.
+  if (numActuals != fn->numFormals() && fn->hasFlag(FLAG_OPERATOR)) {
+    formalToActualOpMod = fn->numFormals() - numActuals;
+  } else {
+    formalToActualOpMod = 0;
+  }
```
Comment (mppf) [inline compiler/resolution/wrappers.cpp:2132]: it's OK to do it this way but it would make more sense to me to check that the mismatched args are what we expect (method token and then this).

**Review by mppf — APPROVED** [review]
