### PR TITLE
Fixes to error handling with iterators

### LINKED ISSUE #18773: segfault (use-after-free error) when calling throwing function within a forall loop
### Summary of Problem

[reported by @jlbyrne-hpe]

When calling a throwing function within a forall loop over a distributed array,
we seem to be getting a segfault due to a use-after-free style error as
reported by valgrind.  Our guess is that the error is not properly getting
propagated out of the forall loop as it should be.

If the forall loop is changed to a for loop, the problem goes away, and I have
also not been able to reproduce the issue in similar cases such as:

* a forall loop over a range
* a forall loop over a range with an on-clause
* a nested coforall loop + on-clause similar to what I think of the block array as doing (though it is actually using leader-follower today)

In some cases, wrapping the throwing function within a `try { }` within the
forall loop's body makes the error go away, but not in the future filed below.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;

var A = newBlockArr({1..10}, real);

proc throwingFunction() throws {
  throw new owned Error("die!");
}

proc throwingCaller() throws {
  forall a in A {
    throwingFunction();
  }
}

proc main() {
  try { throwingCaller(); }
  catch e { writeln("Caught an error!"); }
}
```

**Associated Future Test(s):**

[`test/errhandling/parallel/forall-calls-throwing-fn2.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/errhandling/parallel/forall-calls-throwing-fn2.chpl
          ) #18774

### Configuration Information

- Output of `chpl --version`: `chpl version 1.26.0 pre-release (cf9569b7ad)`

### LINKED ISSUE #19378: Throwing within a forall loop in a function not caught by try/catch
### Summary of Problem
Throwing within a `forall` loop inside of a function is not caught by a try/catch wrapping the function.

### Steps to Reproduce

This code will report uncaught TaskErrors:
```chapel
try {
  loop();
} catch e {
  writeln("Caught error");
}

proc loop() throws {
  forall i in 0..0 do
    throw new Error();
}
```
But it seems like the error should be propagated upwards and caught by the overarching try/catch, printing "Caught error".

This code will catch the error and work as I'd expect, but it seems strange that the extra try/catch is required.
```chapel
try {
  loop();
} catch e {
  writeln("Caught error");
}

proc loop() throws {
  try {
    forall i in 0..0 do
      throw new Error();
  } catch e {
    throw e;
  }
}
```

Related issue: #18773
Related future test: `test/errhandling/parallel/forall-in-function-throws.chpl`

### PR DESCRIPTION
**Pull request by vasslitvinov**
This PR improves the handling of errors within a "halting" context, i.e., when the throwing expression - either a `throw` statement or a call of a throwing function - occurs outside of a "try" context, i.e., a `try` or `try!` block or else in a function that `throws`. It makes the behavior more consistent with the "immediate" option in #19388. For example, an error thrown in a "halting" context in an iterator is now reported as "uncaught" in the iterator, not in the loop over the iterator. An error thrown in a "halting" context in a forall statement is reported as "uncaught" where it is thrown, not at the forall statement. The PR fixes some bugs and resolves #19378.

### Implementation Details

A key change is to tune up decision making in ErrorHandlingVisitor::enterCallExpr() where it chooses between propagating the thrown error to the function's error_out, to an enclosing try block, or halding immediately.

* Calls to throwing functions in a halting context are lowered during the `lowerErrorHandling` pass by adding calls to `chpl_uncaught_error`, not `chpl_propagate_error`, as it used to be.

* Calls to `_waitEndCount()` are a special case, as this function propagates errors from the associated task functions. They used to be lowered in a halting context always by adding calls `chpl_propagate_error`, like all other throwing functions. This PR changes that to call:
  - `chpl_uncaught_error` when the corresponding source code appears lexically within a procedure,
  - `chpl_propagate_error` when it is within an iterator.

  Background: `chpl_uncaught_error` always causes the program to halt. `chpl_propagate_error` also always causes the program to halt, however it may be replaced during lowerIterators / iterator inlining to propagating the exception to a now-enclosing try block or throwing function.

* Task functions that correspond to task constructs that, in the source code, occur in a halting context, are marked with `FLAG_OUTSIDE_TRY`. This is easiest to do before the task constructs get converted to task functions, so I put it in createTaskFunctions.

* The new `FLAG_FORALL_BREAK_LABEL` helps find the forall statement's error handler just like FLAG_ERROR_LABEL helps find other handlers in handleChplPropagateErrorCall(), i.e., when lowering calls to chpl_propagate_error / gChplPropagateError. These are inserted in lowerErrorHandling() to pass error handling information to lowerIterators(), where they are lowered away. The behavior of handleChplPropagateErrorCall() remains unchanged unless we are lowering a forall statement. This reduces the chance of introducing unwanted behavior.

* The changes to the tests in `parallel/forall/task-private-vars/throwing-init-exprs/` are aimed to preserve the previously-observed behavior so that their (numerous) .good files do not need to change.

* I added comments based on what I learned.

### Future work

(f1) Clarify the [error handling section of the language spec](https://chapel-lang.org/docs/master/language/spec/error-handling.html#handling-errors) that the relationship between a thrown error and its try/try! block is lexical, not dynamic. "Lexical" is mentioned in one case and omitted in another case. This PR and this writeup assume this is the desired semantics.

(f2) Have a `try` block within a parallel iterator handle only the exceptions thrown within its lexical scope, not those thrown in the loop body. For example:
```chpl
proc myIter(param tag) where tag == iterKind.standalone {
  try {
    coforall ... {
      functionThatThrows();
      yield ...;
    }
  }
}
```

When this iterator is invoked in a forall statement under the current implementation, the above try-block will handle both the exceptions thrown by functionThatThrows() and those thrown in the loop body of the forall.

(f3) Report correct line numbers when an error is handled or not handled in an iterator that is inlined. For example:
```chpl
proc myIter(param tag) where tag == iterKind.standalone {
  ...
  functionThatThrows(); // assume no surrounding 'try'
  ...
}
```

When this iterator is invoked in a forall statement and the program reports during execution that an exception is thrown at line NNN and uncaught at line MMM, the line MMM points into the forall statement, whereas it should point into `myIter()`.

This problem is due to the inlining-based implementation of loops, whereby the line numbers associated with the iterator code are replaced with the loop's line number upon inlining the iterator into the loop. For the same reason if we were stepping through the iterator code in the debugger, it would be pointing at the loop line number, not the iterator line numbers. Iterator line numbers can be observed in both of these scenarios if compiling with `--preserve-inlined-line-numbers`.

(f4) Make it a compile-time error to have something thrown in a `defer` statement -- until such time that we figure out how to make the program behavior reasonable (and implement it). Currently it may be a runtime error or might even propagate the error upstream.

Testing: standard paratest; multilocale tests under gasnet

### CODE REVIEW

File: compiler/resolution/lowerIterators.cpp [hunk 1]
```diff
@@ -1747,7 +1747,7 @@ fixupErrorHandlingExits(BlockStmt* body, bool& adjustCaller) {
 
 static bool
 findFollowingCheckErrorBlock(SymExpr* se, LabelSymbol*& outHandlerLabel,
```
Comment (dlongnecke-cray) [inline compiler/resolution/lowerIterators.cpp:1749]: A summary comment for this helper would be great.

File: compiler/passes/createTaskFunctions.cpp [hunk 2]
```diff
@@ -654,6 +652,28 @@ static void replaceVarUses(Expr* topAst, SymbolMap& vars) {
...
+// Is this expr within a try or try! statement or a 'throws' function?
+static bool inTryContext(Expr* expr) {
+  if (FnSymbol* parentFn = toFnSymbol(expr->parentSymbol)) {
+    if (parentFn->throwsError())
+      return true;
+    if (isTaskFun(parentFn) && ! parentFn->hasFlag(FLAG_OUTSIDE_TRY))
+      return true;
+  }
+
+  Expr* curr = expr->parentExpr; // must be inTree()
```
Comment (dlongnecke-cray) [inline compiler/passes/createTaskFunctions.cpp:666]: Could we just `INT_ASSERT` that?

**Review by dlongnecke-cray — APPROVED** [review]
Read through it a few times, I _think_ I understand what's going on, but this sort of lowering is hard to decipher. The comments you've added certainly make things easier - thanks for adding them!

File: compiler/passes/createTaskFunctions.cpp (hunk 2 above)
Comment (vasslitvinov) [reply compiler/passes/createTaskFunctions.cpp:666]: I suggest it is not worth it. Much of the compiler code relies on this condition without INT_ASSERT-ing it; if the condition does not hold, the compiler would stop rather than silently doing something incorrectly. This case is not different. So by analogy I should probably remove the comment, as the rest of the compiler typically does not have it. :)
