### PR TITLE
Generate an error for domain queries in field

### LINKED ISSUE #5140: domain query fields cause internal errors
### Summary of Problem

When declaring array fields that use domain queries (e.g., 'X: [?D] real;'), the compiler generates an internal error.  Internal errors are always indicative of bugs.  I don't believe we ever intended to support domain queries here, so it should generate a helpful user-focused error message rather than an internal error.  (See also related issue #5141)

### Steps to Reproduce

**Source Code:**

```chapel
// Excerpted from test/classes/generic/domainQueryField.chpl:
class C {
  var X: [?D] real;
}

var A: [1..1000] real;
var myC = new C(A);
```

**Compile command:**
chpl domainQueryField.chpl

**Execution command:**
N/A

### Configuration Information

- Output of `chpl --version`: 1.14.0.117304e
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

### PR DESCRIPTION
**Pull request by bradcray**
This PR fixes #5140 in which a user reported that the use of domain queries in array field types resulted in an internal error.  This is something we've never intended to support, but have not generated a good error message for either.  Issue #5141 asks whether it's something we might want to support down the line.

The approach taken here is to add a check to the checkParsed pass that looks for DefExprs whose types are arrays and whose queries themselves contain a DefExpr.  I borrowed this logic from normalize.cpp which processes such domain queries when they do occur in formal argument types.

### CODE REVIEW

File: compiler/passes/checkParsed.cpp [hunk 1]
```diff
@@ -66,6 +66,25 @@ checkParsed() {
               USR_FATAL_CONT(def->sym,
                              "Variable '%s' is not initialized or has no type",
                              def->sym->name);
+    }
+
+    //
+    // This test checks to see if query domains (e.g., '[?D]') are
+    // used in places other than formal argument type specifiers.
+    //
```
Comment (noakesmichael) [inline compiler/passes/checkParsed.cpp]: Largely FYI and not a request to edit.  It is increasingly the convention to prefer
isFnSymbo(), which returns a bool, rather than toFnSymbol(), which returns NULL
or a FnSymbol* in this context.
