### PR TITLE
Avoid unnecessary instantiations for generic functions with later concrete arguments

### LINKED ISSUE #15928: Able to pass non-param values to a param argument when it isn't the first argument
### Summary of Problem
Chapel allows you to pass a variable into a `param` argument 
when there is a prior argument that is an array (throws an error, 
as expected, when it is an int) and will execute the method with 
the default value, not the one passed in. The code below should
instead result in an error about using a non-param argument.
Also, the below code results in the expected error when the first
argument is the `param` instead of the array

### Steps to Reproduce

**Source Code:**

```chapel
proc foo(a: [] int, param p=false) {
  writeln("value of p: ", p);
}
var arr = [1,2,3];
var temp = true;
foo(arr, temp);
```

**This code throws the expected error:**

```chapel
proc foo(a: int, param p=false) {
  writeln("value of p: ", p);
}
var arr = [1,2,3];
var temp = true;
foo(arr[0], temp);
```

**Compile command:**
`chpl foo.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.23.0 pre-release (3bbc139ab6)
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/
usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/
SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### LINKED ISSUE #16470: unnecessary instantiations for generic functions with later concrete arguments
When helping @ronawho with an issue with Arkouda running into the max instantiation limit for `_cast` with 1.22, I noticed that the compiler does not rule out a function with a concrete formal after a generic one if the formal does not match.

For example:

``` chapel
use CPtr;

proc mockcast(type t, arg: int(32)) where t == string
{
}

proc mockcast(type t:c_ptr, arg: c_ptr)
{
}


var n32 = 1:int(32);
mockcast(string, n32);
var n32ptr = c_ptrTo(n32);
mockcast(c_ptr(int(8)), n32ptr);
```

when compiled with this patch to the compiler:
```
diff --git a/compiler/resolution/generics.cpp b/compiler/resolution/generics.cpp
index d219af80ab..fb16f1c0d6 100644
--- a/compiler/resolution/generics.cpp
+++ b/compiler/resolution/generics.cpp
@@ -800,6 +800,8 @@ FnSymbol* instantiateFunction(FnSymbol*  fn,
   return newFn;
 }
 
+#include "view.h"
+
 void explainAndCheckInstantiation(FnSymbol* newFn, FnSymbol* fn) {
   if (explainInstantiationLine == -2) {
     parseExplainFlag(fExplainInstantiation,
@@ -811,6 +813,9 @@ void explainAndCheckInstantiation(FnSymbol* newFn, FnSymbol* fn) {
     explainInstantiation(newFn);
   }
 
+  if (newFn->name == astr("mockcast")) {
+    nprint_view(newFn);
+  }
   checkInstantiationLimit(fn);
 }
```

will show 3 instantiations of `mockcast` when there ought to only be 2.
In particular, `proc mockcast(type t, arg: int(32)) where t == string` is instantiated for the call `mockcast(c_ptr(int(8)), n32ptr);`. That is because the compiler hasn't yet resolved the type of `arg`.

Now, `hasGenericFormals` will be run on the function before it is checked for applicability in `checkGenericFormals`. It resolves the formals in order, but it stops at the first generic formal. One reason for that is that a later formal might have a type expression that depends on the earlier formal, as with e.g. `inline proc *(x: _tuple, y: x(0).type)`.

So, to resolve the issue, we would need a way to attempt to resolve the type expression but to give up if something ends up being generic; and/or we could give up if the type expression refers to a previous generic formal.

### PR DESCRIPTION
**Pull request by mppf**
Resolves #16470.
Resolves #15928.

In the issue #16470, we were seeing problems with Arkouda running into
the instantiation limit for certain `_cast` functions that should not
have been candidates for most calls. I was able to create a small
reproducer as shown in #16470. This PR fixes the problem by ruling out
generic candidate functions before instantiation in more cases.

For example, a cast function like
`proc _cast(type t, arg: int(32)) where t == string`
was being instantiated for a call site with two `c_ptr`
typed arguments. In other words, the fact that the function couldn't
possibly match due to passing a pointer actual argument to an `int(32)`
formal argument was not used by the compiler before instantiating.

The problem is that `checkGenericFormals` doesn't actually check any
arguments that don't have their type established yet. Meanwhile,
`tagIfGeneric`/`hasGenericFormals` (which is called early in
`ResolutionCandidate::isApplicable`) establishes the types for arguments
up until the first generic argument (because at that point, it has served
its purpose - it knows the function is generic). As a result,
`checkGenericFormals` was only checking arguments up to and including the
first generic argument.

There is one situation in which it would be impractical to establish the
type for a second generic argument before instantiating the function
signature. In particular, the language allows the types of later
arguments to depend on earlier arguments. For example, in
`proc f(a, b: typeFn(a.type))`,
the type for the second argument cannot really be
established without performing substitutions (which is currently done
when instantiating the signature).

This PR improves the situation by adjusting `hasGenericFormals` to
establish the types for all arguments up until an argument is encountered
that has a type expression that mentions a previous generic argument.
Note that some of these arguments can still have generic types. This
allows cases like the cast above to be ruled out before instantiation
while still allowing cases like `f` above to work correctly.

This PR only offers modest improvement in compile time but is probably
worthwhile anyway. I have observed compilation time improvements when
compiling `hello.chpl` with a debug build of the compiler. With an
optimized compiler, the time to compile `hello.chpl` is not very much
changed by this PR. However it happens to resolve the case described in #15928
(because more argument types are established to be checked) and it
should reduce problems with programs that come near to the instantiation
limit.

Reviewed by @vasslitvinov - thanks!

- [x] full local futures testing

### CODE REVIEW

**Comment by vasslitvinov** [comment]
While this is a good fix, I suggest that this particular case:
```chpl
proc _cast(type t, arg: int(32)) where t == string
```
be written as
```chpl
proc _cast(type t: string, arg: int(32))
```

File: compiler/AST/FnSymbol.cpp [hunk 1]
```diff
@@ -735,10 +735,44 @@ TagGenericResult FnSymbol::tagIfGeneric(SymbolMap* map, bool abortOK) {
 // 'map' is expected to be non-NULL if this function has been instantiated.
 //
 bool FnSymbol::hasGenericFormals(SymbolMap* map) const {
+  bool anyGeneric = false;
+
+  std::vector<unsigned char> formalIsGeneric;
```
Comment (vasslitvinov) [inline compiler/AST/FnSymbol.cpp:740]: I'd expect `formalIsGeneric` to contain bools.
OK to leave as-is.

File: compiler/AST/FnSymbol.cpp [hunk 2]
```diff
@@ -735,10 +735,44 @@ TagGenericResult FnSymbol::tagIfGeneric(SymbolMap* map, bool abortOK) {
...
+
+      bool dependsOnPreviousGeneric = false;
+      int i = 0;
+      if (anyGeneric) {
+        for_formals(prevFormal, this) {
+          if (i >= count)
+            break;
+
+          int cursz = formalIsGeneric.size();
+          if (i < cursz && formalIsGeneric[i] == 1) {
```
Comment (vasslitvinov) [inline compiler/AST/FnSymbol.cpp:759]: Makes me think that we may as well update `formalIsGeneric` eagerly, rather than lazily, to simplify quite a bit of logic around it. OK to leave that for another time.

File: compiler/AST/FnSymbol.cpp [hunk 3]
```diff
@@ -786,11 +820,18 @@ bool FnSymbol::hasGenericFormals(SymbolMap* map) const {
...
                   "   formal argument '%s' causes it to be", formal->name);
       }
-      return true; // no need to examine the remaining formals
     }
+    anyGeneric = anyGeneric || isGeneric;
+    if (isGeneric) {
+      while ((int)formalIsGeneric.size() < count) {
+        formalIsGeneric.push_back(0);
+      }
+      formalIsGeneric.push_back(isGeneric?1:0);
```
Comment (vasslitvinov) [inline compiler/AST/FnSymbol.cpp:829]: You can just push_back a `1` in the above.
OK to leave as-is, please double-check correctness.

**Review by vasslitvinov — APPROVED** [review]
Good. See my minor comments.

**Comment by mppf** [comment]
@vasslitvinov 

> 
> While this is a good fix, I suggest that this particular case:
> ```chpl
> proc _cast(type t, arg: int(32)) where t == string
> ```
> be written as
> ```chpl
> proc _cast(type t: string, arg: int(32))
> ```
> 

The cast we were running into with Arkouda was written with the where clause in 1.22 but not on master anymore. Anyway the specific cast above was created simply as a reproducer. I agree we should write such functions using the second form.

File: compiler/AST/FnSymbol.cpp (hunk 1 above)
Comment (mppf) [reply compiler/AST/FnSymbol.cpp:740]: I was avoiding the `std::vector<bool>` which has a different representation and uses bit masking.

File: compiler/AST/FnSymbol.cpp (hunk 2 above)
Comment (mppf) [reply compiler/AST/FnSymbol.cpp:759]: The patch used to do that, but I got slightly better compiler performance doing it this way. I do it this way in order to avoid allocating the `std::vector`'s buffer in the event the function is entirely concrete.

Comment (mppf) [reply compiler/AST/FnSymbol.cpp:759]: (LLVM's data structures like `SmallVector` are designed for cases like this and I look forward to the day we can use them throughout the compiler).
