### PR TITLE
Narrow lvalue checking special case from arrays to array views

### LINKED ISSUE #20166: Are arrays returned by value passable to ref formals?
Related: #13106 #20137

Should a `ref` formal accept an array returned by a function
with  the default return intent? What if it is a `const ref` formal and/or
the function's return intent is `const` ? For example:

```chpl
proc writeArr(ref X) {  // what if X has a `const ref` intent?
  writeln(X);
}

proc addEm() {    // what if addEm() has a `const` return intent?
  return [1,2];
}

writeArr(addEm());
```

Today all four combinations of {val,const} return intent * {ref, const ref}
argument intent are accepted. Should they be?

Test:
```
test/users/thom/arrArg-fromFunction.chpl
```

### LINKED ISSUE #22330: when should a value returned by a function be mutable?
See also #17195.

Today it's the case that a function that returns by value produces something that cannot be modified, unless it is an array.

For example:

``` chapel
proc foo() {
  return 42;
}

foo() = 43; // error: illegal lvalue in assignment
```

But, when returning an array, such things are valid and sometimes useful. Here is an example that mutates the value returned by `makeInputArray` in-place to avoid needing more space:

``` chapel
proc makeInputArray(n: int) {
  var A:[1..n] int = 1..n;
  return A;
}

proc mutateAndSum(ref A) {
  for x in A {
    x *= 2;
  }
  return + reduce A;
}

var sum = mutateAndSum(makeInputArray(1000)); // compiles today!
writeln(sum);
```

What should we do about this?

### Option 1: Allow returned values to be mutated

Make both of the above programs legal with the default intent. Not because the first program is useful, but because it simplifies the rules about whether returned values can be modified without breaking patterns using the array exception today.

### Option 2: Make both programs result in compilation error

Keep the 1st program a compilation error but extend that checking to array-returning functions. To write such patterns, you would need an intermediate variable. For example

``` chapel
var array = makeInputArray(1000);
var sum = mutateAndSum(array);
```

### What about explicit return intents?

Separately, we can consider having an explicit way to opt in to or out of this checking. For example, it has been proposed that we could write `proc f() out` to return a mutable value and `proc f() const out` to produce a non-mutable value.

One concern with this approach is that it's not so clear that a function knows whether or not it's reasonable to modify the value returned. That seems more of a style issue at the call site. So how can a function author (say, writing a library) make a good choice between these options? Perhaps instead of a return intent, the call site could use an attribute on the block making the call to indicate that modifying the returned value is OK. Or, perhaps it's good enough to ask people to add a temporary variable.

### PR DESCRIPTION
**Pull request by mppf**
Resolves #22330
Resolves #20166

This PR implements Option 2 from #22330 by changing an exception in `isLegalLvalueActualArg` for arrays into an exception for array views (including slices). That makes arrays more consistent with other types while allowing code assigning to a slice, e.g., `A[2..n-1] = 1.0`, to continue to work. The rationale for having an exception for array views is 1) they are a pretty special type already and 2) they arguably behave more as a reference than a value (and in the future, might be considered a special kind of reference).

For example, here is a program that previously compiled, but after this PR fails to compile with an lvalue error:
``` chapel
proc processArr(ref X) { }
proc createArr() {
  return [1,2];
}

processArr(createArr()); // error: non-lvalue actual is passed to 'ref' formal 'X' of processArr()

```

To address this error, a user will need to add a new variable:
``` chapel
var A = createArr();
processArr(A); // OK!
```

To do so, this PR updates `isLegalLvalueActualArg` as described above and also updates the code propagating flags to promotion wrapper functions to consider `FLAG_REF_TO_CONST_WHEN_CONST_THIS`, to address an issue that was revealed in testing. While there, this PR moves the code propagating `FLAG_OPERATOR`, from `initPromotionWrapper` to `buildEmptyWrapper` (where the other flags are handled).

Reviewed by @lydia-duncan - thanks!

- [x] full comm=none testing

### CODE REVIEW

File: compiler/resolution/wrappers.cpp [hunk 1]
```diff
@@ -2710,10 +2710,6 @@ static void initPromotionWrapper(PromotionInfo& promotion,
   retval->addFlag(FLAG_PROMOTION_WRAPPER);
   retval->addFlag(FLAG_FN_RETURNS_ITERATOR);
 
-  if (fn->hasFlag(FLAG_OPERATOR)) {
-    retval->addFlag(FLAG_OPERATOR);
-  }
-
```
Comment (lydia-duncan) [inline compiler/resolution/wrappers.cpp:2716]: It'd be good to call this movement out in the PR message, but it definitely looks like an improvement

**Review by lydia-duncan — APPROVED** [review]
Minor update request to the PR message but otherwise this is great, thanks!
