### PR TITLE
Fix type of param field when initialized with literal

### LINKED ISSUE #12461: C backend error when uint-param used in array assignment
Related xx

Bug. Low priority since there's a workaround available. There's a C-backend bug when a param is type `uint` and is being used in an array assignment initializer.

```chapel
record Data {
  type pt;
  param p: pt;
}

record DataArray {
  type pt;
  param p: pt;
  
  var data: [1..10] Data(pt, p);
}

proc main() {
  // Ok
  Data(int, 42);
  Data(real, 42.1);
  Data(uint, 42:uint);
  Data(uint, 42);
  
  // Ok
  DataArray(int, 42);
  DataArray(real, 42.1);
  DataArray(uint, 42:uint);
  
  // C-backend error: incompatible types when assigning to type ...
  DataArray(uint, 42);
}
```
`chpl version 1.19.0 pre-release`

### PR DESCRIPTION
**Pull request by benharsh**
Before this PR the compiler could incorrectly map a param field to an immediate symbol of a different type. For example, a type expression that bound the value ``42`` to a ``uint`` param, but the compiler would map the field to an int(64) because that's the default value for literals.

This PR updates the compiler to coerce to a new immediate symbol when the field and value types differ, and use that new symbol in the AggregateType substitution map.

Before this PR, the test added by this PR fails with output like:
```
paramFieldType.chpl:17: In function 'dosize':
paramFieldType.chpl:18: warning: expecting 'int(8)', got 'int(64)'
paramFieldType.chpl:19: warning: expecting 'uint(8)', got 'int(64)'
paramFieldType.chpl:17: In function 'dosize':
paramFieldType.chpl:18: warning: expecting 'int(16)', got 'int(64)'
paramFieldType.chpl:19: warning: expecting 'uint(16)', got 'int(64)'
paramFieldType.chpl:17: In function 'dosize':
paramFieldType.chpl:18: warning: expecting 'int(32)', got 'int(64)'
paramFieldType.chpl:19: warning: expecting 'uint(32)', got 'int(64)'
paramFieldType.chpl:22: warning: expecting 'real(32)', got 'real(64)'
paramFieldType.chpl:17: In function 'dosize':
paramFieldType.chpl:19: warning: expecting 'uint(64)', got 'int(64)'
<gen compiler failures>
```

Resolves #12461

Testing:
- [x] local
- [x] gasnet

### CODE REVIEW

File: compiler/AST/AggregateType.cpp [hunk 1]
```diff
@@ -853,6 +853,24 @@ AggregateType* AggregateType::getNewInstantiation(Symbol* sym) {
...
+    // Sometimes 'sym' might be a different type from the field. For example,
+    // the literal '42' is an int(64), and the field might be a uint(64). In
+    // such cases, we need to coerce to a new symbol that will be placed in
+    // the substitutions map.
+    if (fieldType != NULL  &&
+        fieldType != dtUnknown &&
+        fieldType != sym->getValType()) {
+      Immediate coerce = getDefaultImmediate(fieldType);
+      Immediate* from = toVarSymbol(sym)->immediate;
+      coerce_immediate(from, &coerce);
```
Comment (lydia-duncan) [inline compiler/AST/AggregateType.cpp]: What happens if the types can't be coerced?

Comment (benharsh) [reply compiler/AST/AggregateType.cpp]: From what I can tell the compiler will fail before this point with a clean-ish error message if the param value and type are incompatible:
```
error: unresolved type specifier 'R(type uint(64), -100)'
candidates are: R(type T, param p: T)
```

Comment (lydia-duncan) [reply compiler/AST/AggregateType.cpp]: Okay, sounds good!
