### PR TITLE
Prevent modification of const ref varargs, too

### LINKED ISSUE #25901: [Bug]: `const ref` attached to vararg formal arguments allows their modification
### Summary of Problem

**Description:**
This is the remaining issue tracked by #25858 which I wasn't able to solve yet.

The individual arguments passed to a `const ref` varargs should behave the same as though they were passed to a `const ref` tuple or individually - they should trigger an error about modifying a `const` if the body of the function tries to modify them.  However, today a program that does so compiles without issue and allows modification to occur.

This was easily solved for `const` and `const in`, but `const ref` for some reason is proving more elusive.

**Is this issue currently blocking your progress?**
No, just tracking it

### Steps to Reproduce

**Source Code:**

```chapel
proc myPrintln(const ref args...)
{
  writeln("args.type     = ", args.type:string);
  writeln("args (before) = ", args);

  args[0] *= 10;  // should not be allowed

  writeln("args (after) = ", args);
}

myPrintln(1, 2.3, "four");
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A - should fail at compilation, but does not

**Associated Future Test(s):**
[`test/functions/varargs/constRefVarargs.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/functions/varargs/constRefVarargs.chpl) #25902

### Configuration Information

- Output of `chpl --version`: 2.2.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: any
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: any
- (For Cray systems only) Output of `module list`: N/A

### PR DESCRIPTION
**Pull request by lydia-duncan**
Resolves #25901 

Modifies the same place as the PRs for const and const in, but additionally needed a fix for `moveSetConstFlagsAndCheck` because the local tuple variable was using a `PRIM_GET_MEMBER_VALUE` instead of a `PRIM_GET_MEMBER` (though only in the case where it returns a ref).

Also updates a couple of tests that were impacted by the change:
- The varargs array test could reasonably be considered fulfilling the promise of the deprecation message it encountered previously.
- Futurizes the DataFrame test.  We believe it to be okay because the failure mode is accurate (we think `chpl__buildAssociativeArrayExpr` should still be generally using `const` for its varargs, and copying an owned class does modify the original) and was not caught before this change.  Add test locking in that there's an alternate way to create an associative array of owned classes that doesn't use the associative array literal syntax.  I also opened #26035 to track the future

Add tests locking in the fix for const ref.  Covers both queried and unqueried numbers of arguments.

### CODE REVIEW

**Comment by lydia-duncan** [comment]
This branch mostly works, but encounters an issue with test/library/draft/DataFrames/psahabu/HelloDataFrame.chpl when initializing the array of `owned Series?` on line 9.  The warning is occurring within `chpl__buildAssociativeArrayExpr`.  I think what's happening is that the created temporary array is const and isn't liking moving it into the named array where it will be useful to the user.  But I'm uncertain if that's a reasonable issue for it to encounter or not.  That'll probably have to wait until I'm back from vacation unless someone else wants to grab this and run with it for code freeze

File: compiler/resolution/functionResolution.cpp [hunk 1]
```diff
@@ -9599,6 +9599,7 @@ static void resolveMoveForRhsCallExpr(CallExpr* call, Type* rhsType) {
 
 static void moveSetConstFlagsAndCheck(CallExpr* call, CallExpr* rhs) {
   if (rhs->isPrimitive(PRIM_GET_MEMBER) ||
+      rhs->isPrimitive(PRIM_GET_MEMBER_VALUE) ||
```
Comment (mppf) [inline compiler/resolution/functionResolution.cpp:9602]: This function sets the LHS according to the RHS, right? (`call` is usually a `PRIM_MOVE` so `call->get(1)` would be the LHS).

In that case, I think that this conditional needs to be aware of whether or not `rhs` is a ref. That's based on this comment:

```
  // PRIM_GET_MEMBER(_VALUE): aggregate, field
  // if the field is a ref:
  //   GET_MEMBER is invalid AST
  //   GET_MEMBER_VALUE returns the reference
  // if the field is not a ref
  //   GET_MEMBER returns a reference to the field
  //   GET_MEMBER_VALUE returns the field value
```

In particular the case I am concerned about here is that the field is not a reference and it's using `PRIM_GET_MEMBER_VALUE`. In that event, the value is copied to the LHS, and the const-ness of it is unrelated to the const-ness of the field.

Comment (mppf) [reply compiler/resolution/functionResolution.cpp:9602]: (the fix might be as simple as changing this line to `(rhs->isPrimitive(PRIM_GET_MEMBER_VALUE) && rhs->get(2)->qualType().isRef()) ||` )

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp:9602]: Unfortunately that gets us right back to the basic functionality tests not working (and thus the argument getting modified in the body of the function).  Maybe the qualified type of the tuple's fields are not getting set up correctly?  The code certainly behaves like it got a reference:
```
    ref read_x0[1608172]:_ref(int(64))[1146578]
    (1608177 'move' read_x0[1608172](1608174 '.v' args[1602037] x0[1602097]))
    val elt_x0[1608179]:int(64)[10]
    unknown coerce_tmp[1608187]:int(64)[10] "dead at end of block" "coerce temp" "insert auto destroy" "temp"
    (1608191 'move' coerce_tmp[1608187](1608189 'deref' read_x0[1608172]))
```
Maybe the comment is out of date?

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp:9602]: Okay, doing the following allows the tests to behave like we want:

```
(rhs->isPrimitive(PRIM_GET_MEMBER_VALUE) && call->get(1)->qualType().isRef()) ||
```

Does that feel like it's doing what you're looking for?

Comment (mppf) [reply compiler/resolution/functionResolution.cpp:9602]: Hmm, in your example, we know `x0` is a reference, and `PRIM_GET_MEMBER_VALUE` is returning that reference. So the thing to do is figure out how to make sure the field is a reference.

Checking `call->get(1)` for ref-ness doesn't seem right to me.

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp:9602]: What if we limit it to checking if the rhsBase is a tuple?  I suspect the value access will be treated the same for all tuples and the type of the tuple's field doesn't seem to be a ref on its own

Comment (mppf) [reply compiler/resolution/functionResolution.cpp:9602]: > What if we limit it to checking if the rhsBase is a tuple? I suspect the value access will be treated the same for all tuples 

I don't think so, because we have referential and value tuples.


> and the type of the tuple's field doesn't seem to be a ref on its own

That doesn't seem right. Maybe we are just asking if it's a ref in the wrong way or it isn't a ref yet or something. See

```
ref read_x0[1608172]:_ref(int(64))[1146578]
(1608177 'move' read_x0[1608172](1608174 '.v' args[1602037] x0[1602097]))
```

The type of `read_x0` would have been inferred from the field & `.v` / `PRIM_GET_MEMBER_VALUE` would return a value if it wasn't a ref.

What happens if you try to use `call->qualType().isRef()` ? Anyway I suspect there's something wrong in my/our understanding, but I can't understand why the earlier attempts would tell it that `x0` is not a ref in this case.

Comment (lydia-duncan) [reply compiler/resolution/functionResolution.cpp:9602]: I think you mean `rhs->qualType().isRef()`?  That returns true at least

Comment (mppf) [reply compiler/resolution/functionResolution.cpp:9602]: Yes, I did mean that. In that case, we should be able to use that to filter the `PRIM_GET_MEMBER_VALUE` case to ones where the const-ness should propagate.

**Review by mppf — APPROVED** [review]
