### PR TITLE
Fix segfault for use of runtime type field

### LINKED ISSUE #10085: Nill derefernece / segfault with generic class when accepting sparse domain
Im trying to create a class that can accept either dense or sparse rectangular domains. Unfortunately this has resulted in a number of errors, key of which is that instantiating the class using a sparse domain results in come nill/null reference issues that instantiating using a dense domain does not encounter.

Bonus, the failure is different between macOS and linux.

### Steps to Reproduce

**Source Code:**
```chapel
class Map {
  type domain_type;
  var parent_domain : domain_type;
  proc init( in_domain : ?T )
  where isRectangularDom( in_domain ) || isSparseDom( in_domain )
  {
    writeln( "Creating Map(", T : string, ")" );
    this.domain_type = T;
    this.parent_domain = in_domain; // Fault happens in this statement
    writeln( this.parent_domain );
  }
}

var D : domain(2) = {1..5, 1..5 };
var sD : sparse subdomain( D );

// add some indexes into sD
for idx in D {
  if sD.size >= D.size / 2 then break;
  sD += idx;
}

var M1 = new Map( D ); // Succeeds
var M2 = new Map( sD ); // Fails
```

**Output**
On darwin (macOS)
```
Creating Map(domain(2,int(64),false))
{1..5, 1..5}
Creating Map(DefaultSparseDom(2,int(64),domain(2,int(64),false)))
Segmentation fault: 11
```

On Linux
```
Creating Map(domain(2,int(64),false))
{1..5, 1..5}
Creating Map(DefaultSparseDom(2,int(64),domain(2,int(64),false)))
$CHPL_HOME/modules/internal/ChapelArray.chpl:939: error: attempt to dereference nil
```

**macOS LLDB backtrace**
```
> chpl --ccflags "-g" ./generic_class_on_domains.chpl
> lldb ./generic_class_on_domains
(lldb) target create "./generic_class_on_domains"
Current executable set to './generic_class_on_domains' (x86_64).
(lldb) r
Process 2282 launched: './generic_class_on_domains' (x86_64)
Creating Map(domain(2,int(64),false))
{1..5, 1..5}
Creating Map(DefaultSparseDom(2,int(64),domain(2,int(64),false)))
Process 2282 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x000000010004bd8b generic_class_on_domains`dist2 + 91
generic_class_on_domains`dist2:
->  0x10004bd8b <+91>:  movq   0x38(%rdi), %rdi
    0x10004bd8f <+95>:  movq   -0x60(%rbp), %rsi
    0x10004bd93 <+99>:  movq   -0x18(%rbp), %rdx
    0x10004bd97 <+103>: movl   -0x1c(%rbp), %ecx
Target 0: (generic_class_on_domains) stopped.
(lldb) bt
* thread #2, stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x000000010004bd8b generic_class_on_domains`dist2 + 91
    frame #1: 0x000000010004bca1 generic_class_on_domains`chpl__convertValueToRuntimeType + 97
    frame #2: 0x000000010004bb37 generic_class_on_domains`chpl__initCopy2 + 87
    frame #3: 0x000000010004ba50 generic_class_on_domains`_construct_BaseSparseDom + 240
    frame #4: 0x000000010004b905 generic_class_on_domains`_construct_BaseSparseDomImpl + 213
    frame #5: 0x000000010004adc3 generic_class_on_domains`_construct_DefaultSparseDom + 275
    frame #6: 0x000000010004ab30 generic_class_on_domains`DefaultSparseDom + 1680
    frame #7: 0x000000010004a483 generic_class_on_domains`dsiNewSparseDom + 51
    frame #8: 0x000000010004a353 generic_class_on_domains`newSparseDom + 99
    frame #9: 0x0000000100048240 generic_class_on_domains`chpl__convertRuntimeTypeToValue3 + 80
    frame #10: 0x00000001000489a5 generic_class_on_domains`init_chpl12 + 661
    frame #11: 0x0000000100018c8f generic_class_on_domains`chpl__init_generic_class_on_domains + 2639
    frame #12: 0x0000000100017ebe generic_class_on_domains`chpl_gen_main + 846
    frame #13: 0x0000000100069ee6 generic_class_on_domains`chpl_executable_init + 38
    frame #14: 0x000000010006ee37 generic_class_on_domains`main_wrapper + 215
    frame #15: 0x000000010009b402 generic_class_on_domains`qthread_wrapper + 146
```

**Compile command:**
`chpl generic_class_on_domains.chpl` or `chpl --ccflags "-g" generic_class_on_domains.chp`

**Execution command:**
`./generic_class_on_domains`

### Configuration Information

**macOS**
- Output of `chpl --version`: `chpl version 1.17.1.bae434820c`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Linux**
- Output of `chpl --version`: `chpl version 1.17.1.bae434820c`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version
```
gcc (GCC) 6.3.0
```

### PR DESCRIPTION
**Pull request by benharsh**
This PR  fixes a segfault due to the compiler failing to initialize a temporary. The temporary was not initialized because the compiler erroneously used a type field's static type when it should have used the runtime type. This is easily fixed by replacing a prim-get-member with prim-get-member-value during normalization. A test is added to lock in the correct behavior.

Resolves #10085

Testing:
- [x] local + futures
- [x] gasnet over release/, distributions/, arrays/

### CODE REVIEW

**Comment by benharsh** [comment]
@lydia-duncan : would you be willing to review?

File: compiler/passes/InitNormalize.cpp [hunk 1]
```diff
@@ -1168,7 +1168,12 @@ void InitNormalize::updateFieldsMember(Expr* expr) const {
         SymExpr* _this = new SymExpr(mFn->_this);
         SymExpr* name  = new SymExpr(new_CStringSymbol(sym->name));
 
-        symExpr->replace(new CallExpr(PRIM_GET_MEMBER, _this, name));
+        if (field->sym->hasFlag(FLAG_PARAM) ||
+            field->sym->hasFlag(FLAG_TYPE_VARIABLE)) {
+          symExpr->replace(new CallExpr(PRIM_GET_MEMBER_VALUE, _this, name));
```
Comment (lydia-duncan) [inline compiler/passes/InitNormalize.cpp]: Man, we seem to do this a lot.  I wonder if there's a better way to go about it?

Definitely fine in this PR, though
