### PR TITLE
Fix compiler-generated default copy-init for unions

### LINKED ISSUE #15139: union copy initialization problem with --baseline
When compiled with `--baseline`, the below program should print out 1 but instead prints out another value (probably referring to stack trash):

``` chapel
union U {
  var x: int;
  var y: real;
}

var u1: U;
u1.x = 1;
var u2: U = u1;
writeln(u2);
```

### PR DESCRIPTION
**Pull request by mppf**
Continuing PR #14122 to fix bugs with memory management for unions.

This PR makes several changes to improve memory management for unions:
 * generate auto-destroy function for unions so e.g. a union containing a
   string has its field freed
 * only generate a zero-arguments initializer for unions for now. It
   might be reasonable to support single-argument initializers also for
   each field but that is future work per #15189.
 * adjust buildDefaultFunctions to make a good union destructor, and
   accessor
 * union accessors use return intent overloading to create two accessors.
   The accessor that supports writing to a union field will now handle
   the case that the initialized field was a different one. In that
   event, it will deinitialize the contained element and then it will
   default-initialize the appropriate field.
 * adjust buildCopyInitializer to work appropriately with the new union
   accessor
 * do not try to initialize fields for unions in initializer
   normalization

The intention of these changes is to make the compiler-generated `init`,
`init=`, and `deinit` behave appropriately for unions. In contrast,
unions with custom `init`, `init=`, or `deinit` will not correctly and
are a topic for future work (issue #15189).

Resolves #15139.

Future work:
 * totally revisit design of unions - issue #11453
 * address problems with initializers for unions - issue #15189

Reviewed by @lydia-duncan - thanks!

- [x] primers pass with verify+valgrind and do not leak
- [x] test/types/union pass with verify+valgrind and do not leak
- [x] full local futures testing

### CODE REVIEW

File: compiler/AST/AggregateType.cpp [hunk 1]
```diff
@@ -2227,42 +2227,51 @@ void AggregateType::buildDefaultInitializer() {
...
+        fn->addFlag(FLAG_METHOD_PRIMARY);
+
+        preNormalizeInitMethod(fn);
+
+        normalize(fn);
+
+        // BHARSH INIT TODO: Should this be part of normalize(fn)? If we did that
+        // we would emit two use-before-def errors for classes because of the
+        // generated _new function.
+        checkUseBeforeDefs(fn);
```
Comment (lydia-duncan) [inline compiler/AST/AggregateType.cpp]: Looks like you removed a line here but I don't think it's worse that way (just pointing it out in case you like it better the other way)

File: compiler/AST/primitive.cpp [hunk 2]
```diff
@@ -848,6 +848,7 @@ initPrimitive() {
   // As with PRIM_STATIC_TYPEOF, returns a compile-time component of
   // the type of the field.
   // There might be uninitialized memory if the run-time type is used.
+  //  variable, field name
```
Comment (lydia-duncan) [inline compiler/AST/primitive.cpp]: Was this a helper comment?

File: compiler/passes/buildDefaultFunctions.cpp [hunk 3]
```diff
@@ -307,6 +307,69 @@ static void fixupAccessor(AggregateType* ct, Symbol *field,
...
+    Symbol* newFieldNameSym = new_CStringSymbol(newField->name);
+    // Set the union ID to store the target field
+    block->insertAtTail(new CallExpr(PRIM_SET_UNION_ID,
+                                     _this,
+                                     new CallExpr(PRIM_FIELD_NAME_TO_NUM,
+                                                  ct->symbol,
+                                                  newFieldNameSym)));
+
+    // Next, initialize the requsted field.
+    VarSymbol* tmp = newTemp("union_reset_int");
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: I'd make this end with "init" rather than "int", it's a little confusing

File: compiler/passes/buildDefaultFunctions.cpp [hunk 4]
```diff
@@ -307,6 +307,69 @@ static void fixupAccessor(AggregateType* ct, Symbol *field,
...
+    Symbol* fieldNameSym = new_CStringSymbol(field->name);
+
+    CallExpr* checkId = new CallExpr("==",
+                              new CallExpr(PRIM_GET_UNION_ID, _this),
+                              new CallExpr(PRIM_FIELD_NAME_TO_NUM,
+                                           ct->symbol,
+                                           fieldNameSym));
+
+    BlockStmt* deinitBlock = new BlockStmt();
+    VarSymbol* tmp = newTemp("union_reset_dnt");
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: Maybe insert a comment that the "dnt" stands for "deinit"?  It took me a minute.  I also wouldn't object to just typing "deinit" out fully

File: compiler/passes/buildDefaultFunctions.cpp [hunk 5]
```diff
@@ -1827,10 +1899,17 @@ void buildDefaultDestructor(AggregateType* ct) {
...
+      fn->insertAtTail(buildResetUnionField(fn->_this, ct, NULL));
+    }
+
     fn->insertAtTail(new CallExpr(PRIM_RETURN, gVoid));
 
     ct->symbol->defPoint->insertBefore(new DefExpr(fn));
 
+    if (ct->isUnion()) {
+      normalize(fn);
+    }
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: Why would we only want to normalize if the new function was a union?  Shouldn't we just always normalize the functions we create in buildDefaultFunctions?

Comment (mppf) [reply compiler/passes/buildDefaultFunctions.cpp]: I don't want to change behavior for non-unions at this time. I believe that buildDefaultDestructor didn't run normalize on the function because it is so simple (consisting only of a PRIM_RETURN) that it is already normalized.

In other words - I added more code for unions in the conditional above - and that code needs to be normalized.
