### PR TITLE
Fix problem with --llvm and GASNet with MPI

### LINKED ISSUE #9097: Linking issue with LLVM and GASNet
### Summary of Problem
Linking would fail on Chapel with LLVM and GASNet support (I tested `mpi`, `ibv` and `mxm`).
Problem can be solved by passing `--ccflags "-pthread" --ldflags "-pthread -lmpi"`.

### Steps to Reproduce
```
export CHPL_HOME=/tmp/chapel
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=ibv
export CHPL_LLVM=llvm
export CHPL_WIDE_POINTERS=node16
cd $CHPL_HOME
source util/setchplenv.bash
make
```

**Compile command:**
`chpl --llvm --fast examples/hello6-taskpar-dist.chpl`

**Error message:**
```
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapAbort':
gasnet_bootstrap_mpi.c:(.text+0x12e): undefined reference to `MPI_Abort'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapFini':
gasnet_bootstrap_mpi.c:(.text+0x162): undefined reference to `MPI_Finalized'
gasnet_bootstrap_mpi.c:(.text+0x186): undefined reference to `MPI_Comm_free'
gasnet_bootstrap_mpi.c:(.text+0x199): undefined reference to `MPI_Finalize'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapAlltoall':
gasnet_bootstrap_mpi.c:(.text+0x1e4): undefined reference to `ompi_mpi_byte'
gasnet_bootstrap_mpi.c:(.text+0x1f6): undefined reference to `MPI_Alltoall'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapSNodeBroadcast':
gasnet_bootstrap_mpi.c:(.text+0x260): undefined reference to `ompi_mpi_byte'
gasnet_bootstrap_mpi.c:(.text+0x265): undefined reference to `MPI_Recv'
gasnet_bootstrap_mpi.c:(.text+0x320): undefined reference to `ompi_mpi_byte'
gasnet_bootstrap_mpi.c:(.text+0x32c): undefined reference to `MPI_Isend'
gasnet_bootstrap_mpi.c:(.text+0x369): undefined reference to `MPI_Waitall'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapBarrier':
gasnet_bootstrap_mpi.c:(.text+0x3bc): undefined reference to `MPI_Barrier'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapExchange':
gasnet_bootstrap_mpi.c:(.text+0x413): undefined reference to `ompi_mpi_byte'
gasnet_bootstrap_mpi.c:(.text+0x434): undefined reference to `MPI_Allgather'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `bootstrapBroadcast':
gasnet_bootstrap_mpi.c:(.text+0x48b): undefined reference to `ompi_mpi_byte'
gasnet_bootstrap_mpi.c:(.text+0x495): undefined reference to `MPI_Bcast'
/tmp/chapel/third-party/gasnet/install/linux64-clang-included-unknown/substrate-ibv/seg-large/nodbg/lib/libgasnet-ibv-pa
r.a(gasnet_bootstrap_mpi-PAR.o): In function `gasneti_bootstrapInit_mpi':
gasnet_bootstrap_mpi.c:(.text+0x51e): undefined reference to `MPI_Initialized'
gasnet_bootstrap_mpi.c:(.text+0x5bc): undefined reference to `MPI_Init_thread'
gasnet_bootstrap_mpi.c:(.text+0x611): undefined reference to `ompi_mpi_comm_world'
gasnet_bootstrap_mpi.c:(.text+0x616): undefined reference to `MPI_Comm_group'
gasnet_bootstrap_mpi.c:(.text+0x632): undefined reference to `ompi_mpi_comm_world'
gasnet_bootstrap_mpi.c:(.text+0x637): undefined reference to `MPI_Comm_create'
gasnet_bootstrap_mpi.c:(.text+0x649): undefined reference to `MPI_Group_free'
gasnet_bootstrap_mpi.c:(.text+0x667): undefined reference to `MPI_Comm_size'
gasnet_bootstrap_mpi.c:(.text+0x698): undefined reference to `MPI_Comm_rank'
gasnet_bootstrap_mpi.c:(.text+0x6e6): undefined reference to `MPI_Query_thread'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
error: Make Binary - Linking
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.18.0 pre-release (53a9fb1)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv *
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_ibv
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by mppf**
As described in issue #9097, when using --llvm,
the MPI library is not linked with the resulting
executable, resulting in link errors for some GASNet
configurations.

These errors don't come up without --llvm because the
GASNet Makefiles set LD to e.g. mpicxx. This commit
adjusts the --llvm support to take similar action by
saving the LD to invoke in a lib/.../override-ld file
(similarly to how list-libraries is handled) so that
make need not be invoked during a chpl --llvm compile.

This can be viewed as a follow-on to PR #7757.

Fixes #9097.

- [x] test on a Cray XC
- [x] hello compiles and runs with GASNet ibv and --llvm
- [x] full local testing

Reviewed by @dmk42 - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
@ronawho - would you be up for reviewing this bug fix for gasnet + --llvm builds ? Thanks.

**Comment by ronawho** [comment]
This is an extension/followup to https://github.com/chapel-lang/chapel/pull/5369, right?

This looks ok to me, but I don't feel particularly well qualified to review. I would imagine @dmk42 or maybe @bradcray if he has some time would be better reviewers.

**Comment by mppf** [comment]
@ronawho - this PR doesn't adjust how LD is set, it just stores it in a file and uses it in --llvm builds.

**Comment by ronawho** [comment]
> this PR doesn't adjust how LD is set, it just stores it in a file and uses it in --llvm builds.

I get that it's not changing `LD` per say, but isn't it changing the linker used for --llvm?

**Comment by mppf** [comment]
> > this PR doesn't adjust how LD is set, it just stores it in a file and uses it in --llvm builds.
> 
> I get that it's not changing `LD` per say, but isn't it changing the linker used for --llvm?

yes

**Comment by ronawho** [comment]
Ok, so to me it seems like this is just a followup on #5369, which probably makes Brad the right reviewer. That or David as the other llvm guy would be fine too.

I don't have a problem with this PR, but I don't feel like the best/right person to review. (i.e. it looks good to me, but I'm not sure I would catch any issues with it if there are any)

File: compiler/util/clangUtil.cpp [hunk 1]
```diff
@@ -2768,7 +2782,7 @@ void makeBinaryLLVM(void) {
   // Run the linker. We always use clang++ because some third-party
   // libraries are written in C++. With the C backend, this switcheroo
   // is accomplished in the Makefiles somewhere
```
Comment (cassella) [inline compiler/util/clangUtil.cpp]: Is this comment still accurate?

**Comment by dmk42** [comment]
If we want to build a module with multiple comm layers so the user can choose one at will by changing the `CHPL_COMM` environment variable, and one of those layers is GASNet, we will have multiple possible contents for the `override-ld` file.  Since the user won't be recompiling Chapel in that case, the file will be left with the contents deposited by whichever comm layer was compiled last.  I think we need a way to have multiple `LD` values that change based on `CHPL_COMM`.

**Comment by mppf** [comment]
@dmk42 - it already works that way because the override-ld file is stored in the uniquified-by-configuration lib/ directory - it would be a different subdir for different settings of CHPL_COMM.

**Comment by dmk42** [comment]
Ah, I didn't catch that.  The only other thing is that this file should be removed by a `make clean` similar to the `CLANG_SETTINGS` file.  Our Makefiles are so complicated I couldn't tell for sure, but it looks like that isn't happening.

That's the last issue I have.

**Comment by mppf** [comment]
@dmk42 - While I agree it might be reasonable to remove this file on `make clean`, it would be a significant change for other files. In particular, if I do a make in some configuration and then `make clean` or even `make cleanall`, the `lib` directory still exists and contains built things, such as libchpl.a, list-includes-and-defines, main.o (as well as override-ld).

In fact, I would expect `make clean` to totally remove the currently configured lib-runtime-subdir, in which case each of these individual files does not need special treatment  to be removed by make clean in this way. However doing so seems to be both something that requires discussion and also something that is fairly independent from this PR, so I'd like to leave it out of this PR.

**Comment by dmk42** [comment]
@mppf - It turns out that this PR broke `CHPL_LLVM=llvm` on a Mac when tests try to link to the re2 library (found with git bisect).  Here is output from a sample test.
```
['../util/start_test', '-compopts', "'--llvm'", '-compopts', '--fast', '-compopts', '--vectorize', 'release/examples/benchmarks/miniMD']
['../util/start_test', '-compopts', "'--llvm'", '-compopts', "'--fast'", '-compopts', '--vectorize', 'release/examples/benchmarks/miniMD']
['../util/start_test', '-compopts', "'--llvm'", '-compopts', "'--fast'", '-compopts', "'--vectorize'", 'release/examples/benchmarks/miniMD']

[Removing log file with duplicate name /Users/dmk/chapel/test/Logs/dmk.darwin.log
[Starting Chapel regression tests - 180418.191743]
[starting directory: "/Users/dmk/chapel/test"]
[Logs directory: "/Users/dmk/chapel/test/Logs"]
[log_file: "/Users/dmk/chapel/test/Logs/dmk.darwin.log"]
[CHPL_HOME: /Users/dmk/chapel]
[host platform: darwin]
[target platform: darwin]
[valgrind: OFF]
[performance tests: OFF]
[compiler performance tests: OFF]
[number of trials: 1]
[performance graph generation: OFF]
[compiler: "/Users/dmk/chapel/bin/darwin/chpl"]
[compopts: "--cc-warnings --llvm --fast --vectorize"]
[execopts: ""]
[launchcmd: ""]
[comm: "none"]
[localeModel: "flat"]
[numlocales: "(default)"]
[max_locales: "(default)"]
[tests: ""]
[directories: "/Users/dmk/chapel/test/release/examples/benchmarks/miniMD"]

### Chapel Environment ###
machine info: Darwin loess.dmk.com 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
CHPL_HOME: /Users/dmk/chapel *
script location: /Users/dmk/chapel/util
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib *
CHPL_GMP: system *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
##########################
[Working from directory /Users/dmk/chapel/test/release/examples/benchmarks/miniMD]

[Working on directory /Users/dmk/chapel/test/release/examples/benchmarks/miniMD]
[Starting sub_clean - Wed Apr 18 19:17:43 PDT 2018]
[pwd: /Users/dmk/chapel/test/release/examples/benchmarks/miniMD]
Cleaning directory: .
Cleaning test: ./miniMD

[Starting /Users/dmk/chapel/util/test/sub_test Wed Apr 18 19:17:43 PDT 2018]
[Starting subtest - Wed Apr 18 19:17:43 PDT 2018]
[test: release/examples/benchmarks/miniMD/miniMD.chpl]
[Executing compiler /Users/dmk/chapel/bin/darwin/chpl -o miniMD --cc-warnings --llvm --fast --vectorize -sprintCorrect=true -sprintPerf=false -M helpers miniMD.chpl < /dev/null]
[Elapsed compilation time for "release/examples/benchmarks/miniMD/miniMD (compopts: 1)" - 27.713 seconds]
[Executing diff miniMD.good miniMD.1.comp.out.tmp]
1,2c1,522
< 0 1.440000e+00 -6.773368e+00 -5.022101e+00
< 100 6.793662e-01 -5.642776e+00 7.808232e-01
---
> Undefined symbols for architecture x86_64:
>   "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::insert(std::__1::__wrap_iter<unsigned char const*>, unsigned long, unsigned char const&) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       re2::DFA::BuildAllStates(std::__1::function<void (int const*, bool)> const&) in libre2.a(dfa.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(nfa.o)
>       ...
>   "std::__1::__basic_string_common<true>::__throw_length_error() const", referenced from:
>       _qio_regexp_replace in libchpl.a(re2-interface.o)
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::trunc(re2::StringPiece const&) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libre2.a(re2.o)
>       re2::CEscape(re2::StringPiece const&) in libre2.a(strutil.o)
>       re2::PrefixSuccessor(re2::StringPiece const&) in libre2.a(strutil.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libre2.a(onepass.o)
>       ...
>   "std::__1::locale::use_facet(std::__1::locale::id&) const", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::ios_base::getloc() const", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::logic_error::logic_error(char const*)", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "std::length_error::~length_error()", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))", referenced from:
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::RE2::ReverseProg() const in libre2.a(re2.o)
>       re2::RE2::NumberOfCapturingGroups() const in libre2.a(re2.o)
>       re2::RE2::NamedCapturingGroups() const in libre2.a(re2.o)
>       re2::RE2::CapturingGroupNames() const in libre2.a(re2.o)
>       re2::RE2::DoMatch(re2::StringPiece const&, re2::RE2::Anchor, unsigned long*, re2::RE2::Arg const* const*, int) const in libre2.a(re2.o)
>       re2::RE2::Match(re2::StringPiece const&, unsigned long, unsigned long, re2::RE2::Anchor, re2::StringPiece*, int) const in libre2.a(re2.o)
>       ...
>   "std::__1::__next_prime(unsigned long)", referenced from:
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long long, int>, std::__1::__unordered_map_hasher<unsigned long long, std::__1::__hash_value_type<unsigned long long, int>, std::__1::hash<unsigned long long>, true>, std::__1::__unordered_map_equal<unsigned long long, std::__1::__hash_value_type<unsigned long long, int>, std::__1::equal_to<unsigned long long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long long, int> > >::rehash(unsigned long) in libre2.a(compile.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::erase(unsigned long, unsigned long)", referenced from:
>       re2::PrefixSuccessor(re2::StringPiece const&) in libre2.a(strutil.o)
>       re2::ToStringWalker::PostVisit(re2::Regexp*, int, int, int*, int) in libre2.a(tostring.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)", referenced from:
>       re2::trunc(re2::StringPiece const&) in libre2.a(re2.o)
>       re2::RE2::QuoteMeta(re2::StringPiece const&) in libre2.a(re2.o)
>       re2::RegexpStatus::Text() const in libre2.a(regexp.o)
>       re2::Regexp::ToString() in libre2.a(tostring.o)
>       re2::ToStringWalker::PreVisit(re2::Regexp*, int, bool*) in libre2.a(tostring.o)
>       re2::ToStringWalker::PostVisit(re2::Regexp*, int, int, int*, int) in libre2.a(tostring.o)
>       re2::AppendCCChar(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) in libre2.a(tostring.o)
>       ...
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)", referenced from:
>       re2::RE2::Rewrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::StringPiece const&, re2::StringPiece const*, int) const in libre2.a(re2.o)
>       re2::RE2::GlobalReplace(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::RE2 const&, re2::StringPiece const&) in libre2.a(re2.o)
>       re2::RE2::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) const in libre2.a(re2.o)
>       re2::StringAppendV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, char const*, __va_list_tag*) in libre2.a(strutil.o)
>       re2::RegexpStatus::Text() const in libre2.a(regexp.o)
>       re2::Regexp::RequiredPrefix(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*, re2::Regexp**) in libre2.a(regexp.o)
>       re2::ConvertLatin1ToUTF8(re2::StringPiece const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in libre2.a(parse.o)
>       ...
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char)", referenced from:
>       re2::DFA::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) in libre2.a(dfa.o)
>       re2::Regexp::RequiredPrefix(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*, re2::Regexp**) in libre2.a(regexp.o)
>       re2::AppendLiteral(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int, bool) in libre2.a(tostring.o)
>       re2::AppendCCChar(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) in libre2.a(tostring.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*)", referenced from:
>       re2::RE2::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) const in libre2.a(re2.o)
>       re2::RE2::CheckRewriteString(re2::StringPiece const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const in libre2.a(re2.o)
>       re2::DFA::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) in libre2.a(dfa.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*, unsigned long)", referenced from:
>       re2::RE2::Arg::parse_string(char const*, unsigned long, void*) in libre2.a(re2.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::resize(unsigned long, char)", referenced from:
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(bitstate.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(bitstate.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(dfa.o)
>       ...
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long)", referenced from:
>       re2::RE2::Replace(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::RE2 const&, re2::StringPiece const&) in libre2.a(re2.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::reserve(unsigned long)", referenced from:
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::RE2::QuoteMeta(re2::StringPiece const&) in libre2.a(re2.o)
>       re2::RE2::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) const in libre2.a(re2.o)
>       re2::DFA::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) in libre2.a(dfa.o)
>       re2::Regexp::SimplifyRegexp(re2::StringPiece const&, re2::Regexp::ParseFlags, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::RegexpStatus*) in libre2.a(simplify.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::push_back(char)", referenced from:
>       re2::RE2::Rewrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::StringPiece const&, re2::StringPiece const*, int) const in libre2.a(re2.o)
>       re2::RE2::QuoteMeta(re2::StringPiece const&) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(bitstate.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(dfa.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(nfa.o)
>       ...
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
>       std::__1::pair<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, void*>*, long>, bool> std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::piecewise_construct_t const&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>, std::__1::tuple<> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::piecewise_construct_t const&&&, std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>&&, std::__1::tuple<>&&) in libre2.a(regexp.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::allocator<char> const&)", referenced from:
>       re2::RE2::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) const in libre2.a(re2.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
>       re2::RE2::~RE2() in libre2.a(re2.o)
>   "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
>       re2::RE2::PossibleMatchRange(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, int) const in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(bitstate.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(dfa.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(nfa.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(regexp.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::write(char const*, long)", referenced from:
>       re2::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, re2::StringPiece const&) in libre2.a(stringpiece.o)
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()", referenced from:
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()", referenced from:
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()", referenced from:
>       LogMessage::~LogMessage() in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       LogMessage::~LogMessage() in libre2.a(onepass.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(void const*)", referenced from:
>       re2::ToStringWalker::PostVisit(re2::Regexp*, int, int, int*, int) in libre2.a(tostring.o)
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)", referenced from:
>       re2::RE2::Options::ParseFlags() const in libre2.a(re2.o)
>       re2::RE2::Match(re2::StringPiece const&, unsigned long, unsigned long, re2::RE2::Anchor, re2::StringPiece*, int) const in libre2.a(re2.o)
>       re2::RE2::Rewrite(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, re2::StringPiece const&, re2::StringPiece const*, int) const in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       re2::Prog::IsOnePass() in libre2.a(onepass.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(onepass.o)
>       re2::BitState::TrySearch(int, char const*) in libre2.a(bitstate.o)
>       ...
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned long)", referenced from:
>       re2::RE2::Match(re2::StringPiece const&, unsigned long, unsigned long, re2::RE2::Anchor, re2::StringPiece*, int) const in libre2.a(re2.o)
>   "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned short)", referenced from:
>       re2::Regexp::Destroy() in libre2.a(regexp.o)
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::sync()", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::imbue(std::__1::locale const&)", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow()", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::setbuf(char*, long)", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsgetn(char*, long)", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::xsputn(char const*, long)", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::showmanyc()", referenced from:
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       vtable for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::basic_streambuf()", referenced from:
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(onepass.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(bitstate.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(dfa.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(nfa.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(regexp.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(compile.o)
>       ...
>   "std::__1::basic_streambuf<char, std::__1::char_traits<char> >::~basic_streambuf()", referenced from:
>       LogMessage::~LogMessage() in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_stringbuf() in libre2.a(re2.o)
>       ...
>   "std::__1::ctype<char>::id", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "void std::__1::__sort<std::__1::__less<int, int>&, int*>(int*, int*, std::__1::__less<int, int>&)", referenced from:
>       re2::DFA::WorkqToCachedState(re2::DFA::Workq*, unsigned int) in libre2.a(dfa.o)
>   "std::__1::locale::~locale()", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::ios_base::__set_badbit_and_consider_rethrow()", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::ios_base::init(void*)", referenced from:
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(onepass.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(bitstate.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(dfa.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(nfa.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(regexp.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(compile.o)
>       ...
>   "std::__1::ios_base::clear(unsigned int)", referenced from:
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(dfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(nfa.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(regexp.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(compile.o)
>       ...
>   "std::__1::basic_ios<char, std::__1::char_traits<char> >::~basic_ios()", referenced from:
>       LogMessage::~LogMessage() in libre2.a(re2.o)
>       LogMessage::LogMessage(char const*, int) in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       virtual thunk to std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_ostringstream() in libre2.a(re2.o)
>       LogMessage::~LogMessage() in libre2.a(onepass.o)
>       ...
>   "std::terminate()", referenced from:
>       ___clang_call_terminate in libre2.a(re2.o)
>       ___clang_call_terminate in libre2.a(onepass.o)
>       ___clang_call_terminate in libre2.a(bitstate.o)
>       ___clang_call_terminate in libre2.a(dfa.o)
>       ___clang_call_terminate in libre2.a(nfa.o)
>       ___clang_call_terminate in libre2.a(prog.o)
>       ___clang_call_terminate in libre2.a(regexp.o)
>       ...
>   "typeinfo for std::__1::basic_ostream<char, std::__1::char_traits<char> >", referenced from:
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       ...
>   "typeinfo for std::__1::basic_streambuf<char, std::__1::char_traits<char> >", referenced from:
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "typeinfo for std::length_error", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "vtable for __cxxabiv1::__class_type_info", referenced from:
>       typeinfo for re2::Regexp::Walker<re2::Range> in libre2.a(regexp.o)
>       typeinfo for re2::Regexp::Walker<int> in libre2.a(regexp.o)
>       typeinfo for re2::Regexp::Walker<re2::Frag> in libre2.a(compile.o)
>       typeinfo for re2::Regexp::Walker<int> in libre2.a(parse.o)
>       typeinfo for re2::Regexp::Walker<re2::Regexp*> in libre2.a(simplify.o)
>       typeinfo for re2::Regexp::Walker<int> in libre2.a(tostring.o)
>   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
>   "vtable for __cxxabiv1::__si_class_type_info", referenced from:
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       typeinfo for std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       typeinfo for std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       ...
>   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
>   "vtable for std::length_error", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
>   "virtual thunk to std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()", referenced from:
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "virtual thunk to std::__1::basic_ostream<char, std::__1::char_traits<char> >::~basic_ostream()", referenced from:
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(re2.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(onepass.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(bitstate.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(dfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(nfa.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(regexp.o)
>       construction vtable for std::__1::basic_ostream<char, std::__1::char_traits<char> >-in-std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libre2.a(compile.o)
>       ...
>   "operator delete[](void*)", referenced from:
>       re2::RE2::ProgramFanout(std::__1::map<int, int, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, int> > >*) const in libre2.a(re2.o)
>       re2::RE2::DoMatch(re2::StringPiece const&, re2::RE2::Anchor, unsigned long*, re2::RE2::Arg const* const*, int) const in libre2.a(re2.o)
>       re2::SparseArray<int>::SparseArray(int) in libre2.a(re2.o)
>       re2::CEscape(re2::StringPiece const&) in libre2.a(strutil.o)
>       re2::StringAppendV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, char const*, __va_list_tag*) in libre2.a(strutil.o)
>       re2::Prog::IsOnePass() in libre2.a(onepass.o)
>       re2::SparseSetT<void>::SparseSetT(int) in libre2.a(onepass.o)
>       ...
>   "operator delete(void*)", referenced from:
>       _qio_regexp_create_compile in libchpl.a(re2-interface.o)
>       _qio_regexp_release in libchpl.a(re2-interface.o)
>       _qio_regexp_replace in libchpl.a(re2-interface.o)
>       re2::RE2::RE2(char const*) in libre2.a(re2.o)
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::RE2::RE2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(re2.o)
>       re2::RE2::RE2(re2::StringPiece const&) in libre2.a(re2.o)
>       ...
>   "operator new[](unsigned long)", referenced from:
>       re2::RE2::DoMatch(re2::StringPiece const&, re2::RE2::Anchor, unsigned long*, re2::RE2::Arg const* const*, int) const in libre2.a(re2.o)
>       re2::SparseArray<int>::SparseArray(int) in libre2.a(re2.o)
>       re2::CEscape(re2::StringPiece const&) in libre2.a(strutil.o)
>       re2::StringAppendV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, char const*, __va_list_tag*) in libre2.a(strutil.o)
>       re2::Prog::IsOnePass() in libre2.a(onepass.o)
>       re2::SparseSetT<void>::SparseSetT(int) in libre2.a(onepass.o)
>       re2::BitState::GrowStack() in libre2.a(bitstate.o)
>       ...
>   "operator new(unsigned long)", referenced from:
>       _qio_regexp_create_compile in libchpl.a(re2-interface.o)
>       _qio_regexp_replace in libchpl.a(re2-interface.o)
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::trunc(re2::StringPiece const&) in libre2.a(re2.o)
>       re2::RE2::ProgramFanout(std::__1::map<int, int, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, int> > >*) const in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const in libre2.a(re2.o)
>       std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char) in libre2.a(re2.o)
>       ...
>   "___cxa_allocate_exception", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "___cxa_begin_catch", referenced from:
>       ___clang_call_terminate in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(onepass.o)
>       ___clang_call_terminate in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(bitstate.o)
>       ...
>   "___cxa_end_catch", referenced from:
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(re2.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(re2.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(onepass.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(onepass.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(bitstate.o)
>       std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libre2.a(bitstate.o)
>       std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::overflow(int) in libre2.a(dfa.o)
>       ...
>   "___cxa_free_exception", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "___cxa_pure_virtual", referenced from:
>       vtable for re2::Regexp::Walker<int> in libre2.a(regexp.o)
>       vtable for re2::Regexp::Walker<re2::Range> in libre2.a(regexp.o)
>       vtable for re2::Regexp::Walker<re2::Frag> in libre2.a(compile.o)
>       vtable for re2::Regexp::Walker<int> in libre2.a(parse.o)
>       vtable for re2::Regexp::Walker<re2::Regexp*> in libre2.a(simplify.o)
>       vtable for re2::Regexp::Walker<int> in libre2.a(tostring.o)
>   "___cxa_throw", referenced from:
>       std::__1::vector<re2::SparseArray<int>::IndexValue, std::__1::allocator<re2::SparseArray<int>::IndexValue> >::__append(unsigned long) in libre2.a(re2.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(onepass.o)
>       std::__1::vector<int, std::__1::allocator<int> >::__append(unsigned long) in libre2.a(dfa.o)
>       void std::__1::vector<int, std::__1::allocator<int> >::__push_back_slow_path<int>(int&&) in libre2.a(dfa.o)
>       std::__1::__hash_table<re2::DFA::State*, re2::DFA::StateHash, re2::DFA::StateEqual, std::__1::allocator<re2::DFA::State*> >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::__unordered_map_hasher<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::hash<re2::DFA::State*>, true>, std::__1::__unordered_map_equal<re2::DFA::State*, std::__1::__hash_value_type<re2::DFA::State*, int>, std::__1::equal_to<re2::DFA::State*>, true>, std::__1::allocator<std::__1::__hash_value_type<re2::DFA::State*, int> > >::__rehash(unsigned long) in libre2.a(dfa.o)
>       std::__1::deque<re2::DFA::State*, std::__1::allocator<re2::DFA::State*> >::__add_back_capacity() in libre2.a(dfa.o)
>       ...
>   "___gxx_personality_v0", referenced from:
>       _qio_regexp_create_compile in libchpl.a(re2-interface.o)
>       _qio_regexp_replace in libchpl.a(re2-interface.o)
>       Dwarf Exception Unwind Info (__eh_frame) in libchpl.a(re2-interface.o)
>       re2::RE2::RE2(char const*) in libre2.a(re2.o)
>       re2::RE2::Init(re2::StringPiece const&, re2::RE2::Options const&) in libre2.a(re2.o)
>       re2::RE2::RE2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libre2.a(re2.o)
>       re2::RE2::RE2(re2::StringPiece const&) in libre2.a(re2.o)
>       ...
> ld: symbol(s) not found for architecture x86_64
> clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
> error: Make Binary - Linking
[Error matching compiler output for release/examples/benchmarks/miniMD/miniMD (compopts: 1)]
[Executing compiler /Users/dmk/chapel/bin/darwin/chpl -o miniMD --cc-warnings --llvm --fast --vectorize -sprintCorrect=true -sprintPerf=false -M helpers -suseStencilDist=true -sdefaultDoRADOpt=false miniMD.chpl < /dev/null]
```

**Comment by mppf** [comment]
@dmk42 thanks for noticing. I've made PR #9277 to fix it, would you have a look?
