### PR TITLE
Fix copy propagation errors with virtual method calls

### LINKED ISSUE #16935: Odd bug with `ref` parameter
### Summary of Problem
Getting different behavior depending on whether a call is inside a block or not.

### Steps to Reproduce

**Source Code:**

```chapel
class Base {
  proc ff(ref ipos : int) {};
}

class A : Base {
  override proc ff(ref ipos : int) {
    ipos += 1;
  }
}

var x : owned Base? = new owned A();

var ipos1 = 0;
x!.ff(ipos1);
writeln(ipos1);

// Why do I get a different answer here?
{
  var ipos = 0;
  x!.ff(ipos);
  writeln(ipos);
}
```

Running this, I get 
```
1
0
```
while I would have expected 
```
1
1
```

If I change the variable declaration to `var x : owned A? = ...`, then it works correctly. 

@e-kayrakli also pointed out on gitter that 

- compiling with `-no-copy-propagation` gets the code to work.
- writing the code as `ref iposRef = ipos;` and then using `iposRef` in the call works as well.
- 
### Configuration Information

This is chapel 1.22

### PR DESCRIPTION
**Pull request by daviditen**
Fix two places where copy propagation was mishandling virtual method calls
leading to propagating copies where it shouldn't have. Treat virtual method
calls in the same way as regular function calls when finding kills and when
looking for uses.

Add the test case from #16935.

Fixes #16935.

### CODE REVIEW

File: compiler/optimizations/copyPropagation.cpp [hunk 1]
```diff
@@ -216,6 +216,34 @@ static bool needsKilling(SymExpr* se, std::set<Symbol*>& liveRefs)
...
+    if (arg->intent == INTENT_OUT   ||
+        arg->intent == INTENT_INOUT ||
+        arg->intent == INTENT_REF   ||
+        arg->hasFlag(FLAG_ARG_THIS)) // Todo: replace with arg intent check?
+    {
+      liveRefs.insert(se->symbol());
+      return true;
+    }
+
+    if (isRecordWrappedType(arg->type))
```
Comment (e-kayrakli) [inline compiler/optimizations/copyPropagation.cpp:240]: What's the reason for this check?

If there's a special thing that we need to do w.r.t record-wrapped types, maybe we should add a test for it?

Comment (e-kayrakli) [reply compiler/optimizations/copyPropagation.cpp:240]: Ah, OK. Thanks!

**Review by e-kayrakli — APPROVED** [review]
