### PR TITLE
Avoid parsing files twice (in simple cases)

### LINKED ISSUE #13948: Files are sometimes parsed multiple times
### Summary of Problem

Given the code:

main.chpl: 
```chapel
proc main() {
  use SomeLibrary only;
  writeln(SomeLibrary.M.x);
}
```

SomeLibrary.chpl:
```chapel
module M {
  var x = 42;
}
```

compiling `chpl main.chpl SomeLibrary.chpl` results in the confusing error:

```
SomeLibrary.chpl:1: error: 'M' has multiple definitions, redefined at:
  ./SomeLibrary.chpl:1
```

This is because we parse SomeLibrary.chpl twice, hoping that it will define a module name SomeLibrary (it doesn't).  A likely fix for this would be to avoid parsing the same file twice.

### PR DESCRIPTION
**Pull request by bradcray**
This adds a check to avoid parsing the same file twice.  Doing so can result in a
single module being defined twice, resulting in a duplicate symbol definition error.

The approach taken here is to convert all paths that we parse via `realpath()`
(wrapped by the pre-existing helper `chplRealPath()`, made non-static here),
and to keep a set of these realPaths that we've parsed to avoid duplicates.

Added a test showing that this works in various ways of explicitly and implicitly
including the file twice.

While here, I improved the "Ambiguous module file" error to distinguish between
cases where the two paths being considered are really the same file using the
same chplRealPath() routine.  This avoided some warnings that occurred when
the same file was found via multiple paths (which some of the cases in my new
test hit).

Resolves #13948.

### CODE REVIEW

File: compiler/parser/parser.cpp [hunk 1]
```diff
@@ -505,11 +508,41 @@ static ModuleSymbol* parseMod(const char* modName, bool isInternal) {
...
+//
+// This is a poor person's check to see whether we've already parsed
+// this file before to avoid re-parsing the same thing twice.  It'd be
+// nice to upgrade to the C++17 filesystem library to do this, but we
+// haven't done portability testing of those features and it's close
+// to the release as I add this.  Instead, check to see whether the
+// path to the file matches one we've parsed before, adding special
+// handling to paths with the form './abc.chpl'.  This will catch
+// common cases for how we build up filenames using search paths,
+// though other cases will definitely slip past.
```
Comment (mppf) [inline compiler/parser/parser.cpp]: Our C runtime has support for this:

https://github.com/chapel-lang/chapel/blob/da7ecc219a5598b250832caa6c41961c5bf33c24/runtime/src/chpl-file-utils.c#L335-L351

It seems to me that we could call the same `realpath` function from the compiler without needing any particular C++ thing.

Comment (bradcray) [reply compiler/parser/parser.cpp]: Good idea, thanks for the pointer.  Looks like we already have a wrapper for it in the compiler as well.

**Comment by bradcray** [comment]
@mppf / @vasslitvinov: I revamped the approach here based on Michael's good suggestion to use `realPath()` and cleaned up some things while I was at it.  I think this should be re-reviewed due to the changes if one of you has time to do it (or if not, let me know and I'll solicit a new volunteer.

File: compiler/parser/parser.cpp [hunk 2]
```diff
@@ -505,14 +505,44 @@ static ModuleSymbol* parseMod(const char* modName, bool isInternal) {
...
                                bool        namedOnCommandLine) {
   ModuleSymbol* retval = NULL;
 
+  // Make sure we haven't already parsed this file
+  if (haveAlreadyParsed(path)) {
+    return NULL;
+  }
 
   if (FILE* fp = openInputFile(path)) {
-    gFilenameLookup.push_back(path);
```
Comment (mppf) [inline compiler/parser/parser.cpp]: I think it's confusing that gFilenameLookup is modified in `haveAlreadyParsed`. Could we just do the push_back here as we did before?

File: test/modules/implicit/parseTwice/main.compopts [hunk 3]
```diff
@@ -0,0 +1,7 @@
+                      # main.good
+SomeLibrary.chpl
```
Comment (mppf) [inline test/modules/implicit/parseTwice/main.compopts]: You probably know something I don't about the test system, but I don't see where the .good data would be for all these options. Is main.good reused for all of them?

Comment (bradcray) [reply test/modules/implicit/parseTwice/main.compopts]: Yeah,  it is since main.chpl is the file being compiled.  I'm not 100% sure that the comment on line 1 is strictly required, but I tend to put it on blank lines to make clear that the intention of the line is "compile via no compiler options" rather than "this is a blank line, to be skipped."

File: compiler/parser/parser.cpp (hunk 2 above)
Comment (bradcray) [reply compiler/parser/parser.cpp]: Yeah, that's a good idea.  In an intermediate version I was using gFilenameLookup for both the set and its traditional use, so it made sense to both check for updates and modify it in the same place.  Now that I've split that back out into its own set datatype (rationale: because realPaths are absolute whereas these gFilenameLookup paths are often relative and more digestible when they are), I think you're right that I should put this back where it was as well.
