### PR TITLE
Shadowing improvements

### LINKED ISSUE #15937: bugs with fields/methods and POI
Consider a record defined in a module. The record defines a field `x` or a method `x`, and some `genericMethod()` that accesses `x`. User code uses the module and also defines a method `x` on a record, then invokes the genericMethod().

When resolving genericMethod(), the user definition of `x` should be visible via genericMethod's Point of Instantiation (POI) and should conflict with the one in the module. However:

* If `x` is a field, the compiler finds neither definition.
* if `x` is a method, the compiler silently prefers the one in the module.

Here is the code with `x` --> `method` and `field`:

```chpl
use M;
proc R.method() { }
proc R.field { }
var r: R;
r.genericMethod(int);

module M {
 record R {
   proc method() { }
   var field: int;
   proc genericMethod(type t) {
     this.method();  // prefers 'proc method()' within R
     this.field;    // error: no functions named "field" found in scope
   }
 }
}
```

**Tests**:

    test/functions/generic/poi/shadowing-method.chpl
    test/functions/generic/poi/shadowing-field.chpl

### LINKED ISSUE #20509: Should user-defined field-accessors be deprecated?
Currently I can write my own field-accessor for fields in a composite type:

```chpl
record R {
  var x : int;

  proc x ref {
    writeln("R.x accessor");
    return x;
  }
}

var r : R;
r.x = 5; // prints "R.x accessor" to stdout
```

This functionality was met with some surprise/unease over on #20472, which contains some discussion concerning the value of this feature (or lack thereof).

**Should we deprecate this functionality?**

A few points made on that issue:
- ``proc x ref`` seems like something that would incur a "multiple definitions" error
- Such a method seems more appropriate to "hide" a field (e.g. ``_x`` and ``x``).
- At one time, this may have been considered a logical conclusion to the implementation of compiler-generated field-accessors, and how we resolve field accesses

Some relevant issues:
- https://github.com/chapel-lang/chapel/issues/18177
- https://github.com/chapel-lang/chapel/issues/19474
  - https://github.com/chapel-lang/chapel/pull/19505

### PR DESCRIPTION
**Pull request by mppf**
This PR takes several steps to improve the shadowing situation:
 * it adjusts the scope resolver to continue searching for more symbols unless a non-function has been found (to enable the below ambiguity error)
 * it adjusts the scope resolver to use a set instead of `isRepeat` and to consistently check for a symbol already being in the set/vector before adding it to the vector
 * it adds an ambiguity error in the scope resolver for when an Identifier could refer to both a non-operator method and a non-operator non-method. This allows us to get an error to rule out problematic cases in the near term. In the long term, this should come from disambiguation.
 * it adjusts the disambiguation process to not consider methods in `discardWorseVisibility`; methods are never discarded and their visibility level is ignored when deciding what else to discard
 * it adjusts the disambiguation process to fail if there is a mix of non-operator methods and non-operator non-methods. This is the desired behavior that we are approximating with the scope resolve error above, and as far as I know it cannot come up in practice today with the way the production compiler is implemented. However, I implemented it anyway just to make sure there are no surprises.
 * it adds a check to the frontend/ scope resolver that a field is never redefined with a parenless method with the same name.
 * it adds tests for many tricky cases that were discussed in https://github.com/Cray/chapel-private/issues/5163 #20540 and #21668.
 
 
Resolves #15937 :

* the behavior with methods was as expected
* the field example now produces a compilation error about redeclaring a field

Resolves #20509 since a parenless proc with the same name as a field now leads to a redeclaration error.

Future Work:
 * #22918
 * #23085

Reviewed by @DanilaFe - thanks!

- [x] full comm=none testing

#### Details of Specific Programs

<details>

``` chapel
// Example 5' from 21668 née 15937
record R {
  proc field { return 1; }
  var field = 2;

  proc foo() { writeln(field);} // calls the parenless proc
}

var r: R;
r.foo();
```

This PR adjusts this program to emit a redeclaration error.

``` chapel
// Example 5'' from 21668 née 15937
module Main {
  use Library;
  proc R.field { compilerWarning("In R.field"); return 8; }

  proc main() {
    var myR: R;
    myR.method();
  }
}

module Library {
  record R {
    var field = 77;
    proc method() { writeln(this.field); } // currently, error: unresolved call
  }
}
```

This PR adjusts this program to emit a redeclaration error.

``` chapel
// Example 5a (primary method variant) (based on issue 21668)
module M {
  record r {
    proc foo { writeln("in A.r.foo"); return 5; }
  }
  proc r.method() {
    var foo: int;
    foo; // is this referring to the int or the parenless method?
         // production compiler refers to the local variable
    writeln(foo); // prints out the local variable
  }

  proc main() {
    var x: r;
    x.method();
  }
}
```

This should run and print out the local variable & the PR adds a test to ensure it stays that way.

``` chapel
// Example 5a
module M {
  record r { }
  proc r.method() {
    var foo: int;
    proc r.foo { writeln("in A.r.foo"); return 23; }
    foo; // is this referring to the int or the parenless method?
         // production compiler refers to the local variable
    writeln(foo); // prints out the local variable
  }

  proc main() {
    var x: r;
    x.method();
  }
}
```

It would be OK for this to result in an ambiguity error, but it also makes sense to have it prefer `var foo`, since methods are considered only when reaching the `proc r.method` scope when going up. The PR adds it as a test & it currently prefers the variable.

``` chapel
// Example 5 from 21668
module A {
  record r { }
  proc r.foo { writeln("in A.r.foo"); }
}
module B {
  use A;
  var foo: int;

  proc r.tertiary() {
    foo; // is this A.r.foo or B.foo?
         // production compiler calls A.r.foo
  }

  proc main() {
    var x: r;
    x.tertiary();
  }
}
```

This should prefer the method, since methods are considered before global variables. The PR adds a test that it does that. Perhaps it would be OK for it to be an ambiguity, alternatively.

``` chapel
// Example 2 from 21668
module M {
  record R { }
  proc R.bar(arg: real) { writeln("in M.R.bar()"); }
  proc bar(arg: int) { writeln("in M.bar()"); }
  proc R.foo() {
    var x = 32;
    bar(x); // does it refer to M.R.bar() or M.bar() ?
  }
  proc main() { var r = new R(); r.foo(); }
}
```

This PR gets it to be an ambiguity error.

``` chapel
// Example O: shadowing-nonmethod-method.chpl from 20540
module Library {

  record R { var x: int; }

  operator +(a: R, b: R) { 
    writeln("in Library plus");
    return new R(a.x + b.x);
  }
}

module Variant {
  import Library.R;

  operator R.+(a: R, b: R) { // currently, this one is called
    writeln("in Variant plus");
    return new R(a.x + b.x);
  }
}

module Main {
  use Library;

  proc main() {
    use Variant;

    var x = new R(1);
    var y = new R(2);
    var z = x + y;

    assert(z.x == 3);
  }
}
```

The PR gets it back to an ambiguity error, after PR #20528 had it prefering one of the operators as "more visible".

</details>

### CODE REVIEW

File: compiler/passes/scopeResolve.cpp [hunk 1]
```diff
@@ -1954,11 +1994,35 @@ void lookup(const char*           name,
...
+// Continue searching if we have found a method.
+static bool shouldStopSearch(llvm::SmallVectorImpl<Symbol*>& symbols) {
+  for (Symbol* sym : symbols) {
+    if (!isParenfulFn(sym)) {
+      // found parenless fn or type or var or ...
+      return true;
+    }
+  }
+  return false;
 }
```
Comment (DanilaFe) [inline compiler/passes/scopeResolve.cpp:2023]: Reading the PR in order (and thus not yet having seen uses for shouldStopSearch) makes me think this is quadratic. After every so often, we will stop and re-run the check on `symbols`? But "every so often" continues as we find more symbols to insert? 

I suppose it might be negligible in the long term (how many overloaded symbols are there really?), but if it becomes a problem I suspect keeping a boolean together with the `symbols` (via some sort of struct, maybe), and updating the flag with each insertion, would be more efficient.

File: compiler/passes/scopeResolve.cpp [hunk 2]
```diff
@@ -2304,17 +2394,16 @@ static void lookupUseImport(const char*           name,
...
                     renameLocs[sym] = &use->astloc;
                   }
                 }
 
-              } else if (isRepeat(sym, symbols) == false) {
-                symbols.push_back(sym);
-                if (storeRenames && use->isARenamedSym(name)) {
+              } else {
+                bool added = saveSymbol(sym, symbols, foundSymsSet);
+                if (added && storeRenames && use->isARenamedSym(name)) {
```
Comment (DanilaFe) [inline compiler/passes/scopeResolve.cpp:2406]:
```suggestion
              } else if (saveSymbol(sym, symbols, foundSymsSet)) {
                if (storeRenames && use->isARenamedSym(name)) {
```

File: compiler/passes/scopeResolve.cpp [hunk 3]
```diff
@@ -2345,16 +2435,15 @@ static void lookupUseImport(const char*           name,
...
+                  if (added && storeRenames && import->isARenamedSym(name)) {
                     renameLocs[sym] = &import->astloc;
                   }
                 }
-              } else if (isRepeat(sym, symbols) == false) {
-                symbols.push_back(sym);
-                if (storeRenames && import->isARenamedSym(name)) {
+              } else {
+                bool added = saveSymbol(sym, symbols, foundSymsSet);
+                if (added && storeRenames && import->isARenamedSym(name)) {
```
Comment (DanilaFe) [inline compiler/passes/scopeResolve.cpp:2446]: Ditto here about keeping the else-if.

File: doc/rst/language/spec/methods.rst [hunk 4]
```diff
@@ -509,3 +509,6 @@ keyword (see :ref:`Overriding_Base_Class_Methods`).
 Note that class methods without parentheses that return with ``type`` or
 ``param`` intent use a generic type for the ``this`` argument. See
 :ref:`Class_Methods` for more details.
+
+It is a redeclaration error to define a method without parenthesis with
+the same name as a field.
```
Comment (DanilaFe) [inline doc/rst/language/spec/methods.rst:514]:
```suggestion
It is a redeclaration error to define a method without parentheses with
the same name as a field.
```

File: frontend/lib/resolution/resolution-queries.cpp [hunk 5]
```diff
@@ -412,6 +412,30 @@ static ID parentFunctionId(Context* context, ID functionId) {
...
+      if (receiverType.type()) {
+        // use the type information, if it is present
+        if (auto ct = receiverType.type()->getCompositeType()) {
+          receiverId = ct->id();
+        }
+      }
+      if (!receiverId.isEmpty()) {
+        if (parsing::idContainsFieldWithName(context, receiverId, fn->name())) {
+          context->error(fn, "parenless proc redeclares the field '%s'",
+                         fn->name().c_str());
```
Comment (DanilaFe) [inline frontend/lib/resolution/resolution-queries.cpp:432]: It would be nice if this were a full-style Dyno error someday. Doesn't have to be in this PR, though.

File: test/functions/generic/poi/shadowing-method.good [hunk 6]
```diff
@@ -1,3 +1,4 @@
-<The desired output should indicate an ambiguous error
-between MyRecord.method definitions on Lines 4 and 17.
-Maybe even an Overloading Sets error.>
+shadowing-method.chpl:21: In method 'genericMethod':
+shadowing-method.chpl:22: warning: in Library.MyRecord.method
+  shadowing-method.chpl:10: called as MyRecord.genericMethod(type t = int(64))
+shadowing-method.chpl:9: error: in Main.main, done
```
Comment (DanilaFe) [inline test/functions/generic/poi/shadowing-method.good:4]: I have no idea what this error message means.

File: test/functions/resolution/errors/testBadCallCandidates.chpl [hunk 7]
```diff
@@ -1,5 +1,5 @@
 config param testNum = 1;
-
+/* Note: some cases commented-out due to stopgap scope resolver ambiguity */
```
Comment (DanilaFe) [inline test/functions/resolution/errors/testBadCallCandidates.chpl:2]: It would be good to note this change on some issue or somewhere to make sure we come back to this test to uncomment the cases.

File: test/functions/generic/poi/shadowing-method.good (hunk 6 above)
Comment (mppf) [reply test/functions/generic/poi/shadowing-method.good:4]: the test itself has compilerWarning and compilerError calls that generate this output

File: compiler/passes/scopeResolve.cpp (hunk 2 above)
Comment (mppf) [reply compiler/passes/scopeResolve.cpp:2406]: I like the way I had it better because it explains what the result of `saveSymbol` means (it was added)

Comment (mppf) [reply compiler/passes/scopeResolve.cpp:2406]: I am not seeing any advantage to keeping the `else if` here, and it seems to be a purely stylistic choice.

File: test/functions/resolution/errors/testBadCallCandidates.chpl (hunk 7 above)
Comment (mppf) [reply test/functions/resolution/errors/testBadCallCandidates.chpl:2]: I've created #23085 to track this future work and to note that this test should change when it is complete.

File: compiler/passes/scopeResolve.cpp (hunk 1 above)
Comment (mppf) [reply compiler/passes/scopeResolve.cpp:2023]: Good point. I've added a comment about this strategy, to pursue in the event that loop becomes a performance problem.

File: compiler/passes/scopeResolve.cpp [hunk 8]
```diff
@@ -1831,11 +1835,47 @@ void checkConflictingSymbols(llvm::SmallVectorImpl<Symbol *>& symbols,
...
+          USR_STOP();
+        }
+        if (isNonMethod && foundMethod) {
+          USR_FATAL_CONT(context,
+                         "currently ambiguous what '%s' refers to", name);
+          USR_PRINT(foundMethod, "found this method");
+          USR_PRINT(sym, "and this non-method");
+          USR_STOP();
+        }
+      }
```
[the remark this answers is not in the document]
Comment (mppf) [reply compiler/passes/scopeResolve.cpp]: This seems like a good simplification & I've given it a try. Will see if testing reveals any issue.

[the remark this answers is not in the document]
Comment (mppf) [reply compiler/passes/scopeResolve.cpp]: Works just fine after I fix a typo in the error message :)

**Review by DanilaFe — APPROVED** [review]
