### PR TITLE
Fix a compiler assert

### LINKED ISSUE #18218: Internal error RES-LOW-ORS-1902 related to Errors and recursive iterators?
### Summary of Problem

I was trying to rework `test/library/packages/Curl/check-http.chpl` to
handle errors in order to ensure the server is stopped when an Error
is thrown.  I found an internal error, which I was able to narrow
down:

### Steps to Reproduce

**Source Code:**

```chapel
module CheckHttp {
  use FileSystem;
  use IO;

  proc main() throws {
    for f in findfiles() {
      var filereader = open(f, iomode.r).reader();
    }
  }
}
```

```
check-http.chpl:21: internal error: assertion error [resolution/lowerIterators.cpp:1902]
```

or

```
> check-http.chpl:22: internal error: RES-LOW-ORS-1902 chpl version 1.25.0 pre-release (31330febf2)
```

which is

```

// Return an appropriate IBB insertion point for an outbound goto 'gt'.
// 'loopRef' is the forLoop or its copy for lowering, whichever is inTree().
// 'IC' is the forLoop's _iteratorClass, or NULL if lowering a ForallStmt.
//
static Expr* ibbInsertPoint(Expr* loopRef, Symbol* IC, GotoStmt* gt) {
  DefExpr* gtTarget = toSymExpr(gt->label)->symbol()->defPoint;
  // Sanity: the goto's target is in the forLoop's function.
  INT_ASSERT(gtTarget->parentSymbol == loopRef->parentSymbol);
```

Both the loop over `findfiles()` and opening a file within it are
necessary.  A loop over `("foo", "bar")` doesn't trigger it, nor an
empty loop over `findfiles()`, nor just a call to `open()` with no
loop.

**Associated Future Test(s):**
[`test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl
          ) #18252 

### Configuration Information

```
chpl version 1.25.0 pre-release (31330febf2)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: unset [ built with CHPL_LLVM=none ]
CHPL_AUX_FILESYS: none

gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
```

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #18218.

A loop over a recursive iterator used to trigger an assertion failure in the compiler when the loop body contained a call to a throwing function. This PR makes the compiler handle that case using a heuristic solution.

Adds a beefed-up reproducer from 18218 and de-futurizes a test filed previously for 18218.

### CODE REVIEW

File: compiler/resolution/lowerIterators.cpp [hunk 1]
```diff
@@ -1907,6 +1905,27 @@ replaceErrorFormalWithEnclosingError(SymExpr* se) {
...
+static void adjustIbbGotoTarget(GotoStmt* gt, DefExpr*& gtTarget,
+                                Expr* loopRef) {
+  // Normally, the goto's target is in the forLoop's function.
+  if (gtTarget->parentSymbol == loopRef->parentSymbol)
+    return;
+
+  // If this is not for a recursive iterator, let us know.
+  INT_ASSERT(!strncmp(loopRef->parentSymbol->name, "_rec_", 5));
+
+  LabelSymbol* redirect = ((FnSymbol*)(loopRef->parentSymbol))->
```
Comment (dlongnecke-cray) [inline compiler/resolution/lowerIterators.cpp:1921]: Is there any time this cast could break? Could we do a `toFnSymbol()` instead just to have it crash if that's not the case?

**Review by dlongnecke-cray — APPROVED** [review]
Looks good to me sans a C cast I felt hesitant about.
