### PR TITLE
Minor nilability fixes

### LINKED ISSUE #11305: enable compile-time nil checking for internal modules
To make it easier to get started with the implementation, the compile-time nil checking added in PR #11238 ignores internal modules. The TODO here is to make it apply to internal modules.

### LINKED ISSUE #13601: Misleading error upon returning a nilable
The compiler is correct in reporting an error, however the error text needs to be clearer:
```chpl
class MyClass {var x:int;}

var global: owned MyClass?;

proc myFun(): owned MyClass {
  return global;  // error: returning a nilable
                  //  when the return type is non-nilable
}

var result3 = myFun();
```

I get:
```
test.chpl:6: error: Cannot default-initialize <temporary>
note: non-nil class types do not support default initialization
note: Consider using the type _owned(MyClass)? instead
```

### LINKED ISSUE #13632: Spurious "cannot default-initialize" error
A mismatch of type instantiations causes a spurious and misleading error "cannot default-initialize":

```chpl
class MyClass {
  var x;
}

var a: borrowed MyClass(real) = new borrowed MyClass(1);
```

Luckily, the desired "cannot assign" error is also issued.

The same thing happens upon `var x: borrowed CHILD = new borrowed PARENT();`

This issue prevents the following tests from passing with `--no-legacy-nilable-classes` :

    test/classes/initializers/generics/explicitAssignment.chpl
    test/classes/marybeth/test_dispatch1-error.chpl

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #13632. Resolves #13601. Resolves #11305. Resolves https://github.com/Cray/chapel-private/issues/415.

* Enable compile-time nil checking for internal modules
  that was initially disabled in #11238.

* Adjust comments in DecoratedClassType.h,cpp .

* Remove an unnecssary postfix`!` in ChapelLocale.chpl.

* Add newly-created DecoratedClassTypes to `gDecoratedClassTypes`.

* Make `new C()?` return a nilable owned C.

### CODE REVIEW

File: compiler/resolution/functionResolution.cpp [hunk 1]
```diff
@@ -6752,9 +6752,20 @@ static void resolveNewSetupManaged(CallExpr* newExpr, Type*& manager) {
...
+        break;
       }
     }
   }
+
+  // adjust for the cases like 'new C()?'
+  if (manager == NULL) {
+    if (SymExpr* arg1 = toSymExpr(newExpr->get(1)))
+      if (DecoratedClassType* dt1 = toDecoratedClassType(arg1->symbol()->type))
+        if (dt1->getDecorator() == CLASS_TYPE_GENERIC_NILABLE)
```
Comment (mppf) [inline compiler/resolution/functionResolution.cpp]: Why does this only check for GENERIC_NILABLE? It would make more sense to me if it checked for any CLASS_TYPE_GENERIC.

File: compiler/resolution/functionResolution.cpp [hunk 2]
```diff
@@ -6752,9 +6752,20 @@ static void resolveNewSetupManaged(CallExpr* newExpr, Type*& manager) {
...
+          newExpr->insertAtHead(dtOwned->symbol), gdbShouldBreakHere();
```
Comment (mppf) [inline compiler/resolution/functionResolution.cpp]: You probably meant to remove the breakpoint

File: compiler/resolution/functionResolution.cpp (hunk 1 above)
Comment (vasslitvinov) [reply compiler/resolution/functionResolution.cpp]: In the case `new C()?` I am observing CLASS_TYPE_GENERIC_NILABLE. In what situations would other GENERIC variants occur?

Let me leave it this way for now. We will adjust once we decide what to do about this kind of expression on #13619.
