### PR TITLE
Fix munging with LLVM

### LINKED ISSUE #14473: export proc empty does not compile
``` chapel
export proc empty() { }
empty();
```

does not compile, with C backend errors.

### PR DESCRIPTION
**Pull request by mppf**
Continues #14513.
Resolves #14473.

The main fix here replaces a use of `name` with `cname` for string 
literals. The issue was that the string literal cname was being munged,
but the LLVM-specific string literal code generation was looking under
the un-munged name.

Additionally, added some helper functions for use when debugging the 
compiler with LLVM.

- [x] full local --llvm testing

Reviewed by @bradcray - thanks!

### CODE REVIEW

**Comment by mppf** [comment]
@bradcray - this is arguably trivial but would you be available to give it a review? Fixes the munging problem with --llvm. Thanks.

File: compiler/codegen/codegen.cpp [hunk 1]
```diff
@@ -1235,16 +1235,6 @@ static void protectNameFromC(Symbol* sym) {
...
-  //
-  // For reasons not clear to me, renaming internal module symbols
-  // when LLVM is being used causes problems, so let's not do it for
-  // now.
-  //
-  ModuleSymbol* symMod = sym->getModule();
-  if (llvmCodegen && symMod->modTag == MOD_INTERNAL) {
-    return;
-  }
-
```
Comment (bradcray) [inline compiler/codegen/codegen.cpp]: Sweet, thanks!  (still reviewing)

**Comment by bradcray** [comment]
Would you also test that removing `test/interop/fortran/genFortranInterface/unhandledType.suppressif` causes that test to work with `--llvm` again, and if so, remove it?  It ended up going into a later PR because I only caught the failure after the nightly had run.

You can also add a "Resolves #14473." to this PR's description (I re-opened it after resolving it once I realized `--llvm` was broken).

Thanks again for grabbing this!
