### PR TITLE
Extend cases where `super` can be used in an `import` statement

### LINKED ISSUE #15309: `import super.x` can't refer to a member `x`, only module `x`.
### Summary of Problem

At present, it seems that `import super.x` can't be used to refer to a variable `x` in a parent module, only to a module `x` in that parent module.  This seems like a likely oversight in the implementation (?).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/import/superDotVar.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/superDotVar.chpl
          ) #15307 
[`test/visibility/import/superDotSuperDotVar.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/superDotSuperDotVar.chpl
          ) #15307

### Configuration Information

- Output of `chpl --version`: `1.21.0 pre-release (52b68d036f)`

### PR DESCRIPTION
**Pull request by lydia-duncan**
Prior to this change, `import super.foo;` would only work if foo was a module.
However, import statements are allowed to indicate a single symbol within a
module for unqualified access, and since we require an import or use of parent
modules to access their symbols now, it makes sense to enable a faster way of
indicating a symbol in the parent module (by using `super` instead of the full
module path).

This change also allows `import super.{foo};` and `import super;` (unless the
module with the import is already at the top-level).

Resolves #15309

Test updates
-------------
- Removes 3 .future and .bad files.
- Adds a test of the curly bracket variant.
- Updates the expected behavior for what was import-relative-error6.chpl and
renames it now that it is no longer expected to be an error.

Passed a full paratest with futures

### CODE REVIEW

**Comment by lydia-duncan** [comment]
Current failures:
[Error matching compiler output for visibility/import/public/no-param-import]
[Error matching program output for visibility/import/relative/import-relative-error1]
[Error matching compiler output for visibility/import/no-param-import]

All of these are actual failures that need to be fixed

File: compiler/passes/ResolveScope.cpp [hunk 1]
```diff
@@ -650,9 +650,15 @@ Symbol* ResolveScope::lookupForImport(Expr* expr, bool isUse) const {
...
-        else
+        else if (relativeScope == NULL || relativeScope == this)
           USR_FATAL(expr, "import must name a module ('%s' is not a module)",
-                          sym->name);
+                    sym->name);
+        else {
+          // It's okay for the symbol following a super to not be a module, so
+          // long as it is the last symbol in the import statement...
+          retval = sym;
+          break;
```
Comment (mppf) [inline compiler/passes/ResolveScope.cpp:660]: Is there a test of `import super.Mod.super.SubMod.x` ? Should we see an error there, or is it supposed to work? It's not clear to me that this code handles that case correctly so I'd appreciate it if you can add a test / find one that exists.

File: test/visibility/import/superDotVar2.chpl [hunk 2]
```diff
@@ -0,0 +1,11 @@
+module M {
+  var x = 42;
+
+  module N {
+    import super.{x};
```
Comment (mppf) [inline test/visibility/import/superDotVar2.chpl:5]: Can you make this list 2 variables just for better coverage?

File: compiler/passes/ResolveScope.cpp (hunk 1 above)
Comment (lydia-duncan) [reply compiler/passes/ResolveScope.cpp:660]: It looks like there isn't already a test of this so far as I can see.  In terms of what it should do, I would be okay with it working for the following hierarchy:
```chapel
module M {
  module Mod { ... }
  module SubMod {
     var x: int;
  }
  module User {
    import super.Mod.super.SubMod.x;
    proc main() {
      writeln(x);
    }
  }
}
```
but would also be okay with it not working, since that's not really a clear path for people reading the code.  As written, I think it's pretty similar to `../Mod/../SubMod` in file paths and that's something that's allowed generally.

What actually happens is that we get `error: Cannot find symbol 'super' in module 'Mod'`, it looks like due to looking for the name "super" in the module.  This is not changed by my branch, it behaves the same on master - if we want it to work, I think that should be a separate PR
