### PR TITLE
Fix a uAST conversion bug that incorrectly converted some array types

### LINKED ISSUE #18717: 'borrowed' keyword applied to an array crashes the compiler
### Summary of Problem

Trying to declare a `borrowed` array causes an internal compiler error (AST-EXP-0299).

### Steps to Reproduce

**Source Code:**

```chapel
record Chunk {
  type eltType;
  var D: domain(1);
  var data: borrowed [D] eltType;

  proc init(type eltType) {
    this.eltType = eltType;
  }

  proc init(array: [?X] ?t) {
    this.eltType = t;
    this.D = X;
    this.data = array;
  }
}

proc main()
{
  var x = new Chunk([1, 2, 3]);
}
```

**Compile command:**
`chpl -o error error.chpl`

### Configuration Information

- Output of `chpl --version`: 1.25.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc 11.2.0

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
Resolves #18717.

Fixes a bug which caused an array type preceded by the `borrowed` keyword to be incorrectly transformed into a loop. This led to internal errors when the loop was queried for its type information.

At a syntactic level, array types and loops are indistinguishable. However, in type-only contexts (such as for formal types, or for return types) we can always convert a "loop" into an array type. This PR adjusts the uAST converter so that it can handle converting array types at arbitrary depths. This covers array types that follow the `borrowed` keyword (which is represented as a "call").

TESTING

- [x] `linux64`, `standard`
- [x] `linux64`, `COMM=gasnet`

Reviewed by @mppf, @vasslitvinov. Thanks!

### CODE REVIEW

File: compiler/passes/convert-uast.cpp [hunk 1]
```diff
@@ -3727,7 +3712,6 @@ struct Converter {
 
       // If there is a type query, extract it from the domain.
       if (lastTypeQuery) {
-        CHPL_ASSERT(isFormalType);
```
Comment (mppf) [inline compiler/passes/convert-uast.cpp:3730]: Could/should this be replaced by `CHPL_ASSERT(inTypeExpression)` ?

**Review by mppf — APPROVED** [review]
Looks like you removed some code duplication in convert-uast as well!

**Review by vasslitvinov — APPROVED** [review]

File: compiler/passes/convert-uast.cpp (hunk 1 above)
Comment (dlongnecke-cray) [reply compiler/passes/convert-uast.cpp:3730]: I think that assert was just checking that we only convert type queries in formal types. Since we already check for that in post-parse-checks I'm not too worried.
