### PR TITLE
Overloaded INT_ASSERT

### LINKED ISSUE #10152: Should INT_ASSERT() take an optional AST to indicate source location?
When INT_ASSERT()s are triggered, it seems to take extra work to figure out where things went wrong.  It seems as though if there were a two-argument overload where one argument was an AST source location (as with INT_FATAL, USR_FATAL, etc.) we'd get more information out when assertions were triggered (though we'd also have to train people to try and write INT_ASSERT()s in the two-argument form.

### PR DESCRIPTION
**Pull request by chris980**
Added a variadic selector for different number of parameters for INT_ASSERT.

[chapel-lang/10152](https://github.com/chapel-lang/chapel/issues/10152)

Resolves #10152.

### CODE REVIEW

File: compiler/include/misc.h [hunk 1]
```diff
@@ -70,7 +70,10 @@
 #define USR_STOP       exitIfFatalErrorsEncountered
 
 // INT_ASSERT is intended to become no-op in production builds of compiler
-#define INT_ASSERT(x) do { if (!(x)) INT_FATAL("assertion error"); } while (0)
+#define SELECT_ASSERT(_1, _2, NAME) NAME
+#define INT_ASSERT(...) SELECT_ASSERT(__VA_ARGS__, INT_ASSERT2, INT_ASSERT1)(__VA_ARGS__)
+#define INT_ASSERT1(x) do { if (!(x)) INT_FATAL("assertion error"); } while (0)
+#define INT_ASSERT2(x, s) do { if (!(x)) INT_FATAL((s), "assertion error"); } while (0)
```
Comment (bradcray) [inline compiler/include/misc.h]: Thanks for tackling this, @chris980!

I think that most of the USR/INT macros take the source location as their first optional argument and then the stuff that's specific to the macro after that, so would suggest swapping the order of s and x.

I'm also trying to think how to test this...  I wonder if we could find any tests in the test system whose .bad files have internal assertion failures, and if so, whether they would be candidates for attaching a location like this...

**Comment by chris980** [comment]
Hi Brad,

I think the only file that produces a failing assert is [setDestructors.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/Set/destructors/setDestructors.chpl)

**Comment by bradcray** [comment]
Unfortunately, that assert is caused by the `assert()` within the test itself (a user-level assertion that's part of the Chapel library) whereas your efforts are about the internal-to-the-compiler INT_ASSERT() that's for assertions within the implementation of the language.  I'm doing a quick check myself to see if I can find any cases that hit it...

It looks like these two tests do (or at least, did) generate INT_ASSERT() failures, but don't have `.bad` files to compare against.  It also looks like they've suffered some bitrot.  Let me look into them a bit more and see whether they could be used to lock in this behavior.

**Comment by bradcray** [comment]
> Let me look into them a bit more and see whether they could be used to lock in this behavior.

Hmm, not easily.  For better or worse, the assertions they were running into aren't being triggered anymore.

Let me think a bit more about how we could lock in a test this (short of modifying the compiler to introduce an arbitrary assertion), or if you have thoughts about it, let me know.  (Having such a test isn't a necessity but would be the best way to ensure it works and guard against it breaking in the future).

File: compiler/include/misc.h [hunk 2]
```diff
@@ -70,7 +70,10 @@
 #define USR_STOP       exitIfFatalErrorsEncountered
 
 // INT_ASSERT is intended to become no-op in production builds of compiler
-#define INT_ASSERT(x) do { if (!(x)) INT_FATAL("assertion error"); } while (0)
+#define SELECT_ASSERT(_1, _2, NAME) NAME
+#define INT_ASSERT(...) SELECT_ASSERT(__VA_ARGS__, INT_ASSERT2, INT_ASSERT1)(__VA_ARGS__)
+#define INT_ASSERT1(x) do { if (!(x)) INT_FATAL("assertion error"); } while (0)
+#define INT_ASSERT2(s, x) do { if (!(x)) INT_FATAL((s), "assertion error"); } while (0)
```
Comment (cassella) [inline compiler/include/misc.h:76]: I don't believe this will work if the two-arg form of `INT_ASSERT()` is used.  Have you tested that?

Comment (chris980) [reply compiler/include/misc.h:76]: I did not test it because I couldn't find that assertion in the tests. It seems like it's not being triggered anywhere. I think I would have to introduce it arbitrary in one of the existing tests, or create a new one, but I don't know where.

Comment (bradcray) [reply compiler/include/misc.h:76]: Hi @chris980: I haven't come up with a good way to test this feature in the nightly testing (the question I was wrestling with in my previous comments), but I think for the sake of Paul's comment, inserting a call to your INT_ASSERT() somewhere into the code base where it would get called to make sure it works as intended is all that would be required (and then, having verified that it works, back that change back out again rather than committing it).

For example, compiling `chpl test/classes/ferguson/generic-inherit6.chpl --verify --devel` should hit an internal error at [line 202 of `compiler/AST/CallExpr.cpp`](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/CallExpr.cpp#L201-L203).  If you replace that INT_FATAL() with an INT_ASSERT(), rebuild the compiler, and rerun the test, does your INT_ASSERT() work as intended?

Comment (chris980) [reply compiler/include/misc.h]: Hi @bradcray , 

Thank you for the help. 
@cassella was right, the two-arg form was not working, but I fixed it.

After modifying [`compiler/AST/CallExpr.cpp`](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/CallExpr.cpp#L201-L203), it produces the expected result: `test/classes/ferguson/generic-inherit6.chpl:13: internal error: assertion error [AST/CallExpr.cpp:202]`

Comment (bradcray) [reply compiler/include/misc.h]: @chris980: For some reason, after checking out your branch, I don't seem to be able to reproduce this.  Am I doing something wrong?  My diff to CallExpr.cpp is:

```diff
index 0fbdc24f0b..e40bc9c837 100644
--- a/compiler/AST/CallExpr.cpp
+++ b/compiler/AST/CallExpr.cpp
@@ -198,9 +198,12 @@ void CallExpr::verify() {
 
   Expr::verify(E_CallExpr);
 
+  INT_ASSERT(this, parentExpr == NULL);
+  /*
   if (parentExpr == NULL) {
     INT_FATAL(this, "Every CallExpr is expected to have a parentExpr");
   }
+  */
```

but the output I get is:

```
internal error: assertion error [AST/FnSymbol.cpp:102]
```

(note the lack of pointer to the user's source location)

Comment (cassella) [reply compiler/include/misc.h]: I think you mean `parentExpr != NULL`, since you're asserting it, not FATAL'ing if it's true.

The error you're getting is from a different file, I'm guessing because the assert didn't trigger so you reached different code.

Comment (cassella) [reply compiler/include/misc.h]: That line if that other file is an `INT_FATAL`, not an `INT_ASSERT`, so I'm guessing you converted that one the same way.  If I reverse the test on that `INT_FATAL`, the existing `INT_FATAL(this, ...)` also fails to print a user source location.  So I think the lack of a user location in that one has something to do with the `this` in that path,

Comment (bradcray) [reply compiler/include/misc.h]: Ah, you're right, good sleuthing Paul.  I'd originally tried modifying AST/Symbol.cpp just to test something different than @chris980, didn't get the expected result, so tried the case above, but without reverting my original change.  Doing that, and fixing the polarity of my assert, I get the expected output.

(I'm still a little confused by my original test, though... I got to it by finding a test case that generated an internal error which I thought had source information associated with it; and on that one, I did think to reverse the polarity of the boolean expression.  It seems likely I got something wrong, but I'm not sure what...).
