### PR TITLE
Fix memory leak caused by use of first class functions

### LINKED ISSUE #7890: First-class functions leak
### Summary of Problem
First class functions always leak:
```chpl
proc bar() {
  writeln("in bar!");
}

proc foo(f) {
  f();
}

foo(bar);
```
```
> ./a.out --memLeaksByType
in bar!

====================
Leaked Memory Report
==============================================================
Number of leaked allocations
           Total leaked memory (bytes)
                      Description of allocation
==============================================================
1          4          _chpl_fcf_0_bar
==============================================================
```

List of tests that leak primarily due to first-class function usage:
- [x] [fun_as_value.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value.chpl)
- [x] [fun_as_value.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/jturner/fun_as_value.chpl)
- [x] [fun_ret_class.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_ret_class.chpl)
- [x] [spec-test_dropWhile.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_dropWhile.chpl)
- [x] [spec-test_foldLeft.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_foldLeft.chpl)
- [ ] [Grid_DiffusionBE_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/diffusion/grid/Grid_DiffusionBE_driver.chpl)
- [ ] [AMR_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/amr/AMR_AdvectionCTU_driver.chpl)
- [ ] [spec-test_map.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_map.chpl)
- [ ] [fun_type_annot_int_void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_int_void.chpl)
- [ ] [fun_as_value_multiarg_mixed.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_multiarg_mixed.chpl)
- [ ] [exitWithNoCall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exits/albrecht/exitWithNoCall.chpl)
- [ ] [passFnsToCChapel2x.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel2x.chpl)
- [ ] [Level_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/level/Level_AdvectionCTU_driver.chpl)
- [ ] [spec-test_filter.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_filter.chpl)
- [ ] [fun_type_annot_single.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_single.chpl)
- [ ] [Level_DiffusionBE_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/diffusion/level/Level_DiffusionBE_driver.chpl)
- [ ] [fun_tuple_arg.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_tuple_arg.chpl)
- [ ] [fcf-rettype-void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-rettype-void.chpl)
- [ ] [spec-test_takeWhile.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_takeWhile.chpl)
- [ ] [exitWithNoParensNoArgs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exits/sungeun/exitWithNoParensNoArgs.chpl)
- [ ] [fun_as_value_crossmodule.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_crossmodule.chpl)
- [ ] [passFnsToCChapel2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel2.chpl)
- [ ] [storeFnsThenPass2x.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/storeFnsThenPass2x.chpl)
- [ ] [fun_duplicate_values.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_duplicate_values.chpl)
- [ ] [storeFnsThenPass.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/storeFnsThenPass.chpl)
- [ ] [fcf-defaultInit.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/fcf-defaultInit.chpl)
- [ ] [retType.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/sungeun/retType.chpl)
- [ ] [fun_as_value_default.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_default.chpl)
- [ ] [spec-test_foldRight.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_foldRight.chpl)
- [ ] [fun_as_value_multiarg.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_multiarg.chpl)
- [ ] [passFnsToCChapel.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel.chpl)
- [ ] [futures-doc-taskfn.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-taskfn.chpl)
- [ ] [lambda_const_ret_type.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_const_ret_type.chpl)
- [ ] [Grid_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/grid/Grid_AdvectionCTU_driver.chpl)
- [ ] [futures-waitall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-waitall.chpl)
- [ ] [futures-doc-waitall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-waitall.chpl)
- [ ] [futures-doc-chaining2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-chaining2.chpl)
- [ ] [futures-doc-simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-simple.chpl)
- [ ] [futures-simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-simple.chpl)
- [ ] [futures-task-function.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-task-function.chpl)
- [ ] [futures-doc-chaining1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-chaining1.chpl)
- [ ] [futures-chaining1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-chaining1.chpl)
- [ ] [futures-doc-validity.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-validity.chpl)
- [ ] [futures-chaining2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-chaining2.chpl)
- [ ] [return_first_class_function.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/return_first_class_function.chpl)
- [ ] [common_fp_idioms.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/common_fp_idioms.chpl)
- [ ] [lambda_simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_simple.chpl)
- [ ] [lambda_assign.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_assign.chpl)
- [ ] [fun_type_annot_void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_void.chpl)
- [ ] [fun_as_value_crossmodule2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_crossmodule2.chpl)
- [ ] [fun_parent_test.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_parent_test.chpl)
- [ ] [fun_type_annot.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot.chpl)
- [ ] [fcf-rettype.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-rettype.chpl)
- [ ] [fcf-argtypes.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-argtypes.chpl)

### PR DESCRIPTION
**Pull request by dlongnecke-cray**
This PR fixes a memory leak related to the use of first class functions. In the past, the wrapper that instantiates an instance of a FCF returned an `unmanaged` class instance.

This PR resumes efforts started by @benharsh, and makes the FCF class instance `shared` instead.

Some of the issues mentioned by Ben related to `writeThis` for FCFs seem to no longer be relevant (or at least, I did not run into issues). 

To fix test failures with `test/functions/jturner/return_first_class_function.chpl` as a result of using shared (related to user specified FCF return types), I altered the code that maps FCF return types to return a resolved handle to `_shared(parent)` instead of `parent`.

This workaround enables existing tests to pass without incident.

Resolves #7890.

---

Testing:

- [x] `ALL` on `linux64` when `CHPL_COMM=none`
- [x] `ALL` on `linux64` when `CHPL_COMM=gasnet`

### CODE REVIEW

File: compiler/resolution/functionResolution.cpp [hunk 1]
```diff
@@ -3515,6 +3515,23 @@ static void generateUnresolvedMsg(CallInfo& info, Vec<FnSymbol*>& visibleFns);
...
+static bool isSharedFcfWrapper(Type* t);
+
+static bool isSharedFcfWrapper(Type* t) {
+
+  //
+  // TODO: Is there a better way to do this besides strcmp? We should figure
+  // this out pronto to prevent any possibility of user types from passing
+  // this check.
+  //
+  if (!strncmp("shared ", t->name(), 7)) {
```
Comment (benharsh) [inline compiler/resolution/functionResolution.cpp]: You should do something more like:
```cpp
if (AggregateType* at = toAggregateType(t)) {
  if (at->getRootInstantiation() == dtShared) {
    return ...
  }
}

**Comment by dlongnecke-cray** [comment]
Results of paratest with memleaks:

```
   327158256  library/packages/LockFreeQueue/interleavedTest.chpl
   327158224  library/packages/LockFreeStack/interleavedTest.chpl
    25166448  library/packages/LockFreeQueue/consistencyCheck.chpl
    25166424  library/packages/LockFreeStack/consistencyCheck.chpl
      130904  mason/mason/modify/masonModifyTest.chpl
        1024  errhandling/ferguson/loopexprs-caught.chpl
         672  library/packages/EpochManager/sharedMemory/sharedMemory.chpl
         576  library/packages/EpochManager/distributedMemory/distributedMemory.chpl
         240  expressions/if/expr/inside-field.chpl
         160  arrays/ferguson/from/iterator/for-yields-no-arrays.chpl
         160  types/tuple/stonea/returnArrayTuple.chpl
         160  arrays/deitz/runtime_types/test_array_type4.chpl
         160  arrays/deitz/runtime_types/test_array_type3.chpl
         152  studies/hpcc/STREAMS/bradc/stream-block1dclass.chpl
         128  associative/ferguson/plus-reduce-assoc.chpl
         128  associative/bharshbarg/domains/reduceArrOfAssocDom.chpl
         120  distributions/ferguson/islayout.chpl
         104  mason/publish/tests/packageName.chpl
          96  errhandling/ferguson/returns-in-try.chpl
          96  errhandling/parallel/forall-wrap-first-error.chpl
          80  types/records/sungeun/classInRecord.chpl
          80  arrays/deitz/runtime_types/test_array_type1.chpl
          80  functions/vass/type-and-param-function-arg-conversions.chpl
          80  classes/bradc/arrayInClass/genericClassArray-anon.chpl
          80  arrays/shapes/skyline.when-empty.chpl
          80  arrays/deitz/runtime_types/test_array_type2.chpl
          72  errhandling/psahabu/defer-throw-fatal.chpl
          64  trivial/sidelnik/reduction.chpl
          48  parallel/forall/reduce/intents/ri-6-user-instance.chpl
          48  sparse/engin/dsiFuncsSpsBlk.chpl
          48  errhandling/parallel/forall-throws.chpl
          48  errhandling/parallel/forall-throws-subtasks.chpl
          48  parallel/forall/task/private/vars/block.chpl
          48  parallel/taskPar/sungeun/private.chpl
          48  users/engin/sparse_bulk/sparseBulkOpts.chpl
          48  modules/vass/SSCA2-with-Private-1.chpl
          48  sparse/engin/dsiFuncs.chpl
          48  errhandling/parallel/forall-range-throws.chpl
          48  users/engin/sparse_bulk/sparseBulk.chpl
          48  distributions/sungeun/equality1.chpl
          48  users/engin/sparse_bulk/irv.chpl
          48  users/engin/sparse_bulk/sparseAdd2D.chpl
          48  users/engin/partial_reduction_support/unit_tests/sparsePartialThese.chpl
          48  modules/vass/SSCA2-with-Private-2.chpl
          48  users/engin/sparse_bulk/sparseBulk2D.chpl
          48  distributions/sungeun/equality2.chpl
          32  statements/defer/defer-manual-container-throws.chpl
          32  errhandling/psahabu/check-returns-good.chpl
          32  library/packages/EpochManager/atomicObjects/atomicObjectsTest.chpl
          24  llvm/tbaa/tbaa_scalar.chpl
          16  classes/initializers/postInit/class-nongeneric.chpl
          16  classes/initializers/postInit/class-generic.chpl
           8  memory/ferguson/test1.chpl
```

Looks like FCF leaks are gone!
