### PR TITLE
Fix bug with importing or using nested symbols by default

### LINKED ISSUE #15347: Compiler does not parse library module files if only a submodule is used/imported
### Summary of Problem
parser.cpp's `ensureRequiredStandardModulesAreParsed` currently ignores uses and imports of nested modules, due to needing to resolve the full path (which hasn't happened at parse time).  In the internal/standard/package modules today, this is not a problem because we always use or import the top level module as well when we need it, meaning that we have parsed the necessary file.  However, it is entirely possible to write a hierarchy that could trigger this situation, where an internal module required a submodule but didn't care as much about the parent module, and in this case we can't resolve the parent module due to never parsing the file.

### Steps to Reproduce

**Source Code:**

Fake internal module:
int/ChapelNumLocales.chpl 
```chapel
module ChapelNumLocales {
  private use ChapelBase;

  import TOML.TomlParser; // This is a nested package module

  var whatever = TomlParser.debugTomlParser; // Can we access its symbols?

  extern proc chpl_comm_default_num_locales(): int;
  config const numLocales = chpl_comm_default_num_locales();
}
```
Client code that relies on a fake symbol:
foo.chpl
```chapel
 writeln(whatever);
```

**Compile command:**
`chpl foo.chpl --prepend-internal-module-dir int`

**Associated Future Test(s):**
[`test/modules/path/checkNestedModule.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/modules/path/checkNestedModule.chpl) #15348 

### Configuration Information

- Output of `chpl --version`: 1.21.0 pre-release

### LINKED ISSUE #15639: Certain imports in default-used modules produces compiler error
### Summary of Problem

Importing an identifier of certain modules from within certain standard/package modules produces a compiler error when compiling a program that _doesn't_ use the standard/package module.

It seems like this happens only when the standard/package module is used by default (such as `Random` or `Sort`), and only happens with certain imports e.g. `Set.set`, but not `List.list`.

I expect these imports to compile and run successfully, since they work in user programs as well.

We stumbled over this in #15154

### Steps to Reproduce

Add this to `Random.chpl`:

```chapel
import Set.set;
```

A program that does not `use Random` fails, such as the `make check` program:

```sh
> make check
$CHPL_HOME/modules/standard/Random.chpl:69: error: Cannot find symbol 'Set'
```

A program that does `use Random` succeeds:

```chpl
// foo.chpl
use Random;
writeln('success');
```

```sh
> chpl foo.chpl
> ./foo
success
```

### Other data points

These imports produce the error:

- `import Set.set;`
- `import Map.map;`

These imports do not produce the error:

- `import Set;`
- `import Map;`
- `use Set;`
- `use Map;`
- `import List.list;`

Adding the import to these modules produces the error:

  - `Random.chpl`
  - `Sort.chpl`

Adding the import to these modules does not:
  - `ZMQ.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.23.0 pre-release (15a0368beb)

### PR DESCRIPTION
**Pull request by lydia-duncan**
The parser used to ignore uses and imports involving nested symbols when
determining whether to parse a file by default.  Unfortunately, this meant that
if there wasn't an import or use of a top level module in the file, we'd just fail
to parse the file and as a result fail to find symbols defined within it.

I was able to write a fake hierarchy that exhibited this behavior, and Ben A
ran into a situation that triggered it in real code, involving the Random module.

This change rectifies that error, by always parsing a file with the first symbol in
the nested access - I have logically assured myself that this works, because
even in the case where symbols have been brought into the file due to
reexporting, the reexport itself will eventually lead us to their file and their
definition (I added a case demonstrating this).

Resolves #15639 
Resolves #15347 
Resolves Cray/chapel-private#1072

Note: While writing tests for this branch, I found a separate bug with reexporting
from different files that is not handled here.  That bug is listed in #15915 

<details>

In parser.cpp:
When parsing, if the moduleExpr is not an UnresolvedSymExpr, check if it's a
dot call expression and if so use the first argument as the moduleExpr.  Otherwise
just continue.

With #15639 resolved, update Random.chpl to `import Set.set` instead of just `Set`
and replace the qualified access with an unqualified access.

</details>

Testing changes:
- resolved the future tracked by #15347, replacing its reference to TOML with
a reference to a fake internal module (since using TOML before everything else
was resolved resulted in some circular dependencies)
- Added a test of if the symbol being referred to was from a top-level
module that was reexported into that scope from another file, as referred to in the
third paragraph

Passed a full paratest with futures

### CODE REVIEW

**Comment by lydia-duncan** [comment]
@mppf or @bradcray - since you both touched this code recently, would one of you be willing to review?  Should be relatively quick
@ben-albrecht - was the update to Random okay?  Are there other cases I should replace?

**Comment by ben-albrecht** [comment]
> @ben-albrecht - was the update to Random okay? Are there other cases I should replace?

That's the only one I am aware of. Thanks!

File: compiler/parser/parser.cpp [hunk 1]
```diff
@@ -414,7 +414,19 @@ static void ensureRequiredStandardModulesAreParsed() {
       UnresolvedSymExpr* oldModNameExpr = toUnresolvedSymExpr(moduleExpr);
 
       if (oldModNameExpr == NULL) {
-        continue;
+        // Allow us to find symbols due to nested references
```
Comment (bradcray) [inline compiler/parser/parser.cpp:417]: The term "nested reference" doesn't really mean much to me intuitively.  I think the intent of this comment would be clearer if it said something like "Handle the case of `[use|import] Mod.symbol` by extracting `Mod` from the `Mod.symbol` expression."

File: compiler/parser/parser.cpp [hunk 2]
```diff
@@ -414,7 +414,19 @@ static void ensureRequiredStandardModulesAreParsed() {
...
+        if (CallExpr* call = toCallExpr(moduleExpr)) {
+          if (call->isNamedAstr(astrSdot) &&
+              isUnresolvedSymExpr(call->get(1))) {
+            oldModNameExpr = toUnresolvedSymExpr(call->get(1));
```
Comment (bradcray) [inline compiler/parser/parser.cpp:421]: To avoid the repeated `*UnresolvedSymExpr()` calls (which essentially do the same thing twice, I'd probably refactor this to:

```chapel
if (CallExpr* call = toCallExpr(moduleExpr)) {
  UnresolvedSymExpr* use = toUnresolvedSymExpr(call->get(1));
  if (call->isNamedAstr(astrSdot) && use) {
    oldModNameExpr = use;
  }
}
```

I might also avoid the duplicate else...continue cases by following the conditional up with:

```chapel
 if (oldModNameExpr == NULL) {
  continue;
}
```

(which would also reduce the diff with the previous version).

**Comment by bradcray** [comment]
Other than those style comments, this looked fine to me.  I did not try running the tests that were modified/added, but also didn't see obvious problems with them.

**Comment by bradcray** [comment]
Looks good to me assuming it still works, thanks!
