### PR TITLE
Fix several memory leaks

### LINKED ISSUE #9689: Enabling fields with generic declared types introduced memory leaks
https://github.com/chapel-lang/chapel/pull/9489 introduced several new memory leaks:

https://chapel-lang.org/perf/chapcs/?startdate=2018/05/13&enddate=2018/05/19&graphs=memoryleaksforalltests,numberoftestswithleaks (seen on the 17th)

Looking at a partial diff of `diff memleaks.2018-05-16.nightlyfull.log memleaks.2018-05-17.nightlyfull.log`:
```diff
246a254
>       192400  test.chpl
275a284
>         3216  assign.chpl
292a302
>         1824  writef_readf.chpl
295a306,308
>         1584  forwardDefaultDom.chpl
>         1584  forwardDefaultArr.chpl
>         1584  dataPar2.chpl
297a311
>         1520  mason-chpl-version-update.chpl
303d316
<         1376  mason-chpl-version-update.chpl
327a341
>          864  equality.chpl
337a352
>          704  localDataPar.chpl
359a375
>          480  test_forall_of_arrays_is_parallel.chpl
372a389
>          384  test_2D_whole_array_assignment_is_parallel.chpl
378c395,396
<          272  test.chpl
---
>          288  test_whole_array_assignment_of_array_promotion_is_parallel.chpl
>          264  digits.chpl
394a413,418
>          192  test_reduction_of_forall_expression_is_parallel.chpl
>          192  test_whole_array_assignment_is_parallel.chpl
>          192  test_whole_array_assignment_of_elemental_value_is_parallel.chpl
>          192  test_reduction_of_array_promotion_is_parallel.chpl
>          192  test_reduction_of_nested_forall_expressions_is_parallel.chpl
>          192  generic-field-unmanaged-borrowed.chpl
400a425
>          160  readfre.chpl
406a432
>          152  regex.chpl
408c434,435
<          136  regex.chpl
---
>          144  mason-chpl-version-new.chpl
>          144  masonNewTest.chpl
410d436
<          136  mason-chpl-version-new.chpl
412,413d437
<          136  masonNewTest.chpl
<          136  readfre.chpl
472a497
>           64  test_reduction_is_parallel.chpl
477a503
>           48  generic-field-default-init.chpl
478a505,506
>           48  coercions-shared.chpl
>           48  generic-field-integral.chpl
480a509
>           48  generic-field.chpl
490a520
>           40  recordio.chpl
502a533
>           32  coercions.chpl
508a540
>           24  coercions-to-init-borrowed.chpl
511a544
>           20  weirdParamInit4.chpl
518a552
>           16  read-string-zero.chpl
521d554
<           16  coercions-shared.chpl
522a556
>           16  coercions-generic.chpl
533d566
<           16  coercions.chpl
552a586
>            8  scanstring-precision.chpl
561a596
>            8  json-enum.chpl
```

So new leaks for: 

    assign.chpl
    writef_readf.chpl
    forwardDefaultDom.chpl
    forwardDefaultArr.chpl
    dataPar2.chpl
    mason-chpl-version-update.chpl
    equality.chpl
    localDataPar.chpl
    test_forall_of_arrays_is_parallel.chpl
    test_2D_whole_array_assignment_is_parallel.chpl
    test_whole_array_assignment_of_array_promotion_is_parallel.chpl
    digits.chpl
    test_reduction_of_forall_expression_is_parallel.chpl
    test_whole_array_assignment_is_parallel.chpl
    test_whole_array_assignment_of_elemental_value_is_parallel.chpl
    test_reduction_of_array_promotion_is_parallel.chpl
    test_reduction_of_nested_forall_expressions_is_parallel.chpl
    generic-field-unmanaged-borrowed.chpl
    test_reduction_is_parallel.chpl
    generic-field-default-init.chpl
    generic-field-integral.chpl
    generic-field.chpl
    recordio.chpl
    coercions-to-init-borrowed.chpl
    weirdParamInit4.chpl
    read-string-zero.chpl
    coercions-generic.chpl
    scanstring-precision.chpl
    json-enum.chpl

And increased leaks for:

    mason-chpl-version-update.chpl
    test.chpl
    regex.chpl
    mason-chpl-version-new.chpl
    masonNewTest.chpl
    readfre.chpl
    coercions-shared.chpl
    coercions.chpl

### LINKED ISSUE #9809: new memory leak for constructor after generic field improvements
PR #9489  added to resolveInitVar:

```
+  // Clear FLAG_INSERT_AUTO_DESTROY_FOR_EXPLICIT_NEW
+  // since the result of the 'new' will "move" into
+  // the variable we are initializing.
+  src->removeFlag(FLAG_INSERT_AUTO_DESTROY_FOR_EXPLICIT_NEW);
+
```

This adds a leak to the following code but only if constructors are used (not if initializers are used):

``` chapel
record MyRecord {
  var a: string;
}


proc test() {
  var r:MyRecord = new MyRecord("Hello");
}
test();
```

What should we do about this?

### PR DESCRIPTION
**Pull request by mppf**
* fixes RecordParser to avoid useless cast & optimize it
* add tests for useless string cast leak
* fixes leak with useless cast by removing special cases for initCopy
* while there, removed FLAG_DONOR_FN, which as apparently no longer required
* fixes json-enum leak (described in issue #9809) by moving the removeFlag 
  call to the initializers case
* added tests for initialization leak

Resolves #9809
Resolves #9689

An earlier version passed valgrind testing.
Leaks no more memory than master in test/release/examples/primers.
Passed valgrind testing of test/release/examples/primers.
Passed full local testing.

Reviewed by @benharsh - thanks!

### CODE REVIEW

File: compiler/resolution/postFold.cpp [hunk 1]
```diff
@@ -712,15 +712,15 @@ bool requiresImplicitDestroy(CallExpr* call) {
...
-    if (parent->hasFlag(FLAG_DONOR_FN)                        == false &&
+    if (//parent->hasFlag(FLAG_DONOR_FN)                        == false &&
         isRecord(fn->retType)                                 == true  &&
         fn->hasFlag(FLAG_NO_IMPLICIT_COPY)                    == false &&
         fn->isIterator()                                      == false &&
         fn->retType->symbol->hasFlag(FLAG_RUNTIME_TYPE_VALUE) == false &&
-        fn->hasFlag(FLAG_DONOR_FN)                            == false &&
-        fn->hasFlag(FLAG_INIT_COPY_FN)                        == false &&
+        //fn->hasFlag(FLAG_DONOR_FN)                            == false &&
+        //fn->hasFlag(FLAG_INIT_COPY_FN)                        == false &&
```
Comment (benharsh) [inline compiler/resolution/postFold.cpp]: I suspect you already plan to remove these, just wanted to double-check.

Comment (mppf) [reply compiler/resolution/postFold.cpp]: yes in fact I plan to entirely remove FLAG_DONOR_FN also. Thanks for the reminder - I had forgotten.
