### PR TITLE
Avoid double-deinit upon throws from a forall loop

### LINKED ISSUE #18773: segfault (use-after-free error) when calling throwing function within a forall loop
### Summary of Problem

[reported by @jlbyrne-hpe]

When calling a throwing function within a forall loop over a distributed array,
we seem to be getting a segfault due to a use-after-free style error as
reported by valgrind.  Our guess is that the error is not properly getting
propagated out of the forall loop as it should be.

If the forall loop is changed to a for loop, the problem goes away, and I have
also not been able to reproduce the issue in similar cases such as:

* a forall loop over a range
* a forall loop over a range with an on-clause
* a nested coforall loop + on-clause similar to what I think of the block array as doing (though it is actually using leader-follower today)

In some cases, wrapping the throwing function within a `try { }` within the
forall loop's body makes the error go away, but not in the future filed below.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;

var A = newBlockArr({1..10}, real);

proc throwingFunction() throws {
  throw new owned Error("die!");
}

proc throwingCaller() throws {
  forall a in A {
    throwingFunction();
  }
}

proc main() {
  try { throwingCaller(); }
  catch e { writeln("Caught an error!"); }
}
```

**Associated Future Test(s):**

[`test/errhandling/parallel/forall-calls-throwing-fn2.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/errhandling/parallel/forall-calls-throwing-fn2.chpl
          ) #18774

### Configuration Information

- Output of `chpl --version`: `chpl version 1.26.0 pre-release (cf9569b7ad)`

### PR DESCRIPTION
**Pull request by vasslitvinov**
Resolves #18773.

This PR changes the iterator deinitialization actions performed upon a yield
when the yield occurs inside a forall. Formerly these actions included
everything needed to be deinitialized upon returning from the iterator.
Now they include everything upon exiting the forall loop. The impact is
observable when the loop that is using the iterator throws exceptions
in multiple tasks. Before the iterator variables outside the forall loop
would be deinitialized by each task, i.e., multiple times. Now they are
deinitialized just once after the forall loop completed. In this example:
```chpl
iterator IT() { // assume it is the standalone iterator
  var D: domain(1);
  forall i in IT2() {
    yield i;
  }
  writeln();
}

forall idx in IT() {
  throwingFunction();
}
```
the forall loop would be lowered into:
```chpl
var D: domain(1)
forall i in IT2() {
  throwingFunction();
  if it threw an error {
    deinit D;
    goto end_IT;
  }
}
writeln();
deinit D;
end_IT:;
```
now it is lowered into:
```chpl
var D: domain(1)
forall i in IT2() {
  throwingFunction();
  if it threw an error {
    goto forall_IBB_break_label;
  }
}
forall_IBB_break_label:
if there was an error {
  deinit D;
  goto end_IT;
}
deinit D;
writeln();
end_IT:;
```

Testing:
* [x] standard paratest
* [x] multilocale paratest
* [x] asan paratest
* [x] memleaks paratest

### CODE REVIEW

File: compiler/include/passes.h [hunk 1]
```diff
@@ -141,6 +141,10 @@ bool checkIteratorFromForExpr(Expr* ref, Symbol* shape);
 // LoopExpr.cpp
 bool isOuterVarLoop(Symbol* sym, Expr* enclosingExpr);
 
+// errorHandling.cpp
+Symbol*   findErrorVarForHandlerLabel(LabelSymbol* handlerLabel);
+GotoStmt* gotoForallErrorHandler(ForallStmt* fs);
```
Comment (mppf) [inline compiler/include/passes.h:146]: I would expect these in compiler/include/errorHandling.h

Comment (mppf) [inline compiler/include/passes.h:146]: Need comments about what gotoForallErrorHandler function does - it is named like it doesn't have side effects but it does add stuff to the AST. What does it add?

File: compiler/passes/errorHandling.cpp [hunk 2]
```diff
@@ -1071,6 +1082,91 @@ void ErrorCheckingVisitor::exitDeferStmt(DeferStmt* node) {
...
+  return NULL;
+}
+
+// This mimicks the control flow of a thrown error, for an IBB.
+// The label is created analogously to ErrorHandlingVisitor::enterForallStmt().
+// The goto looks like the one created in ErrorHandlingVisitor::gotoHandler().
+// This ignores try-blocks because an IBB is placed in an iterator to handle
+// the errors thrown in the loop body. Iterator try-blocks, if any, should not
+// be used to handle the loop body's errors.
+static ErrorVarAndGoto forallHandlerForIBB(ForallStmt* fs) {
```
Comment (mppf) [inline compiler/passes/errorHandling.cpp:1118]: should it be named like `constructForallHandlerForIBB` or `create` or `add` or ... ?

Comment (mppf) [reply compiler/passes/errorHandling.cpp:1118]: Oh it seems maybe you chose this name because it is idempotent? Needs to be clearer in the comment above it.

File: compiler/resolution/lowerIterators.cpp [hunk 3]
```diff
@@ -1919,6 +1907,16 @@ replaceErrorFormalWithEnclosingError(SymExpr* se) {
 // out of the enclosing loop. See also the PR message for #12963.
 //
 
+// 'bbcopy' may come from an IBB that simulates a throw and so have
+// a goto at the end. If so, remove the goto that we are inserting before.
+// Without this, multiple deinits may occur, ex.
+//   test/errhandling/parallel/forall-calls-throwing-fn2.chpl
+//
+static void adjustMultipleGotos(BlockStmt* bbcopy, GotoStmt* gt) {
+  if (isGotoStmt(bbcopy->body.tail))
```
Comment (mppf) [inline compiler/resolution/lowerIterators.cpp:1916]: Should this only apply to a particular type of goto, like GOTO_BREAK_ERROR_HANDLING e.g.?

**Review by mppf — APPROVED** [review]
This looks like a good improvement to me. However we have more experience with the earlier (buggy) version, so we have to make a call about whether we want this in the release or not. If we think that throwing from foralls was in bad shape, this PR is probably a good candidate for the release. (Which is more or less how I feel about it). Either way we will need to watch testing closely.

File: compiler/resolution/lowerIterators.cpp (hunk 3 above)
Comment (vasslitvinov) [reply compiler/resolution/lowerIterators.cpp:1916]: I believe that duplicate gotos may cause an issue regardless of their kind. So I will keep it unconditional for now.
