### PR TITLE
Fix record comparisons to have lexicographical order

### LINKED ISSUE #14783: record comparison not lexicographic order, and not a total order?
My impression of #11347 was that the desire for a record comparison operator was for sorting / search-tree searching purposes.  And @bradcray 's concern that the comparison between records would depend on the order of the fields of the record suggests a lexicographic ordering.

But as implemented, it's not.  As described in the spec changes in #14777, `r1 <= r2` for example returns true only if every field of `r1` compares less than or equal to the corresponding field of `r2`.  This means that there are some records e.g. `r1=(1,2)` and `r2=(2,1)` where `r1` doesn't compare as `<`, `==`, or `>` `r2`, which wouldn't work for using that comparison for some of the uses described in the issue.

I can't tell though if the issue shifted to having a separate `treeOrder()` or `default_comparator()` for cases that need a total ordering?  I don't see the implemented behavior even alluded to in the issue though.

### Steps to Reproduce

**Source Code:**

```chapel
{
  record R {
    var x, y: int;
  }

  var small = new R(1, 1);
  var mid1 = new R(1, 2);
  var mid2 = new R(2, 1);
  var big = new R(2, 2);


  var Rs = [ small, mid1, mid2, big ];

  for r1 in Rs {
    for r2 in Rs {
      writeln(r1, " == ", r2, ": ", r1 == r2);
      writeln(r1, " < ", r2, ": ", r1 < r2);
      writeln(r1, " <= ", r2, ": ", r1 <= r2);
      writeln(r1, " > ", r2, ": ", r1 > r2);
      writeln(r1, " >= ", r2, ": ", r1 >= r2);
      writeln(r1, " != ", r2, ": ", r1 != r2);
      writeln();
    }
  }
}
```

Particularly, this part of the output:

```
(x = 1, y = 2) == (x = 2, y = 1): false
(x = 1, y = 2) < (x = 2, y = 1): false
(x = 1, y = 2) <= (x = 2, y = 1): false
(x = 1, y = 2) > (x = 2, y = 1): false
(x = 1, y = 2) >= (x = 2, y = 1): false
(x = 1, y = 2) != (x = 2, y = 1): true
```

I was expecting `(1,2) < (2,1)` to be true, among others.

edit 1/19: fix bug in test code, which didn't affect this particular stanza.

**Associated Future Test(s):**

None yet.

### Configuration Information

```
chpl version 1.21.0 pre-release (543d7d7)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

### PR DESCRIPTION
**Pull request by e-kayrakli**
This PR fixes the record comparison so that it has lexicographical ordering. The
inital PR that first added these functions were #14752.

Resolves #14783.

This change mainly involves separating the functions that build the bodies of
the comparison overloads. I think all this can still be done within a single
function, but I am choosing code redundancy over complicated logic.

Test:
- [x] standard
- [x] gasnet

### CODE REVIEW

File: compiler/passes/buildDefaultFunctions.cpp [hunk 1]
```diff
@@ -811,44 +820,142 @@ static void buildRecordComparisonFunc(AggregateType* ct, const char* op) {
...
-        fn->insertAtTail(new CondStmt(elemComp,
+      CallExpr *elemComp = new CallExpr("!=", left, right);
+      fn->insertAtTail(new CondStmt(elemComp,
+                                    new CallExpr(PRIM_RETURN, gTrue)));
+    }
+  }
+  // either it is an empty record, and we didn't add any meaningful comparisons,
+  // or we added those comparisons but they never returned
+
+  // for !=, in either case we return fales
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: Typo on `fales` :)

File: compiler/passes/buildDefaultFunctions.cpp [hunk 2]
```diff
@@ -811,44 +820,142 @@ static void buildRecordComparisonFunc(AggregateType* ct, const char* op) {
...
+      {
+        Expr* left = new CallExpr(tmp->name, gMethodToken, arg1);
+        Expr* right = new CallExpr(tmp->name, gMethodToken, arg2);
+        CallExpr *elemCompTrue = new CallExpr("<", left, right);
+        fn->insertAtTail(new CondStmt(elemCompTrue,
                                       new CallExpr(PRIM_RETURN, gTrue)));
       }
-      else {
-        fn->insertAtTail(new CondStmt(new CallExpr("!", elemComp), 
+      {
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: This doesn't look like an if/else branch?  You've got two `{` after the if statement, and then you close one and open another one?  Was that intentional?

File: compiler/passes/buildDefaultFunctions.cpp [hunk 3]
```diff
@@ -811,44 +820,142 @@ static void buildRecordComparisonFunc(AggregateType* ct, const char* op) {
...
+  // or we added those comparisons but they never returned
 
-  // find the return value and add the return statement
-  VarSymbol* ret;
-  if (fn->body->length() > 0) { // we added comparison statements: not empty
-    if (isNotEqual)
-      ret = gFalse;
-    else
-      ret = gTrue;
+  // for <, in either case we return false
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: This comment is slightly confusing.  I think what you're doing here is distinguishing between `<` and `<=` but the comment refers to `<` and the first branch seems to correspond to `<=`?

File: compiler/passes/buildDefaultFunctions.cpp [hunk 4]
```diff
@@ -811,44 +820,142 @@ static void buildRecordComparisonFunc(AggregateType* ct, const char* op) {
...
+        CallExpr *elemCompFalse = new CallExpr("<", left, right);
+        fn->insertAtTail(new CondStmt(elemCompFalse,
+                                      new CallExpr(PRIM_RETURN, gFalse)));
+      }
+    }
+  }
+  // either it is an empty record, and we didn't add any meaningful comparisons,
+  // or we added those comparisons but they never returned
+
+  // for <, in either case we return false
```
Comment (lydia-duncan) [inline compiler/passes/buildDefaultFunctions.cpp]: Ditto here.  Also, both this and the previous function refer to `<`, but I think one of them should refer to `>` (it should be this one if I'm understanding correctly)

File: compiler/passes/buildDefaultFunctions.cpp (hunk 2 above)
Comment (lydia-duncan) [reply compiler/passes/buildDefaultFunctions.cpp]: I'd rather they were just two code blocks separated only by line breaks, personally

**Comment by e-kayrakli** [comment]
@lydia-duncan -- thanks!

Re-running tests out of paranoia

- [ ] standard local
- [ ] gasnet
