### PR TITLE
Adjust captureTaskIntentValues to avoid PRIM_DEREF

### LINKED ISSUE #19128: Explicit `const ref` intent on an owned class argument results in a segmentation fault
### Summary of Problem

The following piece of code segfaults (some previous iterations at obtaining the minimal example also produced deadlocks):

```chapel
use BlockDist;
use CPtr;

const OnePerLocale = LocaleSpace dmapped Block(LocaleSpace);

class BasisStates {
  var size : int;
  var representatives : [OnePerLocale] [0 ..# size] uint(64);
}

proc foo(const ref basisStates : BasisStates)
{
  coforall loc in Locales do on loc {
    writeln(c_ptrTo(basisStates.representatives[loc.id][0 ..# 1]));
  }
}

proc main()
{
  var representatives : [OnePerLocale] [0 ..# 13] uint(64) =
    [[31, 47, 55, 87, 91, 93, 103, 107, 155, 171, 173, 179, 341]:uint];
  var states = new BasisStates(13, representatives);
  foo(states);
}
```

* If `const ref basisStates` in the signature of `foo` is replaced with `basisStates`, things start to work.
* If `coforall` loop in `foo` is replaced by a `for` loop, things start to work.

There are two issues here. The important one is that the above code should not crash since passing owned classes by `const ref` is the default behavior, i.e. removing `const ref` should not change anything.

The less important issue (which I'm also less certain about) is that the above code should not compile at all... `c_ptrTo` expects a `ref`, but we pass it a `const ref`, don't we? If `const ref` is replaced by `ref` in the example, it still crashes, so the first issue still stands.

**Compile command:**

`chpl -o error error.chpl`

**Execution command:**

`./error -nl1`

### Configuration Information

- Output of `chpl --version`:
   ```
  chpl version 1.25.0
    built with LLVM version 11.1.0
   ```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```

Tagging @bradcray because of our discussion on gitter.

### PR DESCRIPTION
**Pull request by mppf**
The PRIM_DEREF is creating a temporary that is deallocated
which leads to use-after-free.

(https://github.com/chapel-lang/chapel/issues/19128#issuecomment-1023675134 has more details about the bug).

Resolves #19128

This PR also adds two test cases from that issue.

Reviewed by @vasslitvinov 

Thanks to @bradcray for help testing this patch

- [x] full gasnet testing
- [x] full valgrind testing
- [x] full valgrind + --no-local testing
- [x] regular full local testing

### CODE REVIEW

File: compiler/resolution/functionResolution.cpp [hunk 1]
```diff
@@ -6149,7 +6149,8 @@ static void captureTaskIntentValues(int        argNum,
 
       } else if (isReferenceType(varActual->type) ==  true &&
                  isReferenceType(capTemp->type)   == false) {
-        marker->insertBefore("'move'(%S,'deref'(%S))", capTemp, varActual);
+
+        marker->insertBefore(new CallExpr(PRIM_ASSIGN, capTemp, varActual));
```
Comment (vasslitvinov) [inline compiler/resolution/functionResolution.cpp:6153]: No big deal -- do you really need this new empty line?

**Review by vasslitvinov — APPROVED** [review]
Looks good, thank you!
