### PR TITLE
Allocate and free array memory natively and separate array alloc phases.

### LINKED ISSUE #11284: clean up the runtime memory array alloc "call me back" interface
Currently, when `chpl_mem_array_alloc()` allocates array memory from the comm layer it returns a flag to its caller saying that the same `chpl_mem_array_alloc()` call should be repeated once the array initialization is done.  The comm layer's post-alloc function is then invoked from this second call, to register the memory with the NIC if that is needed.  Thus we get good NUMA locality on registered array memory, by registering only after initializing it.

This interface was a hack to get separate array allocation done quickly, but both the interface and how we do the calls to it will need to be cleaner for the case where we know the first thing done to an array is a store, so the default init is not needed.  I'm envisioning  keeping the "call me back" flag returned by the array memory allocation function but having the 2nd call be to a separate array mem post-alloc function (with fewer arguments, maybe just the allocated address) in the array allocation interface, and then augmenting the only working comm layer implementation of this (ugni) so that it can manage the registration  if all it has to go by is the caller's array memory address.

The original caller of the array allocation can then save the "call me back" flag in the array descriptor and delay making the second call, to the array mem post-alloc function, until after the array has been stored to the first time.  The only requirements are that that second call must definitely be done eventually if the flag says it's needed, and furthermore must be done before any remote accesses refer to the array's memory.

Any work that relies on avoiding the current default array initialization logic to improve performance will benefit from this change.

### LINKED ISSUE #11312: bug with PRIM_ARRAY_ALLOC
In the referenced test, `data` is incorrectly `nil` within the loop.
With `--no-copy-propagation` the program behaves correctly.

Test:
```
optimizations/copyPropagation/cp-problem2.chpl
```

### PR DESCRIPTION
**Pull request by gbtitus**
We have been using primitives `PRIM_ARRAY_ALLOC` and `PRIM_ARRAY_FREE` for
allocating and freeing array memory, respectively.  Furthermore, to
support getting NUMA locality right with comm layers needing to register
memory to achieve best remote communication performance, allocation was
actually a split-phase operation.  We invoked `PRIM_ARRAY_ALLOC` a first
time to do the allocation, then set NUMA locality on the memory by means
of the default initializer, then invoked `PRIM_ARRAY_ALLOC` a second time
to allow the comm layer to do the registration.

Here, switch from primitives to direct runtime calls for the allocate
and free operations, and also split the two phases of allocation into
separate allocate and post-allocate functions.  This is not only more
elegant, but will also enable delaying the post-allocation step until
after user initialization code has run, when we have more complete
no-init support.  The `PRIM_ARRAY_ALLOC` invocations are replaced with
calls to `chpl_mem_array_alloc()` or `chpl_mem_array_postAlloc()` calls, and
the `PRIM_ARRAY_FREE` invocations with calls to `chpl_mem_array_free()`.
`PRIM_ARRAY_ALLOC` and `PRIM_ARRAY_FREE` are removed from the compiler.  The
`chpl_mem_wide_array_alloc()` and `chpl_mem_wide_array_free()` runtime
wrapper functions are also removed, since they were only called as a
result of expanding the corresponding primitives and are not needed as
direct calls.

The allocation and post-allocation calls need the "raw" array element
size, so there is a new `PRIM_SIZEOF_RAW` primitive to produce that.  We
had hoped to be able to use the existing `c_sizeof()` function for this,
but that unfortunately didn't produce the necessary `sizeof(wide ptr)` in
the no-local and comm!=none cases, for an array over a class type, such
as `Locales[]`.  The existing `PRIM_SIZEOF` primitive also didn't work for
this case.  There is also a small test (`prim_sizeof_raw`) here, to lock
in the behavior of `PRIM_SIZEOF_RAW`.

The `cp-problem2` future is removed.  It pointed out a peculiarity with
`PRIM_ARRAY_ALLOC` which does not occur with direct runtime calls.  This
also resolves #11312.

This resolves #11284.

### CODE REVIEW

File: compiler/AST/primitive.cpp [hunk 1]
```diff
@@ -679,6 +679,9 @@ initPrimitive() {
   // These are used for task-aware allocation.
   prim_def(PRIM_SIZEOF, "sizeof", returnInfoSizeType);
 
+  // sizeof(array.eltType), since CPtr.chpl:c_sizeof() is "not well defined"
+  prim_def(PRIM_SIZEOF_RAW, "sizeof_raw", returnInfoSizeType);
```
Comment (mppf) [inline compiler/AST/primitive.cpp]: Let's call the new one PRIM_SIZEOF_DATA_ELEMENT since it expects the argument is a _ddata, right?

**Comment by gbtitus** [comment]
@bradcray, @mppf is reviewing this, but would you mind taking a quick look also since we've had a brief conversation about the `sizeof()` aspect of it?  And @ronawho, would you look at it post-merge (assuming that happens)?

File: compiler/AST/primitive.cpp [hunk 2]
```diff
@@ -679,6 +679,9 @@ initPrimitive() {
   // These are used for task-aware allocation.
   prim_def(PRIM_SIZEOF, "sizeof", returnInfoSizeType);
```
Comment (mppf) [inline compiler/AST/primitive.cpp]: Let's rename this one to PRIM_SIZEOF_BUNDLE since it's only used in computing the size of the argument bundle for tasks etc.

File: modules/internal/ChapelBase.chpl [hunk 3]
```diff
@@ -831,19 +831,37 @@ module ChapelBase {
     return ret;
   }
 
+  inline proc sizeof_raw(type t): size_t {
```
Comment (mppf) [inline modules/internal/ChapelBase.chpl]: Let's call this _ddata_sizeof_element and have it accept the _ddata type as an argument

File: modules/internal/ChapelBase.chpl [hunk 4]
```diff
@@ -831,19 +831,37 @@ module ChapelBase {
...
                               subloc = c_sublocid_none) {
+    pragma "insert line file info"
+      extern proc chpl_mem_array_alloc(nmemb: size_t, eltSize: size_t,
+                                       subloc: chpl_sublocID_t,
+                                       ref callPostAlloc: bool): c_void_ptr;
     var ret: _ddata(eltType);
-    var callAgain: bool;
-    __primitive("array_alloc", ret, size, subloc, c_ptrTo(callAgain), c_nil);
+    var callPostAlloc: bool;
+    const ret_voidp = chpl_mem_array_alloc(size:size_t, sizeof_raw(eltType),
```
Comment (mppf) [inline modules/internal/ChapelBase.chpl]: can it be _ddata_sizeof_element(ret) ?

File: modules/internal/ChapelBase.chpl [hunk 5]
```diff
@@ -831,19 +831,37 @@ module ChapelBase {
...
+                                           subloc, callPostAlloc);
+    ret = _cast(_ddata(eltType), ret_voidp);
```
Comment (mppf) [inline modules/internal/ChapelBase.chpl]: You should be able to write this as `ret = ret_voidp : ret.type` or `ret = ret_voidp : _ddata(eltType);`

File: modules/internal/ChapelBase.chpl [hunk 6]
```diff
@@ -831,19 +831,37 @@ module ChapelBase {
...
     init_elts(ret, size, eltType);
-    if callAgain then
-      __primitive("array_alloc", ret, size, subloc, c_nil, ret);
+    if callPostAlloc {
+      pragma "insert line file info"
+        extern proc chpl_mem_array_postAlloc(data: c_void_ptr,
+                                             nmemb: size_t, eltSize: size_t);
+      chpl_mem_array_postAlloc(ret_voidp, size:size_t, sizeof_raw(eltType));
```
Comment (mppf) [inline modules/internal/ChapelBase.chpl]: can it be _ddata_sizeof_element(ret) ?

File: modules/internal/ChapelBase.chpl [hunk 7]
```diff
@@ -831,19 +831,37 @@ module ChapelBase {
...
     return ret;
   }
 
   inline proc _ddata_free(data: _ddata, size: integral) {
-    __primitive("array_free", data, size);
+    pragma "insert line file info"
+      extern proc chpl_mem_array_free(data: c_void_ptr,
+                                      nmemb: size_t, eltSize: size_t);
+    chpl_mem_array_free(_cast(c_void_ptr, data),
+                        size:size_t, sizeof_raw(data.eltType));
```
Comment (mppf) [inline modules/internal/ChapelBase.chpl]: Can it be _ddata_sizeof_element(data) ?

**Comment by bradcray** [comment]
I looked enough to see that we net reduced the number of primitives by 1 rather than 2 as I was hoping, and saw the reason why.  I'm fine with this.

File: compiler/AST/primitive.cpp [hunk 8]
```diff
@@ -677,7 +677,10 @@ initPrimitive() {
   prim_def(PRIM_SET_SERIAL, "task_set_serial", returnInfoVoid, true);
 
   // These are used for task-aware allocation.
-  prim_def(PRIM_SIZEOF, "sizeof", returnInfoSizeType);
+  prim_def(PRIM_SIZEOF_BUNDLE, "sizeof_bundle", returnInfoSizeType);
```
Comment (mppf) [inline compiler/AST/primitive.cpp]: `// used for task bundles and for allocating class instances`

File: compiler/AST/primitive.cpp [hunk 9]
```diff
@@ -677,7 +677,10 @@ initPrimitive() {
...
+
+  // sizeof(array.eltType), since CPtr.chpl:c_sizeof() is "not well defined"
```
Comment (mppf) [inline compiler/AST/primitive.cpp]: Not sure this comment helps anymore
